LOGBOOK.LS     Robot Name ROBOT1 28-AUG-21 20:38:06  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'LISTMENU.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE 'HOME_MSG.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE 'HIST.LS' is saved                
28-AUG-21 20:38 :06
========================================
FILE 'GRIP_SETUP.LS' is saved          
28-AUG-21 20:38 :06
========================================
FILE 'GRIP_MSG.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE 'GRIP_CHK.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE 'GETDATA.LS' is saved             
28-AUG-21 20:38 :06
========================================
FILE 'EXITFZONE.LS' is saved           
28-AUG-21 20:38 :06
========================================
FILE 'EXITALL.LS' is saved             
28-AUG-21 20:38 :06
========================================
FILE 'ERRSYS.LS' is saved              
28-AUG-21 20:38 :06
========================================
FILE 'ERRPWD.LS' is saved              
28-AUG-21 20:38 :06
========================================
FILE 'ERRMOT.LS' is saved              
28-AUG-21 20:38 :06
========================================
FILE 'ERRHIST.LS' is saved             
28-AUG-21 20:38 :06
========================================
FILE 'ERREXT.LS' is saved              
28-AUG-21 20:38 :06
========================================
FILE 'ERRCURR.LS' is saved             
28-AUG-21 20:38 :06
========================================
FILE 'ERRCOMM.LS' is saved             
28-AUG-21 20:38 :06
========================================
FILE 'ERRAPP.LS' is saved              
28-AUG-21 20:38 :06
========================================
FILE 'ERRALL.LS' is saved              
28-AUG-21 20:38 :06
========================================
FILE 'ERRACT.LS' is saved              
28-AUG-21 20:38 :06
========================================
FILE 'ENTER2ZONE.LS' is saved          
28-AUG-21 20:38 :06
========================================
FILE 'DSP_WEBP.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE 'CONVEYOR_MSG.LS' is saved        
28-AUG-21 20:38 :06
========================================
FILE 'CMM_CLS_CHUCK.LS' is saved       
28-AUG-21 20:38 :06
========================================
FILE 'CLOSE_T2.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE 'CLOSE_T1.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE 'CHUCK_MSG.LS' is saved           
28-AUG-21 20:38 :06
========================================
FILE 'BGLOGIC_MSG.LS' is saved         
28-AUG-21 20:38 :06
========================================
FILE 'BGLOGIC.LS' is saved             
28-AUG-21 20:38 :06
========================================
FILE 'AIRBLOW20_2.LS' is saved         
28-AUG-21 20:38 :06
========================================
FILE 'AIRBLOW20_1.LS' is saved         
28-AUG-21 20:38 :06
========================================
FILE 'AIRBLOW10_2.LS' is saved         
28-AUG-21 20:38 :06
========================================
FILE 'AIRBLOW10_1.LS' is saved         
28-AUG-21 20:38 :06
========================================
FILE 'ABORTIT.LS' is saved             
28-AUG-21 20:38 :06
========================================
FILE '-BCKEDT-.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE '-BCKED9-.LS' is saved            
28-AUG-21 20:38 :06
========================================
FILE '-BCKED8-.LS' is saved            
28-AUG-21 20:38 :06
========================================
F4(  YES   ) is pressed                
28-AUG-21 20:38 :06
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [UD1:\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
Overwrite?                                                                      
                          YES      NO                                           
========================================
F1(DO_COPY ) is pressed                
28-AUG-21 20:38 :04
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [UD1:\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
                                                                                
DO_COPY                 [CHOICE] CANCEL                                         
========================================
'USB Disk (UD1:)' is selected          
28-AUG-21 20:38 :02
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [***\\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
28-AUG-21 20:38 :00
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [***\\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
                                                                                
DO_COPY                 [CHOICE] CANCEL                                         
========================================
F2(  COPY  ) is pressed                
28-AUG-21 20:37 :58
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
MD:\*.*                           5/32                                          
   1 *       *   (all files)                                                    
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
\\\5\*\\\\\\\LS\\(all\KAREL\listings)\\\                                        
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
                                                                                
 DELETE   COPY  DISPLAY [INSTAL][VIEW ]>                                        
========================================
'Mem Device (MD:)' is selected         
28-AUG-21 20:37 :54
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
                                                                                
   1 *       *   (all files)                                                    
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
\\\5\*\\\\\\\LS\\(ALL\KAREL\LISTINGS)\\\                                        
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
'Set Device' is selected               
28-AUG-21 20:37 :52
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
                                                                                
   1 *       *   (all files)                                                    
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
\\\5\*\\\\\\\LS\\(ALL\KAREL\LISTINGS)\\\                                        
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
28-AUG-21 20:37 :50
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
                                                                                
   1 *       *   (all files)                                                    
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
\\\5\*\\\\\\\LS\\(ALL\KAREL\LISTINGS)\\\                                        
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
                                                                                
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
PREV is pressed                        
28-AUG-21 20:37 :48
========================================
PREV is pressed                        
28-AUG-21 20:37 :46
========================================
F4([CHOICE]) is pressed                
28-AUG-21 20:37 :44
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 UD1:\                                                                          
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [***\\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
                                                                                
DO_COPY                 [CHOICE] CANCEL                                         
========================================
F2(  COPY  ) is pressed                
28-AUG-21 20:37 :42
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
UD1:\*.*                          5/32                                          
   1 *       *   (all files)                                                    
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
\\\5\*\\\\\\\LS\\(all\KAREL\listings)\\\                                        
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
                                                                                
 DELETE   COPY  DISPLAY [INSTAL][VIEW ]>                                        
========================================
'USB Disk (UD1:)' is selected          
28-AUG-21 20:37 :36
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
MC:\*.*                           1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
'Set Device' is selected               
28-AUG-21 20:37 :34
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
MC:\*.*                           1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
28-AUG-21 20:37 :32
--Screen image--------------------------
                                                                                
PNS0001           LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
MC:\*.*                           1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
Menu changed 'FILE'                    
28-AUG-21 20:37 :30
========================================
'File' is selected in 'FILE' MENU flyou
t                                      
28-AUG-21 20:37 :30
========================================
ENTER is pressed                       
28-AUG-21 20:37 :30
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:37 :10
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:37 :10
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:37 :10
========================================
SRVO-003 Deadman switch released       
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:37 :10
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:37 :10
========================================
SYST-045 TP enabled in AUTO mode       
                                       
                                       
STOP.G                        00100110 
28-AUG-21 20:37 :10
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:37 :10
========================================
Focus changed to 'UTILITIES Hints'     
28-AUG-21 20:37 :10
========================================
Menu changed 'UTILITIES Hints'         
28-AUG-21 20:37 :10
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:36 :44
========================================
Override 100%                          
28-AUG-21 20:36 :44
========================================
Menu changed 'UTILITIES Hints'         
28-AUG-21 20:36 :40
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:36 :40
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:36 :40
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:36 :40
========================================
Power failure recovery                 
28-AUG-21 20:36 :36
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
13-AUG-21 11:26 :08
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
13-AUG-21 11:26 :06
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
13-AUG-21 11:26 :06
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 11:24 :54
========================================
FILE 'WAIT4SYNC.TP' is saved           
13-AUG-21 11:24 :54
========================================
FILE 'USERPAGE.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'USERCLR.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'UPDTLOG.LS' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'UPDATE_REF.TP' is saved          
13-AUG-21 11:24 :54
========================================
FILE 'UPDATES.DAT' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'TS1.TP' is saved                 
13-AUG-21 11:24 :54
========================================
FILE 'TPEINS.XML' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'TPACCN.DG' is saved              
13-AUG-21 11:24 :54
========================================
FILE 'TOOL2_OPEN.TP' is saved          
13-AUG-21 11:24 :54
========================================
FILE 'TOOL2_CLOSE.TP' is saved         
13-AUG-21 11:24 :54
========================================
FILE 'TOOL1_OPEN.TP' is saved          
13-AUG-21 11:24 :54
========================================
FILE 'TOOL1_CLOSE.TP' is saved         
13-AUG-21 11:24 :54
========================================
FILE 'SYSVARS.SV' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SYSUIF.SV' is saved              
13-AUG-21 11:24 :54
========================================
FILE 'SYSSERVO.SV' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'SYSPASS.SV' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SYSMAST.SV' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SYSMACRO.SV' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'SYSHOST.SV' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SYSFSAC.SV' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SYSFRAME.SV' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'SYSEIP.SV' is saved              
13-AUG-21 11:24 :54
========================================
FILE 'SYSEGD.SV' is saved              
13-AUG-21 11:24 :54
========================================
FILE 'SYNC2WAIT.TP' is saved           
13-AUG-21 11:24 :54
========================================
FILE 'SWIUPDT.VR' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SWIAUTO.VR' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SWIAUTO.PC' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'SV_ADJST.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'SUMMARY.DG' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'STRREG.VR' is saved              
13-AUG-21 11:24 :54
========================================
FILE 'STATPAGE.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'SHIP.TP' is saved                
13-AUG-21 11:24 :54
========================================
FILE 'SHADOW.DG' is saved              
13-AUG-21 11:24 :54
========================================
FILE 'SENDSYSV.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'SENDEVNT.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'SENDDATA.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK2_WASHOP20.TP' is saved    
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK2_WASHOP10.TP' is saved    
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK2_OP20.TP' is saved        
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK2_OP10.TP' is saved        
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK1_WASHOP20.TP' is saved    
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK1_WASHOP10.TP' is saved    
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK1_OP20.TP' is saved        
13-AUG-21 11:24 :54
========================================
FILE 'RPS_OK1_OP10.TP' is saved        
13-AUG-21 11:24 :54
========================================
FILE 'ROSIPCFG.XML' is saved           
13-AUG-21 11:24 :54
========================================
FILE 'RLSVRLUT.VR' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'RLSVEXGEN6.VR' is saved          
13-AUG-21 11:24 :54
========================================
FILE 'RLSETMTR.VR' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'RIPESTAT.DG' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'RIPELOG.DG' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'REQMENU.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'RECOVER_MSG.TP' is saved         
13-AUG-21 11:24 :54
========================================
FILE 'RC1R.DT' is saved                
13-AUG-21 11:24 :54
========================================
FILE 'PSRBWLD.CM' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'PROMPTYN.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'PROMPTOK.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'PRG_SELECT.TP' is saved          
13-AUG-21 11:24 :54
========================================
FILE 'PRGSEL_MSG.TP' is saved          
13-AUG-21 11:24 :54
========================================
FILE 'POSREG.VR' is saved              
13-AUG-21 11:24 :54
========================================
FILE 'PNS0004.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'PNS0002.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'PNS0001.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'PLCFMOV.VR' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'PLCFCAL.VR' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'PAYLOAD.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'P10037756NEW.TP' is saved        
13-AUG-21 11:24 :54
========================================
FILE 'P10037756.TP' is saved           
13-AUG-21 11:24 :54
========================================
FILE 'OVERRIDE.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'ORIENT_MSG.TP' is saved          
13-AUG-21 11:24 :54
========================================
FILE 'ORDERFIL.DAT' is saved           
13-AUG-21 11:24 :54
========================================
FILE 'OPERMENU.TP' is saved            
13-AUG-21 11:24 :54
========================================
FILE 'OPEN_TOOL_2_A.TP' is saved       
13-AUG-21 11:24 :54
========================================
FILE 'OPEN_T2.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'OPEN_T1.TP' is saved             
13-AUG-21 11:24 :54
========================================
FILE 'OP20_2_ORIENT2.TP' is saved      
13-AUG-21 11:24 :54
========================================
FILE 'OP20_2_ORIENT1.TP' is saved      
13-AUG-21 11:24 :54
========================================
FILE 'OP20_2_OPEN_CHUCK.TP' is saved   
13-AUG-21 11:24 :54
========================================
FILE 'OP20_2_CLS_CHUCK.TP' is saved    
13-AUG-21 11:24 :54
========================================
FILE 'OP20_1_ORIENT2.TP' is saved      
13-AUG-21 11:24 :54
========================================
FILE 'OP20_1_ORIENT1.TP' is saved      
13-AUG-21 11:24 :54
========================================
FILE 'OP20_1_OPEN_CHUCK.TP' is saved   
13-AUG-21 11:24 :54
========================================
FILE 'OP20_1_CLS_CHUCK.TP' is saved    
13-AUG-21 11:24 :54
========================================
FILE 'OP10_2_ORIENT1.TP' is saved      
13-AUG-21 11:24 :54
========================================
FILE 'OP10_2_OPEN_CHUCK.TP' is saved   
13-AUG-21 11:24 :54
========================================
FILE 'OP10_2_CLS_CHUCK.TP' is saved    
13-AUG-21 11:24 :52
========================================
FILE 'OP10_1_ORIENT1.TP' is saved      
13-AUG-21 11:24 :52
========================================
FILE 'OP10_1_OPEN_CHUCK.TP' is saved   
13-AUG-21 11:24 :52
========================================
FILE 'OP10_1_CLS_CHUCK.TP' is saved    
13-AUG-21 11:24 :52
========================================
FILE 'NUMREG.VR' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'NOTIFY.DG' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'MWAITSTRT.TP' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'MWAITEND.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'MSYNC.TP' is saved               
13-AUG-21 11:24 :52
========================================
FILE 'MREQZONE.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'MRELZONE.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'MOVE_HOME.TP' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'MON_T2ALM.TP' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'MON_T2.TP' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'MON_T1ALM.TP' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'MON_T1.TP' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP20_2ALM.TP' is saved       
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP20_2.TP' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP20_1ALM.TP' is saved       
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP20_1.TP' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP10_2ALM.TP' is saved       
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP10_2.TP' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP10_1ALM.TP' is saved       
13-AUG-21 11:24 :52
========================================
FILE 'MON_OP10_1.TP' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'MIXLOGIC.SV' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'MHMENU.VR' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'MGETZONE.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'MENUTEST.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'MENU501.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'MENU401.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'MENU301.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'MENU201.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'MENU101.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'MEMCHECK.DG' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'MAINT_MSG.TP' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'MACH_MSG.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'LOGBOOK.LS' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'LISTMENU.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'IRC_STLABEL.VR' is saved         
13-AUG-21 11:24 :52
========================================
FILE 'IRC_STATUS.VR' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'IRC_MSG.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'IRC_COUNTER.VR' is saved         
13-AUG-21 11:24 :52
========================================
FILE 'IPRNGSHO.VR' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'IPRNGSET.VR' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'IPKDMP.ZIP' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'IOSTATUS.CM' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'IAHAND.SV' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'HTTPKCL.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'HTCOLREC.VR' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'HOME_MSG.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'HIST.LS' is saved                
13-AUG-21 11:24 :52
========================================
FILE 'HAPTIC.SV' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'GRIP_SETUP.TP' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'GRIP_MSG.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'GRIP_CHK.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'GETDATA.TP' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'GEMDATA.VR' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'FTPLOG.DG' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'FRAMEVAR.VR' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'EXT1A1.DT' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'EXT1.DT' is saved                
13-AUG-21 11:24 :52
========================================
FILE 'EXITFZONE.TP' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'EXITALL.TP' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'ETHERNET.DG' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'ESTP_ADJ.VR' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'ERRSYS.LS' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'ERRPWD.LS' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'ERRMOT.LS' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'ERRHIST.LS' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'ERREXT.LS' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'ERRCURR.LS' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'ERRCOMM.LS' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'ERRAPP.LS' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'ERRALL.LS' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'ERRACT.LS' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'ENTER2ZONE.TP' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'EMAIL.DG' is saved               
13-AUG-21 11:24 :52
========================================
FILE 'EIPLOG.DG' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'DSP_WEBP.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DOBWDEXITG1.VR' is saved         
13-AUG-21 11:24 :52
========================================
FILE 'DOBWDEXIT.VR' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'DIOCFGSV.IO' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DH_EXT.XML' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'DF_MOTN0.DF' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DF_LOGI6.DF' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DF_LOGI5.DF' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DF_LOGI4.DF' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DF_LOGI3.DF' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DF_LOGI2.DF' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DF_LOGI1.DF' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DCSVRFY.DG' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'DCSPOS.SV' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'DCSDIFF.DG' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'DCSCHGD3.DG' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DCSCHGD2.DG' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'DCSCHGD1.DG' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'CONVEYOR_MSG.TP' is saved        
13-AUG-21 11:24 :52
========================================
FILE 'CONSLOG.DG' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'COMSET.VR' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'CMM_CLS_CHUCK.TP' is saved       
13-AUG-21 11:24 :52
========================================
FILE 'CLOSE_T2.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'CLOSE_T1.TP' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'CHUCK_MSG.TP' is saved           
13-AUG-21 11:24 :52
========================================
FILE 'CELLIO.SV' is saved              
13-AUG-21 11:24 :52
========================================
FILE 'BGLOGIC_MSG.TP' is saved         
13-AUG-21 11:24 :52
========================================
FILE 'BGLOGIC.TP' is saved             
13-AUG-21 11:24 :52
========================================
FILE 'BACKDATE.DT' is saved            
13-AUG-21 11:24 :52
========================================
FILE 'AZPAYLOAD.DAT' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'AZPAYLOAD.BIN' is saved          
13-AUG-21 11:24 :52
========================================
FILE 'AZP10037756.DAT' is saved        
13-AUG-21 11:24 :52
========================================
FILE 'AZP10037756.BIN' is saved        
13-AUG-21 11:24 :52
========================================
FILE 'AZP10005662.DAT' is saved        
13-AUG-21 11:24 :50
========================================
FILE 'AZP10005662.BIN' is saved        
13-AUG-21 11:24 :50
========================================
FILE 'AZOVERRIDE.DAT' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZOVERRIDE.BIN' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZOPEN_T2.DAT' is saved          
13-AUG-21 11:24 :50
========================================
FILE 'AZOPEN_T2.BIN' is saved          
13-AUG-21 11:24 :50
========================================
FILE 'AZOPEN_T1.DAT' is saved          
13-AUG-21 11:24 :50
========================================
FILE 'AZOPEN_T1.BIN' is saved          
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_2_OPEN_CHUCK.DAT' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_2_OPEN_CHUCK.BIN' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_2_CLS_CHUCK.DAT' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_2_CLS_CHUCK.BIN' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_1_OPEN_CHUCK.DAT' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_1_OPEN_CHUCK.BIN' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_1_CLS_CHUCK.DAT' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZOP20_1_CLS_CHUCK.BIN' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_2_OPEN_CHUCK.DAT' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_2_OPEN_CHUCK.BIN' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_2_CLS_CHUCK.DAT' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_2_CLS_CHUCK.BIN' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_1_OPEN_CHUCK.DAT' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_1_OPEN_CHUCK.BIN' is saved
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_1_CLS_CHUCK.DAT' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZOP10_1_CLS_CHUCK.BIN' is saved 
13-AUG-21 11:24 :50
========================================
FILE 'AZMACH_MSG.DAT' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZMACH_MSG.BIN' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZHOME_MSG.DAT' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZHOME_MSG.BIN' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZGRIP_MSG.DAT' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZGRIP_MSG.BIN' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZGRIP_CHK.DAT' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZGRIP_CHK.BIN' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZCONVEYOR_MSG.DAT' is saved     
13-AUG-21 11:24 :50
========================================
FILE 'AZCONVEYOR_MSG.BIN' is saved     
13-AUG-21 11:24 :50
========================================
FILE 'AZCMM_CLS_CHUCK.DAT' is saved    
13-AUG-21 11:24 :50
========================================
FILE 'AZCMM_CLS_CHUCK.BIN' is saved    
13-AUG-21 11:24 :50
========================================
FILE 'AZCLOSE_T2.DAT' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZCLOSE_T2.BIN' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZCLOSE_T1.DAT' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZCLOSE_T1.BIN' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AZCHUCK_MSG.DAT' is saved        
13-AUG-21 11:24 :50
========================================
FILE 'AZCHUCK_MSG.BIN' is saved        
13-AUG-21 11:24 :50
========================================
FILE 'AZBGLOGIC_MSG.DAT' is saved      
13-AUG-21 11:24 :50
========================================
FILE 'AZBGLOGIC_MSG.BIN' is saved      
13-AUG-21 11:24 :50
========================================
FILE 'ATERRJOB.VR' is saved            
13-AUG-21 11:24 :50
========================================
FILE 'AIRBLOW20_2.TP' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AIRBLOW20_1.TP' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AIRBLOW10_2.TP' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'AIRBLOW10_1.TP' is saved         
13-AUG-21 11:24 :50
========================================
FILE 'ABORTIT.TP' is saved             
13-AUG-21 11:24 :50
========================================
FILE 'AAVMMAIN.VR' is saved            
13-AUG-21 11:24 :50
========================================
FILE '-BCKEDT-.TP' is saved            
13-AUG-21 11:24 :50
========================================
FILE '-BCKED9-.TP' is saved            
13-AUG-21 11:24 :50
========================================
FILE '-BCKED8-.TP' is saved            
13-AUG-21 11:24 :50
========================================
FILE '-BCKED2-.TP' is saved            
13-AUG-21 11:24 :50
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
13-AUG-21 11:24 :50
========================================
Menu changed 'PNS0001'                 
13-AUG-21 11:02 :28
========================================
EDIT is pressed                        
13-AUG-21 11:02 :28
========================================
Menu changed 'System/Config'           
13-AUG-21 11:01 :32
========================================
'Config' is selected in 'SYSTEM' MENU f
lyout                                  
13-AUG-21 11:01 :32
========================================
ENTER is pressed                       
13-AUG-21 11:01 :32
========================================
ENTER is pressed                       
13-AUG-21 11:01 :30
========================================
PREV is pressed                        
13-AUG-21 11:01 :30
========================================
Menu changed 'I/O Cell Outputs'        
13-AUG-21 11:01 :24
========================================
FILE 'FRS:\CMIO.VR' is loaded          
13-AUG-21 11:01 :24
========================================
UF6 is pressed                         
13-AUG-21 11:01 :24
========================================
Focus changed to 'UTILITIES Hints'     
13-AUG-21 11:01 :22
========================================
Menu changed 'UTILITIES Hints'         
13-AUG-21 11:01 :22
========================================
Focus changed to 'UTILITIES Hints'     
13-AUG-21 11:01 :22
========================================
PREV is pressed                        
13-AUG-21 11:01 :20
========================================
PREV is pressed                        
13-AUG-21 11:01 :20
========================================
PREV is pressed                        
13-AUG-21 11:01 :20
========================================
MASI-019 Err in OSSND                  
                                       
                                       
STOP.G                        00100110 
13-AUG-21 11:01 :20
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 11:01 :20
========================================
SHIFT,RESET is pressed                 
13-AUG-21 11:01 :20
========================================
MASI-019 Err in OSSND                  
                                       
                                       
STOP.G                        00100110 
13-AUG-21 11:01 :20
========================================
MASI-019 Err in OSSND                  
                                       
                                       
STOP.G                        00100110 
13-AUG-21 11:01 :20
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 11:01 :20
========================================
SHIFT,RESET is pressed                 
13-AUG-21 11:01 :20
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 11:01 :14
========================================
RESET is pressed                       
13-AUG-21 11:01 :14
========================================
F1(| TYPE |) is pressed                
13-AUG-21 11:01 :12
--Screen image--------------------------
                                                                                
P10037756NEW      LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
I/O\Cell\Outputs\\\\\\\\\\\\\\       0 0                                        
                                   1/10                                         
    OUTPUT SIGNAL     TYPE #  SIM STATUS                                        
  1 Input Simulated   DO[   0] U   ***                                          
  2 Output Simulated  DO[   0] U   ***                                          
  3 OVERRIDE = 100    DO[   0] U   ***                                          
  4 In cycle          DO[   0] U   ***                                          
  5 Prog Aborted      DO[   0] U   ***                                          
  6 Tryout Status     DO[   0] U   ***                                          
  7 Heartbeat         DO[  34] U   OFF                                          
  8 MH Fault          DO[   0] U   ***                                          
  9 MH Alert          DO[   0] U   ***                                          
 10 Robot motion G1   DO[   0] U   ***                                          
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
| TYPE | CONFIG  IN/OUT SIM     UNSIM  >                                        
========================================
F1([ TYPE ]) is pressed                
13-AUG-21 11:01 :10
--Screen image--------------------------
                                                                                
P10037756NEW      LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\L47%                   
I/O\Cell\Outputs\\\\\\\\\\\\\\       0 0                                        
                                   1/10                                         
    OUTPUT SIGNAL     TYPE #  SIM STATUS                                        
  1 Input Simulated   DO[   0] U   ***                                          
  2 Output Simulated  DO[   0] U   ***                                          
  3 OVERRIDE = 100    DO[   0] U   ***                                          
  4 In cycle          DO[   0] U   ***                                          
  5 Prog Aborted      DO[   0] U   ***                                          
  6 Tryout Status     DO[   0] U   ***                                          
  7 Heartbeat         DO[  34] U   OFF                                          
  8 MH Fault          DO[   0] U   ***                                          
  9 MH Alert          DO[   0] U   ***                                          
 10 Robot motion G1   DO[   0] U   ***                                          
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
[ TYPE ] CONFIG  IN/OUT SIM     UNSIM  >                                        
========================================
Menu changed 'I/O Cell Outputs'        
13-AUG-21 11:01 :08
========================================
FILE 'FRS:\CMIO.VR' is loaded          
13-AUG-21 11:01 :08
========================================
UF6 is pressed                         
13-AUG-21 11:01 :08
========================================
Menu changed 'Select'                  
13-AUG-21 11:01 :06
========================================
SELECT is pressed                      
13-AUG-21 11:01 :06
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 11:01 :06
========================================
RESET is pressed                       
13-AUG-21 11:01 :04
========================================
PREV is pressed                        
13-AUG-21 11:00 :44
========================================
PREV is pressed                        
13-AUG-21 11:00 :04
========================================
Menu changed 'UPDATE_REF'              
13-AUG-21 10:58 :18
========================================
ENTER is pressed                       
13-AUG-21 10:58 :18
========================================
Menu changed 'Select'                  
13-AUG-21 10:58 :10
========================================
SELECT is pressed                      
13-AUG-21 10:58 :10
========================================
Menu changed 'BGLOGIC'                 
13-AUG-21 10:57 :36
========================================
Override 10%                           
13-AUG-21 10:57 :36
========================================
ENTER is pressed                       
13-AUG-21 10:57 :36
========================================
Menu changed 'Select'                  
13-AUG-21 10:57 :30
========================================
SELECT is pressed                      
13-AUG-21 10:57 :30
========================================
Menu changed 'Background logic'        
13-AUG-21 10:57 :24
========================================
'BG Logic' is selected in 'SETUP' MENU 
flyout                                 
13-AUG-21 10:57 :24
========================================
ENTER is pressed                       
13-AUG-21 10:57 :24
========================================
Menu changed 'PNS0001'                 
13-AUG-21 10:55 :40
========================================
ENTER is pressed                       
13-AUG-21 10:55 :40
========================================
Menu changed 'PNS0001'                 
13-AUG-21 10:55 :16
========================================
ENTER is pressed                       
13-AUG-21 10:55 :16
========================================
Menu changed 'Select'                  
13-AUG-21 10:55 :10
========================================
SELECT is pressed                      
13-AUG-21 10:55 :10
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 10:55 :08
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 10:55 :08
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
13-AUG-21 10:55 :08
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
13-AUG-21 10:55 :08
========================================
SYST-045 TP enabled in AUTO mode       
                                       
                                       
STOP.G                        00100110 
13-AUG-21 10:55 :08
========================================
Focus changed to 'iPendant only screen'
13-AUG-21 10:55 :08
========================================
Menu changed 'iPendant only screen'    
13-AUG-21 10:55 :08
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 10:54 :54
========================================
FILE 'WAIT4SYNC.TP' is saved           
13-AUG-21 10:54 :54
========================================
FILE 'USERPAGE.TP' is saved            
13-AUG-21 10:54 :54
========================================
FILE 'USERCLR.TP' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'UPDTLOG.LS' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'UPDATE_REF.TP' is saved          
13-AUG-21 10:54 :54
========================================
FILE 'UPDATES.DAT' is saved            
13-AUG-21 10:54 :54
========================================
FILE 'TS1.TP' is saved                 
13-AUG-21 10:54 :54
========================================
FILE 'TPEINS.XML' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'TPACCN.DG' is saved              
13-AUG-21 10:54 :54
========================================
FILE 'TOOL2_OPEN.TP' is saved          
13-AUG-21 10:54 :54
========================================
FILE 'TOOL2_CLOSE.TP' is saved         
13-AUG-21 10:54 :54
========================================
FILE 'TOOL1_OPEN.TP' is saved          
13-AUG-21 10:54 :54
========================================
FILE 'TOOL1_CLOSE.TP' is saved         
13-AUG-21 10:54 :54
========================================
FILE 'SYSVARS.SV' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'SYSUIF.SV' is saved              
13-AUG-21 10:54 :54
========================================
FILE 'SYSSERVO.SV' is saved            
13-AUG-21 10:54 :54
========================================
FILE 'SYSPASS.SV' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'SYSMAST.SV' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'SYSMACRO.SV' is saved            
13-AUG-21 10:54 :54
========================================
FILE 'SYSHOST.SV' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'SYSFSAC.SV' is saved             
13-AUG-21 10:54 :54
========================================
FILE 'SYSFRAME.SV' is saved            
13-AUG-21 10:54 :54
========================================
FILE 'SYSEIP.SV' is saved              
13-AUG-21 10:54 :54
========================================
FILE 'SYSEGD.SV' is saved              
13-AUG-21 10:54 :54
========================================
FILE 'SYNC2WAIT.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'SWIUPDT.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'SWIAUTO.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'SWIAUTO.PC' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'SV_ADJST.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'SUMMARY.DG' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'STRREG.VR' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'STATPAGE.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'SHIP.TP' is saved                
13-AUG-21 10:54 :52
========================================
FILE 'SHADOW.DG' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'SENDSYSV.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'SENDEVNT.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'SENDDATA.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK2_WASHOP20.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK2_WASHOP10.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK2_OP20.TP' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK2_OP10.TP' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK1_WASHOP20.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK1_WASHOP10.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK1_OP20.TP' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'RPS_OK1_OP10.TP' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'ROSIPCFG.XML' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'RLSVRLUT.VR' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'RLSVEXGEN6.VR' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'RLSETMTR.VR' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'RIPESTAT.DG' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'RIPELOG.DG' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'REQMENU.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'RECOVER_MSG.TP' is saved         
13-AUG-21 10:54 :52
========================================
FILE 'RC1R.DT' is saved                
13-AUG-21 10:54 :52
========================================
FILE 'PSRBWLD.CM' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'PROMPTYN.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'PROMPTOK.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'PRG_SELECT.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'PRGSEL_MSG.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'POSREG.VR' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'PNS0004.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'PNS0002.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'PNS0001.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'PLCFMOV.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'PLCFCAL.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'PAYLOAD.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'P10037756NEW.TP' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'P10037756.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'OVERRIDE.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'ORIENT_MSG.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'ORDERFIL.DAT' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'OPERMENU.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'OPEN_TOOL_2_A.TP' is saved       
13-AUG-21 10:54 :52
========================================
FILE 'OPEN_T2.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'OPEN_T1.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'OP20_2_ORIENT2.TP' is saved      
13-AUG-21 10:54 :52
========================================
FILE 'OP20_2_ORIENT1.TP' is saved      
13-AUG-21 10:54 :52
========================================
FILE 'OP20_2_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :52
========================================
FILE 'OP20_2_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'OP20_1_ORIENT2.TP' is saved      
13-AUG-21 10:54 :52
========================================
FILE 'OP20_1_ORIENT1.TP' is saved      
13-AUG-21 10:54 :52
========================================
FILE 'OP20_1_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :52
========================================
FILE 'OP20_1_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'OP10_2_ORIENT1.TP' is saved      
13-AUG-21 10:54 :52
========================================
FILE 'OP10_2_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :52
========================================
FILE 'OP10_2_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'OP10_1_ORIENT1.TP' is saved      
13-AUG-21 10:54 :52
========================================
FILE 'OP10_1_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :52
========================================
FILE 'OP10_1_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :52
========================================
FILE 'NUMREG.VR' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'NOTIFY.DG' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'MWAITSTRT.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'MWAITEND.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'MSYNC.TP' is saved               
13-AUG-21 10:54 :52
========================================
FILE 'MREQZONE.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'MRELZONE.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'MOVE_HOME.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'MON_T2ALM.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'MON_T2.TP' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'MON_T1ALM.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'MON_T1.TP' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP20_2ALM.TP' is saved       
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP20_2.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP20_1ALM.TP' is saved       
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP20_1.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP10_2ALM.TP' is saved       
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP10_2.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP10_1ALM.TP' is saved       
13-AUG-21 10:54 :52
========================================
FILE 'MON_OP10_1.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'MIXLOGIC.SV' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'MHMENU.VR' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'MGETZONE.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'MENUTEST.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'MENU501.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'MENU401.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'MENU301.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'MENU201.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'MENU101.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'MEMCHECK.DG' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'MAINT_MSG.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'MACH_MSG.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'LOGBOOK.LS' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'LISTMENU.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'IRC_STLABEL.VR' is saved         
13-AUG-21 10:54 :52
========================================
FILE 'IRC_STATUS.VR' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'IRC_MSG.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'IRC_COUNTER.VR' is saved         
13-AUG-21 10:54 :52
========================================
FILE 'IPRNGSHO.VR' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'IPRNGSET.VR' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'IPKDMP.ZIP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'IOSTATUS.CM' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'IAHAND.SV' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'HTTPKCL.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'HTCOLREC.VR' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'HOME_MSG.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'HIST.LS' is saved                
13-AUG-21 10:54 :52
========================================
FILE 'HAPTIC.SV' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'GRIP_SETUP.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'GRIP_MSG.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'GRIP_CHK.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'GETDATA.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'GEMDATA.VR' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'FTPLOG.DG' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'FRAMEVAR.VR' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'EXT1A1.DT' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'EXT1.DT' is saved                
13-AUG-21 10:54 :52
========================================
FILE 'EXITFZONE.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'EXITALL.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'ETHERNET.DG' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'ESTP_ADJ.VR' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'ERRSYS.LS' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'ERRPWD.LS' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'ERRMOT.LS' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'ERRHIST.LS' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'ERREXT.LS' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'ERRCURR.LS' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'ERRCOMM.LS' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'ERRAPP.LS' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'ERRALL.LS' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'ERRACT.LS' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'ENTER2ZONE.TP' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'EMAIL.DG' is saved               
13-AUG-21 10:54 :52
========================================
FILE 'EIPLOG.DG' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'DSP_WEBP.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DOBWDEXITG1.VR' is saved         
13-AUG-21 10:54 :52
========================================
FILE 'DOBWDEXIT.VR' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'DIOCFGSV.IO' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DH_EXT.XML' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'DF_MOTN0.DF' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DF_LOGI6.DF' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DF_LOGI5.DF' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DF_LOGI4.DF' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DF_LOGI3.DF' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DF_LOGI2.DF' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DF_LOGI1.DF' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DCSVRFY.DG' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'DCSPOS.SV' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'DCSDIFF.DG' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'DCSCHGD3.DG' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DCSCHGD2.DG' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'DCSCHGD1.DG' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'CONVEYOR_MSG.TP' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'CONSLOG.DG' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'COMSET.VR' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'CMM_CLS_CHUCK.TP' is saved       
13-AUG-21 10:54 :52
========================================
FILE 'CLOSE_T2.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'CLOSE_T1.TP' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'CHUCK_MSG.TP' is saved           
13-AUG-21 10:54 :52
========================================
FILE 'CELLIO.SV' is saved              
13-AUG-21 10:54 :52
========================================
FILE 'BGLOGIC_MSG.TP' is saved         
13-AUG-21 10:54 :52
========================================
FILE 'BGLOGIC.TP' is saved             
13-AUG-21 10:54 :52
========================================
FILE 'BACKDATE.DT' is saved            
13-AUG-21 10:54 :52
========================================
FILE 'AZPAYLOAD.DAT' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'AZPAYLOAD.BIN' is saved          
13-AUG-21 10:54 :52
========================================
FILE 'AZP10037756.DAT' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'AZP10037756.BIN' is saved        
13-AUG-21 10:54 :52
========================================
FILE 'AZP10005662.DAT' is saved        
13-AUG-21 10:54 :50
========================================
FILE 'AZP10005662.BIN' is saved        
13-AUG-21 10:54 :50
========================================
FILE 'AZOVERRIDE.DAT' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZOVERRIDE.BIN' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZOPEN_T2.DAT' is saved          
13-AUG-21 10:54 :50
========================================
FILE 'AZOPEN_T2.BIN' is saved          
13-AUG-21 10:54 :50
========================================
FILE 'AZOPEN_T1.DAT' is saved          
13-AUG-21 10:54 :50
========================================
FILE 'AZOPEN_T1.BIN' is saved          
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_2_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_2_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_2_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_2_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_1_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_1_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_1_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZOP20_1_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_2_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_2_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_2_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_2_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_1_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_1_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_1_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZOP10_1_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :50
========================================
FILE 'AZMACH_MSG.DAT' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZMACH_MSG.BIN' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZHOME_MSG.DAT' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZHOME_MSG.BIN' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZGRIP_MSG.DAT' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZGRIP_MSG.BIN' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZGRIP_CHK.DAT' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZGRIP_CHK.BIN' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZCONVEYOR_MSG.DAT' is saved     
13-AUG-21 10:54 :50
========================================
FILE 'AZCONVEYOR_MSG.BIN' is saved     
13-AUG-21 10:54 :50
========================================
FILE 'AZCMM_CLS_CHUCK.DAT' is saved    
13-AUG-21 10:54 :50
========================================
FILE 'AZCMM_CLS_CHUCK.BIN' is saved    
13-AUG-21 10:54 :50
========================================
FILE 'AZCLOSE_T2.DAT' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZCLOSE_T2.BIN' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZCLOSE_T1.DAT' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZCLOSE_T1.BIN' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AZCHUCK_MSG.DAT' is saved        
13-AUG-21 10:54 :50
========================================
FILE 'AZCHUCK_MSG.BIN' is saved        
13-AUG-21 10:54 :50
========================================
FILE 'AZBGLOGIC_MSG.DAT' is saved      
13-AUG-21 10:54 :50
========================================
FILE 'AZBGLOGIC_MSG.BIN' is saved      
13-AUG-21 10:54 :50
========================================
FILE 'ATERRJOB.VR' is saved            
13-AUG-21 10:54 :50
========================================
FILE 'AIRBLOW20_2.TP' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AIRBLOW20_1.TP' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AIRBLOW10_2.TP' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'AIRBLOW10_1.TP' is saved         
13-AUG-21 10:54 :50
========================================
FILE 'ABORTIT.TP' is saved             
13-AUG-21 10:54 :50
========================================
FILE 'AAVMMAIN.VR' is saved            
13-AUG-21 10:54 :50
========================================
FILE '-BCKEDT-.TP' is saved            
13-AUG-21 10:54 :50
========================================
FILE '-BCKED9-.TP' is saved            
13-AUG-21 10:54 :50
========================================
FILE '-BCKED8-.TP' is saved            
13-AUG-21 10:54 :50
========================================
FILE '-BCKED2-.TP' is saved            
13-AUG-21 10:54 :50
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
13-AUG-21 10:54 :50
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 10:54 :48
========================================
FILE 'WAIT4SYNC.TP' is saved           
13-AUG-21 10:54 :48
========================================
FILE 'USERPAGE.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'USERCLR.TP' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'UPDTLOG.LS' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'UPDATE_REF.TP' is saved          
13-AUG-21 10:54 :48
========================================
FILE 'UPDATES.DAT' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'TS1.TP' is saved                 
13-AUG-21 10:54 :48
========================================
FILE 'TPEINS.XML' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'TPACCN.DG' is saved              
13-AUG-21 10:54 :48
========================================
FILE 'TOOL2_OPEN.TP' is saved          
13-AUG-21 10:54 :48
========================================
FILE 'TOOL2_CLOSE.TP' is saved         
13-AUG-21 10:54 :48
========================================
FILE 'TOOL1_OPEN.TP' is saved          
13-AUG-21 10:54 :48
========================================
FILE 'TOOL1_CLOSE.TP' is saved         
13-AUG-21 10:54 :48
========================================
FILE 'SYSVARS.SV' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SYSUIF.SV' is saved              
13-AUG-21 10:54 :48
========================================
FILE 'SYSSERVO.SV' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'SYSPASS.SV' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SYSMAST.SV' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SYSMACRO.SV' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'SYSHOST.SV' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SYSFSAC.SV' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SYSFRAME.SV' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'SYSEIP.SV' is saved              
13-AUG-21 10:54 :48
========================================
FILE 'SYSEGD.SV' is saved              
13-AUG-21 10:54 :48
========================================
FILE 'SYNC2WAIT.TP' is saved           
13-AUG-21 10:54 :48
========================================
FILE 'SWIUPDT.VR' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SWIAUTO.VR' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SWIAUTO.PC' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'SV_ADJST.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'SUMMARY.DG' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'STRREG.VR' is saved              
13-AUG-21 10:54 :48
========================================
FILE 'STATPAGE.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'SHIP.TP' is saved                
13-AUG-21 10:54 :48
========================================
FILE 'SHADOW.DG' is saved              
13-AUG-21 10:54 :48
========================================
FILE 'SENDSYSV.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'SENDEVNT.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'SENDDATA.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK2_WASHOP20.TP' is saved    
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK2_WASHOP10.TP' is saved    
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK2_OP20.TP' is saved        
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK2_OP10.TP' is saved        
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK1_WASHOP20.TP' is saved    
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK1_WASHOP10.TP' is saved    
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK1_OP20.TP' is saved        
13-AUG-21 10:54 :48
========================================
FILE 'RPS_OK1_OP10.TP' is saved        
13-AUG-21 10:54 :48
========================================
FILE 'ROSIPCFG.XML' is saved           
13-AUG-21 10:54 :48
========================================
FILE 'RLSVRLUT.VR' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'RLSVEXGEN6.VR' is saved          
13-AUG-21 10:54 :48
========================================
FILE 'RLSETMTR.VR' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'RIPESTAT.DG' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'RIPELOG.DG' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'REQMENU.TP' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'RECOVER_MSG.TP' is saved         
13-AUG-21 10:54 :48
========================================
FILE 'RC1R.DT' is saved                
13-AUG-21 10:54 :48
========================================
FILE 'PSRBWLD.CM' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'PROMPTYN.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'PROMPTOK.TP' is saved            
13-AUG-21 10:54 :48
========================================
FILE 'PRG_SELECT.TP' is saved          
13-AUG-21 10:54 :48
========================================
FILE 'PRGSEL_MSG.TP' is saved          
13-AUG-21 10:54 :48
========================================
FILE 'POSREG.VR' is saved              
13-AUG-21 10:54 :48
========================================
FILE 'PNS0004.TP' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'PNS0002.TP' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'PNS0001.TP' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'PLCFMOV.VR' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'PLCFCAL.VR' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'PAYLOAD.TP' is saved             
13-AUG-21 10:54 :48
========================================
FILE 'P10037756NEW.TP' is saved        
13-AUG-21 10:54 :48
========================================
FILE 'P10037756.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'OVERRIDE.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'ORIENT_MSG.TP' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'ORDERFIL.DAT' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'OPERMENU.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'OPEN_TOOL_2_A.TP' is saved       
13-AUG-21 10:54 :46
========================================
FILE 'OPEN_T2.TP' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'OPEN_T1.TP' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'OP20_2_ORIENT2.TP' is saved      
13-AUG-21 10:54 :46
========================================
FILE 'OP20_2_ORIENT1.TP' is saved      
13-AUG-21 10:54 :46
========================================
FILE 'OP20_2_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :46
========================================
FILE 'OP20_2_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :46
========================================
FILE 'OP20_1_ORIENT2.TP' is saved      
13-AUG-21 10:54 :46
========================================
FILE 'OP20_1_ORIENT1.TP' is saved      
13-AUG-21 10:54 :46
========================================
FILE 'OP20_1_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :46
========================================
FILE 'OP20_1_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :46
========================================
FILE 'OP10_2_ORIENT1.TP' is saved      
13-AUG-21 10:54 :46
========================================
FILE 'OP10_2_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :46
========================================
FILE 'OP10_2_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :46
========================================
FILE 'OP10_1_ORIENT1.TP' is saved      
13-AUG-21 10:54 :46
========================================
FILE 'OP10_1_OPEN_CHUCK.TP' is saved   
13-AUG-21 10:54 :46
========================================
FILE 'OP10_1_CLS_CHUCK.TP' is saved    
13-AUG-21 10:54 :46
========================================
FILE 'NUMREG.VR' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'NOTIFY.DG' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'MWAITSTRT.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'MWAITEND.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'MSYNC.TP' is saved               
13-AUG-21 10:54 :46
========================================
FILE 'MREQZONE.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'MRELZONE.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'MOVE_HOME.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'MON_T2ALM.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'MON_T2.TP' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'MON_T1ALM.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'MON_T1.TP' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP20_2ALM.TP' is saved       
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP20_2.TP' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP20_1ALM.TP' is saved       
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP20_1.TP' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP10_2ALM.TP' is saved       
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP10_2.TP' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP10_1ALM.TP' is saved       
13-AUG-21 10:54 :46
========================================
FILE 'MON_OP10_1.TP' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'MIXLOGIC.SV' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'MHMENU.VR' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'MGETZONE.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'MENUTEST.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'MENU501.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'MENU401.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'MENU301.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'MENU201.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'MENU101.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'MEMCHECK.DG' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'MAINT_MSG.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'MACH_MSG.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'LOGBOOK.LS' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'LISTMENU.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'IRC_STLABEL.VR' is saved         
13-AUG-21 10:54 :46
========================================
FILE 'IRC_STATUS.VR' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'IRC_MSG.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'IRC_COUNTER.VR' is saved         
13-AUG-21 10:54 :46
========================================
FILE 'IPRNGSHO.VR' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'IPRNGSET.VR' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'IPKDMP.ZIP' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'IOSTATUS.CM' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'IAHAND.SV' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'HTTPKCL.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'HTCOLREC.VR' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'HOME_MSG.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'HIST.LS' is saved                
13-AUG-21 10:54 :46
========================================
FILE 'HAPTIC.SV' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'GRIP_SETUP.TP' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'GRIP_MSG.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'GRIP_CHK.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'GETDATA.TP' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'GEMDATA.VR' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'FTPLOG.DG' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'FRAMEVAR.VR' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'EXT1A1.DT' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'EXT1.DT' is saved                
13-AUG-21 10:54 :46
========================================
FILE 'EXITFZONE.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'EXITALL.TP' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'ETHERNET.DG' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'ESTP_ADJ.VR' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'ERRSYS.LS' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'ERRPWD.LS' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'ERRMOT.LS' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'ERRHIST.LS' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'ERREXT.LS' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'ERRCURR.LS' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'ERRCOMM.LS' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'ERRAPP.LS' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'ERRALL.LS' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'ERRACT.LS' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'ENTER2ZONE.TP' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'EMAIL.DG' is saved               
13-AUG-21 10:54 :46
========================================
FILE 'EIPLOG.DG' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'DSP_WEBP.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DOBWDEXITG1.VR' is saved         
13-AUG-21 10:54 :46
========================================
FILE 'DOBWDEXIT.VR' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'DIOCFGSV.IO' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DH_EXT.XML' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'DF_MOTN0.DF' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DF_LOGI6.DF' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DF_LOGI5.DF' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DF_LOGI4.DF' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DF_LOGI3.DF' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DF_LOGI2.DF' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DF_LOGI1.DF' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DCSVRFY.DG' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'DCSPOS.SV' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'DCSDIFF.DG' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'DCSCHGD3.DG' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DCSCHGD2.DG' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'DCSCHGD1.DG' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'CONVEYOR_MSG.TP' is saved        
13-AUG-21 10:54 :46
========================================
FILE 'CONSLOG.DG' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'COMSET.VR' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'CMM_CLS_CHUCK.TP' is saved       
13-AUG-21 10:54 :46
========================================
FILE 'CLOSE_T2.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'CLOSE_T1.TP' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'CHUCK_MSG.TP' is saved           
13-AUG-21 10:54 :46
========================================
FILE 'CELLIO.SV' is saved              
13-AUG-21 10:54 :46
========================================
FILE 'BGLOGIC_MSG.TP' is saved         
13-AUG-21 10:54 :46
========================================
FILE 'BGLOGIC.TP' is saved             
13-AUG-21 10:54 :46
========================================
FILE 'BACKDATE.DT' is saved            
13-AUG-21 10:54 :46
========================================
FILE 'AZPAYLOAD.DAT' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'AZPAYLOAD.BIN' is saved          
13-AUG-21 10:54 :46
========================================
FILE 'AZP10037756.DAT' is saved        
13-AUG-21 10:54 :46
========================================
FILE 'AZP10037756.BIN' is saved        
13-AUG-21 10:54 :46
========================================
FILE 'AZP10005662.DAT' is saved        
13-AUG-21 10:54 :46
========================================
FILE 'AZP10005662.BIN' is saved        
13-AUG-21 10:54 :46
========================================
FILE 'AZOVERRIDE.DAT' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZOVERRIDE.BIN' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZOPEN_T2.DAT' is saved          
13-AUG-21 10:54 :44
========================================
FILE 'AZOPEN_T2.BIN' is saved          
13-AUG-21 10:54 :44
========================================
FILE 'AZOPEN_T1.DAT' is saved          
13-AUG-21 10:54 :44
========================================
FILE 'AZOPEN_T1.BIN' is saved          
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_2_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_2_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_2_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_2_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_1_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_1_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_1_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZOP20_1_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_2_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_2_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_2_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_2_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_1_OPEN_CHUCK.DAT' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_1_OPEN_CHUCK.BIN' is saved
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_1_CLS_CHUCK.DAT' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZOP10_1_CLS_CHUCK.BIN' is saved 
13-AUG-21 10:54 :44
========================================
FILE 'AZMACH_MSG.DAT' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZMACH_MSG.BIN' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZHOME_MSG.DAT' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZHOME_MSG.BIN' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZGRIP_MSG.DAT' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZGRIP_MSG.BIN' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZGRIP_CHK.DAT' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZGRIP_CHK.BIN' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZCONVEYOR_MSG.DAT' is saved     
13-AUG-21 10:54 :44
========================================
FILE 'AZCONVEYOR_MSG.BIN' is saved     
13-AUG-21 10:54 :44
========================================
FILE 'AZCMM_CLS_CHUCK.DAT' is saved    
13-AUG-21 10:54 :44
========================================
FILE 'AZCMM_CLS_CHUCK.BIN' is saved    
13-AUG-21 10:54 :44
========================================
FILE 'AZCLOSE_T2.DAT' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZCLOSE_T2.BIN' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZCLOSE_T1.DAT' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZCLOSE_T1.BIN' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AZCHUCK_MSG.DAT' is saved        
13-AUG-21 10:54 :44
========================================
FILE 'AZCHUCK_MSG.BIN' is saved        
13-AUG-21 10:54 :44
========================================
FILE 'AZBGLOGIC_MSG.DAT' is saved      
13-AUG-21 10:54 :44
========================================
FILE 'AZBGLOGIC_MSG.BIN' is saved      
13-AUG-21 10:54 :44
========================================
FILE 'ATERRJOB.VR' is saved            
13-AUG-21 10:54 :44
========================================
FILE 'AIRBLOW20_2.TP' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AIRBLOW20_1.TP' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AIRBLOW10_2.TP' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'AIRBLOW10_1.TP' is saved         
13-AUG-21 10:54 :44
========================================
FILE 'ABORTIT.TP' is saved             
13-AUG-21 10:54 :44
========================================
FILE 'AAVMMAIN.VR' is saved            
13-AUG-21 10:54 :44
========================================
FILE '-BCKEDT-.TP' is saved            
13-AUG-21 10:54 :44
========================================
FILE '-BCKED9-.TP' is saved            
13-AUG-21 10:54 :44
========================================
FILE '-BCKED8-.TP' is saved            
13-AUG-21 10:54 :44
========================================
FILE '-BCKED2-.TP' is saved            
13-AUG-21 10:54 :44
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
13-AUG-21 10:54 :44
========================================
Override 100%                          
13-AUG-21 10:54 :42
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 10:54 :42
========================================
Menu changed 'UTILITIES Hints'         
13-AUG-21 10:54 :38
========================================
Override 10%                           
13-AUG-21 10:54 :38
========================================
FILE 'MEMORY.DG' is saved              
13-AUG-21 10:54 :36
========================================
SYST-176 Software was updated          
                                       
                                       
PAUSE.G                       00100010 
13-AUG-21 10:54 :36
========================================
FILE 'ERRALL.LS' is saved              
13-AUG-21 10:54 :36
========================================
FILE 'FRS:\CMIO.VR' is loaded          
13-AUG-21 10:54 :36
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
13-AUG-21 10:54 :36
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-21 10:54 :36
========================================
SRVO-302 Set Hand broken to ENABLE     
                                       
                                       
SERVO                         00110110 
13-AUG-21 10:54 :36
========================================
Cold start                             
13-AUG-21 10:54 :30
========================================
'START (COLD)' is selected in FCTN     
13-AUG-21 10:54 :28
========================================
Menu changed 'S/W INSTALL'             
13-AUG-21 10:54 :26
========================================
'S/W INSTALL' is selected in MENU      
13-AUG-21 10:54 :26
========================================
Menu changed 'Tool Setup'              
13-AUG-21 10:54 :20
========================================
FILE 'MEMORY.DG' is saved              
13-AUG-21 10:54 :20
========================================
SYST-290 Cycle power to use new DCS par
ameter                                 
                                       
STOP.G                        00100110 
13-AUG-21 10:54 :20
========================================
FILE 'MED:\00\TEMP\DF_MOTN0.DF' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\DF_LOGI6.DF' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\DF_LOGI5.DF' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\DF_LOGI4.DF' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\DF_LOGI3.DF' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\DF_LOGI2.DF' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\DF_LOGI1.DF' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\TS1.TP' is loaded   
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\TOOL2_OPEN.TP' is lo
aded                                   
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\TOOL2_CLOSE.TP' is l
oaded                                  
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\TOOL1_OPEN.TP' is lo
aded                                   
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\TOOL1_CLOSE.TP' is l
oaded                                  
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\SV_ADJST.TP' is load
ed                                     
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\SHIP.TP' is loaded  
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\RECOVER_MSG.TP' is l
oaded                                  
13-AUG-21 10:54 :18
========================================
FILE 'MED:\00\TEMP\PRGSEL_MSG.TP' is lo
aded                                   
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\P10037756NEW.TP' is 
loaded                                 
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\ORIENT_MSG.TP' is lo
aded                                   
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\OPEN_TOOL_2_A.TP' is
 loaded                                
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MWAITSTRT.TP' is loa
ded                                    
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MWAITEND.TP' is load
ed                                     
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MSYNC.TP' is loaded 
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MREQZONE.TP' is load
ed                                     
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MRELZONE.TP' is load
ed                                     
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MOVE_HOME.TP' is loa
ded                                    
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MON_T2.TP' is loaded
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MON_T1.TP' is loaded
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MON_OP20_2.TP' is lo
aded                                   
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MON_OP20_1.TP' is lo
aded                                   
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MON_OP10_2.TP' is lo
aded                                   
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MON_OP10_1.TP' is lo
aded                                   
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MGETZONE.TP' is load
ed                                     
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MENUTEST.TP' is load
ed                                     
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MAINT_MSG.TP' is loa
ded                                    
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\MACH_MSG.TP' is load
ed                                     
13-AUG-21 10:54 :16
========================================
FILE 'MED:\00\TEMP\HOME_MSG.TP' is load
ed                                     
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\GRIP_MSG.TP' is load
ed                                     
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\DSP_WEBP.TP' is load
ed                                     
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\CONVEYOR_MSG.TP' is 
loaded                                 
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\CHUCK_MSG.TP' is loa
ded                                    
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\BGLOGIC_MSG.TP' is l
oaded                                  
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\-BCKEDT-.TP' is load
ed                                     
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\-BCKED9-.TP' is load
ed                                     
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\-BCKED8-.TP' is load
ed                                     
13-AUG-21 10:54 :14
========================================
FILE 'MED:\00\TEMP\-BCKED2-.TP' is load
ed                                     
13-AUG-21 10:54 :14
========================================
FILE 'AZPAYLOAD.DAT' is loaded         
13-AUG-21 10:54 :14
========================================
FILE 'AZP10037756.DAT' is loaded       
13-AUG-21 10:54 :14
========================================
FILE 'AZP10005662.DAT' is loaded       
13-AUG-21 10:54 :14
========================================
FILE 'AZOVERRIDE.DAT' is loaded        
13-AUG-21 10:54 :14
========================================
FILE 'AZOPEN_T2.DAT' is loaded         
13-AUG-21 10:54 :14
========================================
FILE 'AZOPEN_T1.DAT' is loaded         
13-AUG-21 10:54 :14
========================================
FILE 'AZOP20_2_OPEN_CHUCK.DAT' is loade
d                                      
13-AUG-21 10:54 :14
========================================
FILE 'AZOP20_2_CLS_CHUCK.DAT' is loaded
13-AUG-21 10:54 :14
========================================
FILE 'AZOP20_1_OPEN_CHUCK.DAT' is loade
d                                      
13-AUG-21 10:54 :14
========================================
FILE 'AZOP20_1_CLS_CHUCK.DAT' is loaded
13-AUG-21 10:54 :14
========================================
FILE 'AZOP10_2_OPEN_CHUCK.DAT' is loade
d                                      
13-AUG-21 10:54 :14
========================================
FILE 'AZOP10_2_CLS_CHUCK.DAT' is loaded
13-AUG-21 10:54 :14
========================================
FILE 'AZOP10_1_OPEN_CHUCK.DAT' is loade
d                                      
13-AUG-21 10:54 :14
========================================
FILE 'AZOP10_1_CLS_CHUCK.DAT' is loaded
13-AUG-21 10:54 :14
========================================
FILE 'AZMACH_MSG.DAT' is loaded        
13-AUG-21 10:54 :14
========================================
FILE 'AZHOME_MSG.DAT' is loaded        
13-AUG-21 10:54 :14
========================================
FILE 'AZGRIP_MSG.DAT' is loaded        
13-AUG-21 10:54 :14
========================================
FILE 'AZGRIP_CHK.DAT' is loaded        
13-AUG-21 10:54 :14
========================================
FILE 'AZCONVEYOR_MSG.DAT' is loaded    
13-AUG-21 10:54 :14
========================================
FILE 'AZCMM_CLS_CHUCK.DAT' is loaded   
13-AUG-21 10:54 :14
========================================
FILE 'AZCLOSE_T2.DAT' is loaded        
13-AUG-21 10:54 :14
========================================
FILE 'AZCLOSE_T1.DAT' is loaded        
13-AUG-21 10:54 :14
========================================
FILE 'AZCHUCK_MSG.DAT' is loaded       
13-AUG-21 10:54 :14
========================================
FILE 'AZBGLOGIC_MSG.DAT' is loaded     
13-AUG-21 10:54 :14
========================================
FILE 'AZPAYLOAD.BIN' is loaded         
13-AUG-21 10:54 :14
========================================
FILE 'AZP10037756.BIN' is loaded       
13-AUG-21 10:54 :14
========================================
FILE 'AZP10005662.BIN' is loaded       
13-AUG-21 10:54 :12
========================================
FILE 'AZOVERRIDE.BIN' is loaded        
13-AUG-21 10:54 :12
========================================
FILE 'AZOPEN_T2.BIN' is loaded         
13-AUG-21 10:54 :12
========================================
FILE 'AZOPEN_T1.BIN' is loaded         
13-AUG-21 10:54 :12
========================================
FILE 'AZOP20_2_OPEN_CHUCK.BIN' is loade
d                                      
13-AUG-21 10:54 :12
========================================
FILE 'AZOP20_2_CLS_CHUCK.BIN' is loaded
13-AUG-21 10:54 :12
========================================
FILE 'AZOP20_1_OPEN_CHUCK.BIN' is loade
d                                      
13-AUG-21 10:54 :12
========================================
FILE 'AZOP20_1_CLS_CHUCK.BIN' is loaded
13-AUG-21 10:54 :12
========================================
FILE 'AZOP10_2_OPEN_CHUCK.BIN' is loade
d                                      
13-AUG-21 10:54 :12
========================================
FILE 'AZOP10_2_CLS_CHUCK.BIN' is loaded
13-AUG-21 10:54 :12
========================================
FILE 'AZOP10_1_OPEN_CHUCK.BIN' is loade
d                                      
13-AUG-21 10:54 :12
========================================
FILE 'AZOP10_1_CLS_CHUCK.BIN' is loaded
13-AUG-21 10:54 :12
========================================
FILE 'AZMACH_MSG.BIN' is loaded        
13-AUG-21 10:54 :12
========================================
FILE 'AZHOME_MSG.BIN' is loaded        
13-AUG-21 10:54 :12
========================================
FILE 'AZGRIP_MSG.BIN' is loaded        
13-AUG-21 10:54 :12
========================================
FILE 'AZGRIP_CHK.BIN' is loaded        
13-AUG-21 10:54 :10
========================================
FILE 'AZCONVEYOR_MSG.BIN' is loaded    
13-AUG-21 10:54 :10
========================================
FILE 'AZCMM_CLS_CHUCK.BIN' is loaded   
13-AUG-21 10:54 :10
========================================
FILE 'AZCLOSE_T2.BIN' is loaded        
13-AUG-21 10:54 :10
========================================
FILE 'AZCLOSE_T1.BIN' is loaded        
13-AUG-21 10:54 :10
========================================
FILE 'AZCHUCK_MSG.BIN' is loaded       
13-AUG-21 10:54 :10
========================================
FILE 'AZBGLOGIC_MSG.BIN' is loaded     
13-AUG-21 10:54 :10
========================================
FILE 'TPEINS.XML' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'SWIAUTO.PC' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'SWIUPDT.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'SWIAUTO.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'STRREG.VR' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'RLSVRLUT.VR' is loaded           
13-AUG-21 10:54 :10
========================================
FILE 'POSREG.VR' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'PLCFMOV.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'PLCFCAL.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'NUMREG.VR' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'MHMENU.VR' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'MENU501.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'MENU401.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'MENU301.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'MENU201.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'MENU101.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'IRC_STLABEL.VR' is loaded        
13-AUG-21 10:54 :10
========================================
FILE 'IRC_STATUS.VR' is loaded         
13-AUG-21 10:54 :10
========================================
FILE 'IRC_MSG.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'IRC_COUNTER.VR' is loaded        
13-AUG-21 10:54 :10
========================================
FILE 'IPRNGSHO.VR' is loaded           
13-AUG-21 10:54 :10
========================================
FILE 'IPRNGSET.VR' is loaded           
13-AUG-21 10:54 :10
========================================
FILE 'HTTPKCL.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'HTCOLREC.VR' is loaded           
13-AUG-21 10:54 :10
========================================
FILE 'GEMDATA.VR' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'FRAMEVAR.VR' is loaded           
13-AUG-21 10:54 :10
========================================
FILE 'DOBWDEXITG1.VR' is loaded        
13-AUG-21 10:54 :10
========================================
FILE 'DOBWDEXIT.VR' is loaded          
13-AUG-21 10:54 :10
========================================
FILE 'COMSET.VR' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'ATERRJOB.VR' is loaded           
13-AUG-21 10:54 :10
========================================
FILE 'EMAIL.DG' is loaded              
13-AUG-21 10:54 :10
========================================
FILE-063 (MED:\00\TEMP\SYSPASS.SV) is n
ot loaded                              
FILE-014 File not found                
                                       
                                       
STOP.G                        00100110 
13-AUG-21 10:54 :10
========================================
FILE 'SYSHOST.SV' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'SYSFSAC.SV' is loaded            
13-AUG-21 10:54 :10
========================================
FILE 'SYSEIP.SV' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'SYSEGD.SV' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'EXT1A1.DT' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'EXT1.DT' is loaded               
13-AUG-21 10:54 :10
========================================
FILE 'RC1R.DT' is loaded               
13-AUG-21 10:54 :10
========================================
FILE 'CELLIO.SV' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'DCSPOS.SV' is loaded             
13-AUG-21 10:54 :10
========================================
FILE 'MIXLOGIC.SV' is loaded           
13-AUG-21 10:54 :08
========================================
FILE 'HAPTIC.SV' is loaded             
13-AUG-21 10:54 :08
========================================
FILE 'IAHAND.SV' is loaded             
13-AUG-21 10:54 :08
========================================
FILE 'POSREG.VR' is loaded             
13-AUG-21 10:54 :08
========================================
FILE 'ROSIPCFG.XML' is loaded          
13-AUG-21 10:54 :08
========================================
FILE 'SYSUIF.SV' is loaded             
13-AUG-21 10:54 :08
========================================
FILE 'STRREG.VR' is loaded             
13-AUG-21 10:54 :08
========================================
FILE 'SYSFRAME.SV' is loaded           
13-AUG-21 10:54 :08
========================================
FILE 'SYSMACRO.SV' is loaded           
13-AUG-21 10:54 :08
========================================
FILE 'SYSMAST.SV' is loaded            
13-AUG-21 10:54 :08
========================================
FILE 'SYSSERVO.SV' is loaded           
13-AUG-21 10:54 :08
========================================
FILE 'DIOCFGSV.IO' is loaded           
13-AUG-21 10:54 :08
========================================
FILE 'NUMREG.VR' is loaded             
13-AUG-21 10:54 :08
========================================
FILE 'FRAMEVAR.VR' is loaded           
13-AUG-21 10:54 :08
========================================
FILE 'SYSVARS.SV' is loaded            
13-AUG-21 10:54 :08
========================================
Control start                          
13-AUG-21 10:53 :44
========================================
FILE 'MED:\00\TEMP\DF_MOTN0.DF' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\DF_LOGI6.DF' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\DF_LOGI5.DF' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\DF_LOGI4.DF' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\DF_LOGI3.DF' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\DF_LOGI2.DF' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\DF_LOGI1.DF' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\UPDATE_REF.TP' is lo
aded                                   
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\TS1.TP' is loaded   
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\TOOL2_OPEN.TP' is lo
aded                                   
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\TOOL2_CLOSE.TP' is l
oaded                                  
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\TOOL1_OPEN.TP' is lo
aded                                   
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\TOOL1_CLOSE.TP' is l
oaded                                  
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\SV_ADJST.TP' is load
ed                                     
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\SHIP.TP' is loaded  
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK2_WASHOP20.TP'
 is loaded                             
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK2_WASHOP10.TP'
 is loaded                             
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK2_OP20.TP' is 
loaded                                 
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK2_OP10.TP' is 
loaded                                 
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK1_WASHOP20.TP'
 is loaded                             
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK1_WASHOP10.TP'
 is loaded                             
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK1_OP20.TP' is 
loaded                                 
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RPS_OK1_OP10.TP' is 
loaded                                 
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\RECOVER_MSG.TP' is l
oaded                                  
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\PRG_SELECT.TP' is lo
aded                                   
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\PRGSEL_MSG.TP' is lo
aded                                   
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\PNS0004.TP' is loade
d                                      
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\PNS0002.TP' is loade
d                                      
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\PNS0001.TP' is loade
d                                      
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\PAYLOAD.TP' is loade
d                                      
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\P10037756NEW.TP' is 
loaded                                 
13-AUG-21 10:53 :42
========================================
FILE 'MED:\00\TEMP\P10037756.TP' is loa
ded                                    
13-AUG-21 10:53 :40
========================================
FILE 'MED:\00\TEMP\OVERRIDE.TP' is load
ed                                     
13-AUG-21 10:53 :40
========================================
FILE 'MED:\00\TEMP\ORIENT_MSG.TP' is lo
aded                                   
13-AUG-21 10:53 :40
========================================
FILE 'MED:\00\TEMP\OPEN_TOOL_2_A.TP' is
 loaded                                
13-AUG-21 10:53 :40
========================================
FILE 'MED:\00\TEMP\OPEN_T2.TP' is loade
d                                      
13-AUG-21 10:53 :40
========================================
FILE 'MED:\00\TEMP\OPEN_T1.TP' is loade
d                                      
13-AUG-21 10:53 :40
========================================
FILE 'MED:\00\TEMP\OP20_2_ORIENT2.TP' i
s loaded                               
13-AUG-21 10:53 :40
========================================
FILE 'MED:\00\TEMP\OP20_2_ORIENT1.TP' i
s loaded                               
13-AUG-21 10:53 :40
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 DO[   34]    OFF -> ON 
Tick:   85759
TB:     1621356685
28-AUG-21 20:38 :06
========================================
 DO[   34]    ON  -> OFF
Tick:   85249
TB:     1615078872
28-AUG-21 20:38 :06
========================================
 DO[   34]    OFF -> ON 
Tick:   84739
TB:     1609915030
28-AUG-21 20:38 :06
========================================
 DO[   34]    ON  -> OFF
Tick:   84219
TB:     1604619511
28-AUG-21 20:38 :04
========================================
 DO[   34]    OFF -> ON 
Tick:   83709
TB:     1599467002
28-AUG-21 20:38 :04
========================================
 DO[   34]    ON  -> OFF
Tick:   83199
TB:     1594342225
28-AUG-21 20:38 :04
========================================
 DO[   34]    OFF -> ON 
Tick:   82689
TB:     1589169042
28-AUG-21 20:38 :04
========================================
 DO[   34]    ON  -> OFF
Tick:   82179
TB:     1584015471
28-AUG-21 20:38 :02
========================================
 DO[   34]    OFF -> ON 
Tick:   81659
TB:     1578754145
28-AUG-21 20:38 :02
========================================
 DO[   34]    ON  -> OFF
Tick:   81149
TB:     1573602528
28-AUG-21 20:38 :02
========================================
 DO[   34]    OFF -> ON 
Tick:   80639
TB:     1568445632
28-AUG-21 20:38 :02
========================================
 DO[   34]    ON  -> OFF
Tick:   80129
TB:     1563251663
28-AUG-21 20:38 :00
========================================
 DO[   34]    OFF -> ON 
Tick:   79619
TB:     1558116720
28-AUG-21 20:38 :00
========================================
 DO[   34]    ON  -> OFF
Tick:   79099
TB:     1552888760
28-AUG-21 20:38 :00
========================================
 DO[   34]    OFF -> ON 
Tick:   78589
TB:     1547714908
28-AUG-21 20:38 :00
========================================
 DO[   34]    ON  -> OFF
Tick:   78079
TB:     1542550326
28-AUG-21 20:37 :58
========================================
 DO[   34]    OFF -> ON 
Tick:   77569
TB:     1537379575
28-AUG-21 20:37 :58
========================================
 DO[   34]    ON  -> OFF
Tick:   77059
TB:     1532215724
28-AUG-21 20:37 :58
========================================
 DO[   34]    OFF -> ON 
Tick:   76539
TB:     1526952963
28-AUG-21 20:37 :56
========================================
 DO[   34]    ON  -> OFF
Tick:   76029
TB:     1521760917
28-AUG-21 20:37 :56
========================================
 DO[   34]    OFF -> ON 
Tick:   75519
TB:     1516609951
28-AUG-21 20:37 :56
========================================
 DO[   34]    ON  -> OFF
Tick:   75009
TB:     1511409061
28-AUG-21 20:37 :56
========================================
 DO[   34]    OFF -> ON 
Tick:   74499
TB:     1506259151
28-AUG-21 20:37 :54
========================================
 DO[   34]    ON  -> OFF
Tick:   73979
TB:     1500977491
28-AUG-21 20:37 :54
========================================
 DO[   34]    OFF -> ON 
Tick:   73469
TB:     1495776858
28-AUG-21 20:37 :54
========================================
 DO[   34]    ON  -> OFF
Tick:   72959
TB:     1490020990
28-AUG-21 20:37 :54
========================================
 DO[   34]    OFF -> ON 
Tick:   72449
TB:     1484835740
28-AUG-21 20:37 :52
========================================
 DO[   34]    ON  -> OFF
Tick:   71939
TB:     1479695572
28-AUG-21 20:37 :52
========================================
 DO[   34]    OFF -> ON 
Tick:   71419
TB:     1474396074
28-AUG-21 20:37 :52
========================================
 DO[   34]    ON  -> OFF
Tick:   70909
TB:     1469184140
28-AUG-21 20:37 :52
========================================
 DO[   34]    OFF -> ON 
Tick:   70399
TB:     1464037482
28-AUG-21 20:37 :50
========================================
 DO[   34]    ON  -> OFF
Tick:   69889
TB:     1458842159
28-AUG-21 20:37 :50
========================================
 DO[   34]    OFF -> ON 
Tick:   69379
TB:     1453681067
28-AUG-21 20:37 :50
========================================
 DO[   34]    ON  -> OFF
Tick:   68859
TB:     1448421883
28-AUG-21 20:37 :50
========================================
 DO[   34]    OFF -> ON 
Tick:   68349
TB:     1443219698
28-AUG-21 20:37 :48
========================================
 DO[   34]    ON  -> OFF
Tick:   67839
TB:     1438084950
28-AUG-21 20:37 :48
========================================
 DO[   34]    OFF -> ON 
Tick:   67329
TB:     1432878757
28-AUG-21 20:37 :48
========================================
 DO[   34]    ON  -> OFF
Tick:   66819
TB:     1427686575
28-AUG-21 20:37 :48
========================================
 DO[   34]    OFF -> ON 
Tick:   66299
TB:     1422354786
28-AUG-21 20:37 :46
========================================
 DO[   34]    ON  -> OFF
Tick:   65789
TB:     1417157083
28-AUG-21 20:37 :46
========================================
 DO[   34]    OFF -> ON 
Tick:   65279
TB:     1412026832
28-AUG-21 20:37 :46
========================================
 DO[   34]    ON  -> OFF
Tick:   64769
TB:     1406835579
28-AUG-21 20:37 :44
========================================
 DO[   34]    OFF -> ON 
Tick:   64259
TB:     1401692694
28-AUG-21 20:37 :44
========================================
 DO[   34]    ON  -> OFF
Tick:   63739
TB:     1396423243
28-AUG-21 20:37 :44
========================================
 DO[   34]    OFF -> ON 
Tick:   63229
TB:     1391217646
28-AUG-21 20:37 :44
========================================
 DO[   34]    ON  -> OFF
Tick:   62719
TB:     1386026903
28-AUG-21 20:37 :42
========================================
 DO[   34]    OFF -> ON 
Tick:   62209
TB:     1380857141
28-AUG-21 20:37 :42
========================================
 DO[   34]    ON  -> OFF
Tick:   61699
TB:     1375696093
28-AUG-21 20:37 :42
========================================
 DO[   34]    OFF -> ON 
Tick:   61179
TB:     1370390385
28-AUG-21 20:37 :42
========================================
 DO[   34]    ON  -> OFF
Tick:   60669
TB:     1365172497
28-AUG-21 20:37 :40
========================================
 DO[   34]    OFF -> ON 
Tick:   60159
TB:     1360003832
28-AUG-21 20:37 :40
========================================
 DO[   34]    ON  -> OFF
Tick:   59649
TB:     1354840252
28-AUG-21 20:37 :40
========================================
 DO[   34]    OFF -> ON 
Tick:   59139
TB:     1349685277
28-AUG-21 20:37 :40
========================================
 DO[   34]    ON  -> OFF
Tick:   58619
TB:     1344409014
28-AUG-21 20:37 :38
========================================
 DO[   34]    OFF -> ON 
Tick:   58109
TB:     1339192391
28-AUG-21 20:37 :38
========================================
 DO[   34]    ON  -> OFF
Tick:   57599
TB:     1334011352
28-AUG-21 20:37 :38
========================================
 DO[   34]    OFF -> ON 
Tick:   57089
TB:     1328808532
28-AUG-21 20:37 :38
========================================
 DO[   34]    ON  -> OFF
Tick:   56579
TB:     1323619747
28-AUG-21 20:37 :36
========================================
 DO[   34]    OFF -> ON 
Tick:   56059
TB:     1318342366
28-AUG-21 20:37 :36
========================================
 DO[   34]    ON  -> OFF
Tick:   55549
TB:     1313124470
28-AUG-21 20:37 :36
========================================
 DO[   34]    OFF -> ON 
Tick:   55039
TB:     1307928131
28-AUG-21 20:37 :36
========================================
 DO[   34]    ON  -> OFF
Tick:   54529
TB:     1302735573
28-AUG-21 20:37 :34
========================================
 DO[   34]    OFF -> ON 
Tick:   54019
TB:     1297589244
28-AUG-21 20:37 :34
========================================
 DO[   34]    ON  -> OFF
Tick:   53499
TB:     1292241998
28-AUG-21 20:37 :34
========================================
 DO[   34]    OFF -> ON 
Tick:   52989
TB:     1287020546
28-AUG-21 20:37 :32
========================================
 DO[   34]    ON  -> OFF
Tick:   52479
TB:     1281863878
28-AUG-21 20:37 :32
========================================
 DO[   34]    OFF -> ON 
Tick:   51969
TB:     1276581232
28-AUG-21 20:37 :32
========================================
 DO[   34]    ON  -> OFF
Tick:   51459
TB:     1271427257
28-AUG-21 20:37 :32
========================================
 DO[   34]    OFF -> ON 
Tick:   50939
TB:     1266167358
28-AUG-21 20:37 :30
========================================
 DO[   34]    ON  -> OFF
Tick:   50429
TB:     1260935721
28-AUG-21 20:37 :30
========================================
 DO[   34]    OFF -> ON 
Tick:   49919
TB:     1255774591
28-AUG-21 20:37 :30
========================================
 DO[   34]    ON  -> OFF
Tick:   49409
TB:     1250617043
28-AUG-21 20:37 :30
========================================
 DO[   34]    OFF -> ON 
Tick:   48899
TB:     1245449855
28-AUG-21 20:37 :28
========================================
 DO[   34]    ON  -> OFF
Tick:   48379
TB:     1240196681
28-AUG-21 20:37 :28
========================================
 DO[   34]    OFF -> ON 
Tick:   47869
TB:     1235002774
28-AUG-21 20:37 :28
========================================
 DO[   34]    ON  -> OFF
Tick:   47359
TB:     1229834871
28-AUG-21 20:37 :28
========================================
 DO[   34]    OFF -> ON 
Tick:   46849
TB:     1224487683
28-AUG-21 20:37 :26
========================================
 DO[   34]    ON  -> OFF
Tick:   46339
TB:     1219332062
28-AUG-21 20:37 :26
========================================
 DO[   34]    OFF -> ON 
Tick:   45819
TB:     1214048934
28-AUG-21 20:37 :26
========================================
 DO[   34]    ON  -> OFF
Tick:   45309
TB:     1208870632
28-AUG-21 20:37 :26
========================================
 DO[   34]    OFF -> ON 
Tick:   44799
TB:     1203694900
28-AUG-21 20:37 :24
========================================
 DO[   34]    ON  -> OFF
Tick:   44289
TB:     1198495630
28-AUG-21 20:37 :24
========================================
 DO[   34]    OFF -> ON 
Tick:   43779
TB:     1193269259
28-AUG-21 20:37 :24
========================================
 DO[   34]    ON  -> OFF
Tick:   43259
TB:     1187966810
28-AUG-21 20:37 :24
========================================
 DO[   34]    OFF -> ON 
Tick:   42749
TB:     1182736547
28-AUG-21 20:37 :22
========================================
 DO[   34]    ON  -> OFF
Tick:   42239
TB:     1177535748
28-AUG-21 20:37 :22
========================================
 DO[   34]    OFF -> ON 
Tick:   41729
TB:     1172299226
28-AUG-21 20:37 :22
========================================
 DO[   34]    ON  -> OFF
Tick:   41219
TB:     1167102923
28-AUG-21 20:37 :22
========================================
 DO[   34]    OFF -> ON 
Tick:   40699
TB:     1161798310
28-AUG-21 20:37 :20
========================================
 DO[   34]    ON  -> OFF
Tick:   40189
TB:     1156599132
28-AUG-21 20:37 :20
========================================
 DO[   34]    OFF -> ON 
Tick:   39679
TB:     1151414817
28-AUG-21 20:37 :20
========================================
 DO[   34]    ON  -> OFF
Tick:   39169
TB:     1146232627
28-AUG-21 20:37 :18
========================================
 DO[   34]    OFF -> ON 
Tick:   38659
TB:     1141048394
28-AUG-21 20:37 :18
========================================
 DO[   34]    ON  -> OFF
Tick:   38139
TB:     1135750940
28-AUG-21 20:37 :18
========================================
 DO[   34]    OFF -> ON 
Tick:   37629
TB:     1130522769
28-AUG-21 20:37 :18
========================================
 DO[   34]    ON  -> OFF
Tick:   37119
TB:     1125343437
28-AUG-21 20:37 :16
========================================
 DO[   34]    OFF -> ON 
Tick:   36609
TB:     1120133397
28-AUG-21 20:37 :16
========================================
 DO[   34]    ON  -> OFF
Tick:   36099
TB:     1114946607
28-AUG-21 20:37 :16
========================================
 DO[   34]    OFF -> ON 
Tick:   35579
TB:     1109636069
28-AUG-21 20:37 :16
========================================
 DO[   34]    ON  -> OFF
Tick:   35069
TB:     1104462841
28-AUG-21 20:37 :14
========================================
 DO[   34]    OFF -> ON 
Tick:   34559
TB:     1099280816
28-AUG-21 20:37 :14
========================================
 DO[   34]    ON  -> OFF
Tick:   34049
TB:     1094051852
28-AUG-21 20:37 :14
========================================
 DO[   34]    OFF -> ON 
Tick:   33539
TB:     1088833030
28-AUG-21 20:37 :14
========================================
 DO[   34]    ON  -> OFF
Tick:   33019
TB:     1083556008
28-AUG-21 20:37 :12
========================================
 DO[   34]    OFF -> ON 
Tick:   32509
TB:     1078329399
28-AUG-21 20:37 :12
========================================
 DO[   34]    ON  -> OFF
Tick:   31999
TB:     1073170507
28-AUG-21 20:37 :12
========================================
 DO[   34]    OFF -> ON 
Tick:   31489
TB:     1067971088
28-AUG-21 20:37 :12
========================================
 DO[   34]    ON  -> OFF
Tick:   30979
TB:     1062800726
28-AUG-21 20:37 :10
========================================
 DO[   34]    OFF -> ON 
Tick:   30459
TB:     1057504231
28-AUG-21 20:37 :10
========================================
 DO[    2]    OFF -> ON 
 UO[    2]    OFF -> ON 
 DO[    6]    ON  -> OFF
 UO[    6]    ON  -> OFF
Tick:   30429
TB:     1057191343
28-AUG-21 20:37 :10
========================================
 SO[    3]    ON  -> OFF
Tick:   30428
TB:     1057181496
28-AUG-21 20:37 :10
========================================
 DO[   35]    ON  -> OFF
Tick:   30399
TB:     1056896885
28-AUG-21 20:37 :10
========================================
 DO[    2]    ON  -> OFF
 UO[    2]    ON  -> OFF
 DO[    6]    OFF -> ON 
 UO[    6]    OFF -> ON 
Tick:   30369
TB:     1056503378
28-AUG-21 20:37 :10
========================================
 SO[    3]    OFF -> ON 
Tick:   30368
TB:     1056495667
28-AUG-21 20:37 :10
========================================
 DO[    8]    OFF -> ON 
 UO[    8]    OFF -> ON 
Tick:   30339
TB:     1056198476
28-AUG-21 20:37 :10
========================================
 SO[    7]    OFF -> ON 
Tick:   30338
TB:     1056184636
28-AUG-21 20:37 :10
========================================
 DO[   34]    ON  -> OFF
Tick:   29949
TB:     1052086819
28-AUG-21 20:37 :10
========================================
 DO[   34]    OFF -> ON 
Tick:   29439
TB:     1046268164
28-AUG-21 20:37 :08
========================================
 DO[   34]    ON  -> OFF
Tick:   28929
TB:     1040674161
28-AUG-21 20:37 :08
========================================
 DO[   34]    OFF -> ON 
Tick:   28419
TB:     1034775945
28-AUG-21 20:37 :08
========================================
 DO[   34]    ON  -> OFF
Tick:   27899
TB:     1028894111
28-AUG-21 20:37 :08
========================================
 DO[   34]    OFF -> ON 
Tick:   27389
TB:     1023679012
28-AUG-21 20:37 :06
========================================
 DO[   34]    ON  -> OFF
Tick:   26879
TB:     1018472660
28-AUG-21 20:37 :06
========================================
 DO[   34]    OFF -> ON 
Tick:   26369
TB:     1013250111
28-AUG-21 20:37 :06
========================================
 DO[   34]    ON  -> OFF
Tick:   25859
TB:     1008062185
28-AUG-21 20:37 :06
========================================
 DO[   34]    OFF -> ON 
Tick:   25339
TB:     1002786401
28-AUG-21 20:37 :04
========================================
 DO[   34]    ON  -> OFF
Tick:   24829
TB:     997610565
28-AUG-21 20:37 :04
========================================
 DO[   34]    OFF -> ON 
Tick:   24319
TB:     992452376
28-AUG-21 20:37 :04
========================================
 DO[   34]    ON  -> OFF
Tick:   23809
TB:     987296027
28-AUG-21 20:37 :04
========================================
 DO[   34]    OFF -> ON 
Tick:   23299
TB:     982164824
28-AUG-21 20:37 :02
========================================
 DO[   34]    ON  -> OFF
Tick:   22779
TB:     976880438
28-AUG-21 20:37 :02
========================================
 DO[   34]    OFF -> ON 
Tick:   22269
TB:     971739348
28-AUG-21 20:37 :02
========================================
 DO[   34]    ON  -> OFF
Tick:   21759
TB:     966598396
28-AUG-21 20:37 :00
========================================
 DO[   34]    OFF -> ON 
Tick:   21249
TB:     961427859
28-AUG-21 20:37 :00
========================================
 DO[   34]    ON  -> OFF
Tick:   20739
TB:     956305905
28-AUG-21 20:37 :00
========================================
 DO[   34]    OFF -> ON 
Tick:   20219
TB:     951039402
28-AUG-21 20:37 :00
========================================
 DO[   34]    ON  -> OFF
Tick:   19709
TB:     945918271
28-AUG-21 20:36 :58
========================================
 DO[   34]    OFF -> ON 
Tick:   19199
TB:     940790107
28-AUG-21 20:36 :58
========================================
 DO[   34]    ON  -> OFF
Tick:   18689
TB:     935640766
28-AUG-21 20:36 :58
========================================
 DO[   34]    OFF -> ON 
Tick:   18179
TB:     930495039
28-AUG-21 20:36 :58
========================================
 DO[   34]    ON  -> OFF
Tick:   17659
TB:     925267561
28-AUG-21 20:36 :56
========================================
 DO[   34]    OFF -> ON 
Tick:   17149
TB:     920077163
28-AUG-21 20:36 :56
========================================
 DO[   34]    ON  -> OFF
Tick:   16639
TB:     914978356
28-AUG-21 20:36 :56
========================================
 DO[   34]    OFF -> ON 
Tick:   16129
TB:     909848606
28-AUG-21 20:36 :56
========================================
 DO[   34]    ON  -> OFF
Tick:   15619
TB:     904729753
28-AUG-21 20:36 :54
========================================
 DO[   34]    OFF -> ON 
Tick:   15099
TB:     899475618
28-AUG-21 20:36 :54
========================================
 DO[   34]    ON  -> OFF
Tick:   14589
TB:     894311890
28-AUG-21 20:36 :54
========================================
 DO[   34]    OFF -> ON 
Tick:   14079
TB:     889138786
28-AUG-21 20:36 :54
========================================
 DO[   34]    ON  -> OFF
Tick:   13569
TB:     883965360
28-AUG-21 20:36 :52
========================================
 DO[   34]    OFF -> ON 
Tick:   13059
TB:     878832603
28-AUG-21 20:36 :52
========================================
 DO[   34]    ON  -> OFF
Tick:   12539
TB:     873502386
28-AUG-21 20:36 :52
========================================
 DO[   34]    OFF -> ON 
Tick:   12029
TB:     868305401
28-AUG-21 20:36 :52
========================================
 DO[   34]    ON  -> OFF
Tick:   11519
TB:     863136672
28-AUG-21 20:36 :50
========================================
 DO[   34]    OFF -> ON 
Tick:   11009
TB:     857932056
28-AUG-21 20:36 :50
========================================
 DO[   34]    ON  -> OFF
Tick:   10499
TB:     852758604
28-AUG-21 20:36 :50
========================================
 DO[   34]    OFF -> ON 
Tick:   9979
TB:     847494327
28-AUG-21 20:36 :50
========================================
 DO[   34]    ON  -> OFF
Tick:   9469
TB:     842260444
28-AUG-21 20:36 :48
========================================
 DO[   34]    OFF -> ON 
Tick:   8959
TB:     837074700
28-AUG-21 20:36 :48
========================================
 DO[   34]    ON  -> OFF
Tick:   8449
TB:     831884468
28-AUG-21 20:36 :48
========================================
 DO[   34]    OFF -> ON 
Tick:   7939
TB:     826714875
28-AUG-21 20:36 :46
========================================
 DO[   34]    ON  -> OFF
Tick:   7419
TB:     821494514
28-AUG-21 20:36 :46
========================================
 DO[   34]    OFF -> ON 
Tick:   6909
TB:     816203400
28-AUG-21 20:36 :46
========================================
 DO[   34]    ON  -> OFF
Tick:   6399
TB:     810840246
28-AUG-21 20:36 :46
========================================
 DO[   34]    OFF -> ON 
Tick:   5889
TB:     805720289
28-AUG-21 20:36 :44
========================================
 DO[    2]    OFF -> ON 
 UO[    2]    OFF -> ON 
 DO[    6]    ON  -> OFF
 UO[    6]    ON  -> OFF
 DO[   34]    ON  -> OFF
Tick:   5379
TB:     800430372
28-AUG-21 20:36 :44
========================================
 SO[    3]    ON  -> OFF
Tick:   5378
TB:     800417921
28-AUG-21 20:36 :44
========================================
 SO[    0]    ON  -> OFF
Tick:   5118
TB:     797585696
28-AUG-21 20:36 :44
========================================
 DO[   34]    OFF -> ON 
Tick:   4859
TB:     794917129
28-AUG-21 20:36 :44
========================================
 DO[   34]    ON  -> OFF
Tick:   4349
TB:     789795628
28-AUG-21 20:36 :44
========================================
 DO[   34]    OFF -> ON 
Tick:   3839
TB:     784622351
28-AUG-21 20:36 :42
========================================
 DO[   34]    ON  -> OFF
Tick:   3329
TB:     779513300
28-AUG-21 20:36 :42
========================================
 DO[   34]    OFF -> ON 
Tick:   2819
TB:     774300974
28-AUG-21 20:36 :42
========================================
 SO[    6]    OFF -> ON 
Tick:   2288
TB:     768821782
28-AUG-21 20:36 :42
========================================
 SO[    0]    OFF -> ON 
Tick:   1568
TB:     761342701
28-AUG-21 20:36 :40
========================================
 SO[    1]    ON  -> OFF
Tick:   1348
TB:     759076074
28-AUG-21 20:36 :40
========================================
 DO[    3]    ON  -> OFF
 UO[    3]    ON  -> OFF
 DO[   10]    ON  -> OFF
 UO[   10]    ON  -> OFF
Tick:   1339
TB:     758997071
28-AUG-21 20:36 :40
========================================
 DO[    3]    OFF -> ON 
 UO[    3]    OFF -> ON 
 DO[   10]    OFF -> ON 
 UO[   10]    OFF -> ON 
 DO[   11]    OFF -> ON 
 UO[   11]    OFF -> ON 
Tick:   1309
TB:     758396881
28-AUG-21 20:36 :40
========================================
 SO[    1]    OFF -> ON 
Tick:   1308
TB:     758367953
28-AUG-21 20:36 :40
========================================
 DO[  140]    ON  -> OFF
 DO[  141]    OFF -> ON 
 DO[  142]    ON  -> OFF
 DO[  172]    ON  -> OFF
 DO[  173]    OFF -> ON 
 DO[  174]    ON  -> OFF
Tick:   1292
TB:     755021964
28-AUG-21 20:36 :40
========================================
 DO[   69]    OFF -> ON 
 DO[   70]    OFF -> ON 
 DO[   71]    OFF -> ON 
 DO[  105]    OFF -> ON 
 DO[  119]    OFF -> ON 
 DO[  120]    OFF -> ON 
 DO[  127]    OFF -> ON 
 DO[  128]    OFF -> ON 
Tick:   1290
TB:     755011756
28-AUG-21 20:36 :40
========================================
 GO[    4]    0 -> 1
 GO[    5]    0 -> 2194
 DO[  481]    OFF -> ON 
 DO[  498]    OFF -> ON 
 DO[  501]    OFF -> ON 
 DO[  504]    OFF -> ON 
 DO[  508]    OFF -> ON 
 DO[    6]    OFF -> ON 
 UO[    6]    OFF -> ON 
 DO[    7]    OFF -> ON 
 UO[    7]    OFF -> ON 
 DO[   23]    OFF -> ON 
 DO[   24]    OFF -> ON 
 DO[   33]    OFF -> ON 
 DO[   35]    OFF -> ON 
Tick:   1289
TB:     755010621
28-AUG-21 20:36 :40
========================================
 DO[  253]    ON  -> OFF
 DO[  254]    OFF -> ON 
 DO[  255]    ON  -> OFF
Tick:   1285
TB:     754989476
28-AUG-21 20:36 :40
========================================
 DO[  221]    ON  -> OFF
 DO[  222]    OFF -> ON 
 DO[  223]    ON  -> OFF
Tick:   1284
TB:     754988506
28-AUG-21 20:36 :40
========================================
 SO[    3]    OFF -> ON 
SPI[    1]    OFF -> ON 
SPI[    2]    OFF -> ON 
SPI[    3]    OFF -> ON 
SPI[    4]    OFF -> ON 
SPI[    5]    OFF -> ON 
SPI[    6]    OFF -> ON 
SPI[    7]    OFF -> ON 
SPI[    8]    OFF -> ON 
SPI[    9]    OFF -> ON 
SPI[   10]    OFF -> ON 
SPI[   11]    OFF -> ON 
SPI[   12]    OFF -> ON 
SPI[   13]    OFF -> ON 
SPI[   14]    OFF -> ON 
SPI[   15]    OFF -> ON 
SPI[   16]    OFF -> ON 
SSI[    1]    OFF -> ON 
SSI[    2]    OFF -> ON 
SSI[    3]    OFF -> ON 
SSI[    5]    OFF -> ON 
SSI[    6]    OFF -> ON 
SSI[    9]    OFF -> ON 
Tick:   1028
TB:     753256602
28-AUG-21 20:36 :40
========================================
R:89 S:3 M:55 T:1 N:145 0->0
R:89 S:3 M:55 T:1 N:146 0->0
R:89 S:3 M:55 T:1 N:147 0->0
R:89 S:3 M:55 T:1 N:148 0->0
R:89 S:3 M:55 T:1 N:149 0->0
R:89 S:3 M:55 T:1 N:150 0->0
R:89 S:3 M:55 T:1 N:151 0->0
R:89 S:3 M:55 T:1 N:152 0->0
R:89 S:3 M:55 T:1 N:153 0->0
R:89 S:3 M:55 T:1 N:154 0->0
R:89 S:3 M:55 T:1 N:155 0->0
R:89 S:3 M:55 T:1 N:156 0->0
R:89 S:3 M:55 T:1 N:157 0->0
R:89 S:3 M:55 T:1 N:158 0->0
R:89 S:3 M:55 T:1 N:159 0->0
R:89 S:3 M:55 T:1 N:160 0->0
Tick:   1017
TB:     753238852
28-AUG-21 20:36 :40
========================================
 GI[   13]    0
 GI[   14]    0
 DI[  226]    OFF
 DI[  227]    OFF
 DI[  228]    OFF
 DI[  229]    OFF
 DI[  230]    OFF
 DI[  231]    OFF
 DI[  232]    OFF
 DI[  233]    OFF
 DI[  234]    OFF
 DI[  235]    OFF
 DI[  236]    OFF
 DI[  237]    OFF
 DI[  238]    OFF
 DI[  239]    OFF
 DI[  240]    OFF
 DI[  241]    OFF
R:89 S:3 M:55 T:1 N:33 0->0
R:89 S:3 M:55 T:1 N:34 0->0
R:89 S:3 M:55 T:1 N:35 0->0
R:89 S:3 M:55 T:1 N:36 0->0
R:89 S:3 M:55 T:1 N:37 0->0
R:89 S:3 M:55 T:1 N:38 0->0
R:89 S:3 M:55 T:1 N:39 0->0
R:89 S:3 M:55 T:1 N:40 0->0
 DI[  242]    OFF
 DI[  243]    OFF
 DI[  244]    OFF
 DI[  245]    OFF
 DI[  246]    OFF
 DI[  247]    OFF
 DI[  248]    OFF
 DI[  249]    OFF
 DI[  250]    OFF
 DI[  251]    OFF
 DI[  252]    OFF
 DI[  253]    OFF
 DI[  254]    OFF
 DI[  255]    OFF
 DI[  256]    OFF
 DI[  257]    OFF
 DI[  258]    OFF
 DI[  259]    OFF
 DI[  260]    OFF
 DI[  261]    OFF
 DI[  262]    OFF
 DI[  263]    OFF
 DI[  264]    OFF
 DI[  265]    OFF
R:89 S:3 M:55 T:1 N:65 0->0
R:89 S:3 M:55 T:1 N:66 0->0
R:89 S:3 M:55 T:1 N:67 0->0
R:89 S:3 M:55 T:1 N:68 0->0
R:89 S:3 M:55 T:1 N:69 0->0
R:89 S:3 M:55 T:1 N:70 0->0
R:89 S:3 M:55 T:1 N:71 0->0
R:89 S:3 M:55 T:1 N:72 0->0
R:89 S:3 M:55 T:1 N:73 0->0
R:89 S:3 M:55 T:1 N:74 0->0
R:89 S:3 M:55 T:1 N:75 0->0
R:89 S:3 M:55 T:1 N:76 0->0
R:89 S:3 M:55 T:1 N:77 0->0
R:89 S:3 M:55 T:1 N:78 0->0
R:89 S:3 M:55 T:1 N:79 0->0
R:89 S:3 M:55 T:1 N:80 0->0
 DI[  274]    OFF
 DI[  275]    OFF
 DI[  276]    OFF
 DI[  277]    OFF
 DI[  278]    OFF
 DI[  279]    OFF
 DI[  280]    OFF
 DI[  281]    OFF
 DI[  282]    OFF
 DI[  283]    OFF
 DI[  284]    OFF
 DI[  285]    OFF
 DI[  286]    OFF
 DI[  287]    OFF
 DI[  288]    OFF
 DI[  289]    OFF
 DI[  290]    OFF
R:89 S:3 M:55 T:1 N:98 0->0
R:89 S:3 M:55 T:1 N:99 0->0
R:89 S:3 M:55 T:1 N:100 0->0
R:89 S:3 M:55 T:1 N:101 0->0
R:89 S:3 M:55 T:1 N:102 0->0
R:89 S:3 M:55 T:1 N:103 0->0
R:89 S:3 M:55 T:1 N:104 0->0
 DI[  347]    OFF
 DI[  348]    OFF
 DI[  349]    OFF
 DI[  350]    OFF
 DI[  351]    OFF
 DI[  352]    OFF
 DI[  353]    OFF
 DI[  354]    OFF
 DI[  355]    OFF
 DI[  356]    OFF
 DI[  357]    OFF
 DI[  358]    OFF
 DI[  359]    OFF
 DI[  360]    OFF
 DI[  361]    OFF
 DI[  362]    OFF
 DI[  363]    OFF
R:89 S:3 M:55 T:1 N:122 0->0
R:89 S:3 M:55 T:1 N:123 0->0
R:89 S:3 M:55 T:1 N:124 0->0
R:89 S:3 M:55 T:1 N:125 0->0
R:89 S:3 M:55 T:1 N:126 0->0
R:89 S:3 M:55 T:1 N:127 0->0
R:89 S:3 M:55 T:1 N:128 0->0
R:89 S:3 M:55 T:1 N:129 0->0
R:89 S:3 M:55 T:1 N:130 0->0
R:89 S:3 M:55 T:1 N:131 0->0
R:89 S:3 M:55 T:1 N:132 0->0
R:89 S:3 M:55 T:1 N:133 0->0
R:89 S:3 M:55 T:1 N:134 0->0
R:89 S:3 M:55 T:1 N:135 0->0
R:89 S:3 M:55 T:1 N:136 0->0
R:89 S:3 M:55 T:1 N:137 0->0
R:89 S:3 M:55 T:1 N:138 0->0
R:89 S:3 M:55 T:1 N:139 0->0
R:89 S:3 M:55 T:1 N:140 0->0
R:89 S:3 M:55 T:1 N:141 0->0
R:89 S:3 M:55 T:1 N:142 0->0
R:89 S:3 M:55 T:1 N:143 0->0
R:89 S:3 M:55 T:1 N:144 0->0
Tick:   1016
TB:     753237957
28-AUG-21 20:36 :40
========================================
 GO[   13]    0
 GO[   14]    0
 DO[  250]    OFF
 DO[  251]    OFF
 DO[  252]    OFF
 DO[  253]    ON 
 DO[  254]    OFF
 DO[  255]    ON 
 DO[  256]    OFF
 DO[  257]    OFF
 DO[  258]    OFF
 DO[  259]    OFF
 DO[  260]    OFF
 DO[  261]    OFF
 DO[  262]    OFF
 DO[  263]    OFF
 DO[  264]    OFF
 DO[  265]    OFF
R:89 S:3 M:55 T:2 N:65 0->0
R:89 S:3 M:55 T:2 N:66 0->0
R:89 S:3 M:55 T:2 N:67 0->0
R:89 S:3 M:55 T:2 N:68 0->0
R:89 S:3 M:55 T:2 N:69 0->0
R:89 S:3 M:55 T:2 N:70 0->0
R:89 S:3 M:55 T:2 N:71 0->0
R:89 S:3 M:55 T:2 N:72 0->0
R:89 S:3 M:55 T:2 N:73 0->0
R:89 S:3 M:55 T:2 N:74 0->0
R:89 S:3 M:55 T:2 N:75 0->0
R:89 S:3 M:55 T:2 N:76 0->0
R:89 S:3 M:55 T:2 N:77 0->0
R:89 S:3 M:55 T:2 N:78 0->0
R:89 S:3 M:55 T:2 N:79 0->0
R:89 S:3 M:55 T:2 N:80 0->0
 DO[  274]    OFF
 DO[  275]    OFF
 DO[  276]    OFF
 DO[  277]    OFF
 DO[  278]    OFF
 DO[  279]    OFF
 DO[  280]    OFF
 DO[  281]    OFF
 DO[  282]    OFF
 DO[  283]    OFF
 DO[  284]    OFF
 DO[  285]    OFF
 DO[  286]    OFF
 DO[  287]    OFF
 DO[  288]    OFF
 DO[  289]    OFF
 DO[  290]    OFF
R:89 S:3 M:55 T:2 N:98 0->0
R:89 S:3 M:55 T:2 N:99 0->0
R:89 S:3 M:55 T:2 N:100 0->0
R:89 S:3 M:55 T:2 N:101 0->0
R:89 S:3 M:55 T:2 N:102 0->0
R:89 S:3 M:55 T:2 N:103 0->0
R:89 S:3 M:55 T:2 N:104 0->0
 DO[  347]    OFF
 DO[  348]    OFF
 DO[  349]    OFF
 DO[  350]    OFF
 DO[  351]    OFF
 DO[  352]    OFF
 DO[  353]    OFF
 DO[  354]    OFF
 DO[  355]    OFF
 DO[  356]    OFF
 DO[  357]    OFF
 DO[  358]    OFF
 DO[  359]    OFF
 DO[  360]    OFF
 DO[  361]    OFF
 DO[  362]    OFF
 DO[  363]    OFF
R:89 S:3 M:55 T:2 N:122 0->0
R:89 S:3 M:55 T:2 N:123 0->0
R:89 S:3 M:55 T:2 N:124 0->0
R:89 S:3 M:55 T:2 N:125 0->0
R:89 S:3 M:55 T:2 N:126 0->0
R:89 S:3 M:55 T:2 N:127 0->0
R:89 S:3 M:55 T:2 N:128 0->0
R:89 S:3 M:55 T:2 N:129 0->0
R:89 S:3 M:55 T:2 N:130 0->0
R:89 S:3 M:55 T:2 N:131 0->0
R:89 S:3 M:55 T:2 N:132 0->0
R:89 S:3 M:55 T:2 N:133 0->0
R:89 S:3 M:55 T:2 N:134 0->0
R:89 S:3 M:55 T:2 N:135 0->0
R:89 S:3 M:55 T:2 N:136 0->0
R:89 S:3 M:55 T:2 N:137 0->0
R:89 S:3 M:55 T:2 N:138 0->0
R:89 S:3 M:55 T:2 N:139 0->0
R:89 S:3 M:55 T:2 N:140 0->0
R:89 S:3 M:55 T:2 N:141 0->0
R:89 S:3 M:55 T:2 N:142 0->0
R:89 S:3 M:55 T:2 N:143 0->0
R:89 S:3 M:55 T:2 N:144 0->0
R:89 S:3 M:55 T:2 N:145 0->0
R:89 S:3 M:55 T:2 N:146 0->0
R:89 S:3 M:55 T:2 N:147 0->0
R:89 S:3 M:55 T:2 N:148 0->0
R:89 S:3 M:55 T:2 N:149 0->0
R:89 S:3 M:55 T:2 N:150 0->0
R:89 S:3 M:55 T:2 N:151 0->0
R:89 S:3 M:55 T:2 N:152 0->0
R:89 S:3 M:55 T:2 N:153 0->0
R:89 S:3 M:55 T:2 N:154 0->0
R:89 S:3 M:55 T:2 N:155 0->0
R:89 S:3 M:55 T:2 N:156 0->0
R:89 S:3 M:55 T:2 N:157 0->0
R:89 S:3 M:55 T:2 N:158 0->0
R:89 S:3 M:55 T:2 N:159 0->0
R:89 S:3 M:55 T:2 N:160 0->0
 DI[  210]    OFF
 DI[  211]    OFF
 DI[  212]    OFF
 DI[  213]    OFF
 DI[  214]    OFF
 DI[  215]    OFF
 DI[  216]    OFF
 DI[  217]    OFF
 DI[  218]    OFF
 DI[  219]    OFF
 DI[  220]    OFF
 DI[  221]    OFF
 DI[  222]    OFF
 DI[  223]    OFF
 DI[  224]    OFF
 DI[  225]    OFF
Tick:   1015
TB:     753237157
28-AUG-21 20:36 :40
========================================
 GI[   11]    0
 GI[   12]    0
 DI[  193]    OFF
 DI[  194]    OFF
 DI[  195]    OFF
 DI[  196]    OFF
 DI[  197]    OFF
 DI[  198]    OFF
 DI[  199]    OFF
 DI[  200]    OFF
 DI[  201]    OFF
 DI[  202]    OFF
 DI[  203]    OFF
 DI[  204]    OFF
 DI[  205]    OFF
 DI[  206]    OFF
 DI[  207]    OFF
 DI[  208]    OFF
 DI[  209]    OFF
R:89 S:2 M:55 T:1 N:98 0->0
R:89 S:2 M:55 T:1 N:99 0->0
R:89 S:2 M:55 T:1 N:100 0->0
R:89 S:2 M:55 T:1 N:101 0->0
R:89 S:2 M:55 T:1 N:102 0->0
R:89 S:2 M:55 T:1 N:103 0->0
R:89 S:2 M:55 T:1 N:104 0->0
 DI[  329]    OFF
 DI[  330]    OFF
 DI[  331]    OFF
 DI[  332]    OFF
 DI[  333]    OFF
 DI[  334]    OFF
 DI[  335]    OFF
 DI[  336]    OFF
 DI[  337]    OFF
 DI[  338]    OFF
 DI[  339]    OFF
 DI[  340]    OFF
 DI[  341]    OFF
 DI[  342]    OFF
 DI[  343]    OFF
 DI[  344]    OFF
 DI[  345]    OFF
R:89 S:2 M:55 T:1 N:122 0->0
R:89 S:2 M:55 T:1 N:123 0->0
R:89 S:2 M:55 T:1 N:124 0->0
R:89 S:2 M:55 T:1 N:125 0->0
R:89 S:2 M:55 T:1 N:126 0->0
R:89 S:2 M:55 T:1 N:127 0->0
R:89 S:2 M:55 T:1 N:128 0->0
R:89 S:2 M:55 T:1 N:129 0->0
R:89 S:2 M:55 T:1 N:130 0->0
R:89 S:2 M:55 T:1 N:131 0->0
R:89 S:2 M:55 T:1 N:132 0->0
R:89 S:2 M:55 T:1 N:133 0->0
R:89 S:2 M:55 T:1 N:134 0->0
R:89 S:2 M:55 T:1 N:135 0->0
R:89 S:2 M:55 T:1 N:136 0->0
R:89 S:2 M:55 T:1 N:137 0->0
R:89 S:2 M:55 T:1 N:138 0->0
R:89 S:2 M:55 T:1 N:139 0->0
R:89 S:2 M:55 T:1 N:140 0->0
R:89 S:2 M:55 T:1 N:141 0->0
R:89 S:2 M:55 T:1 N:142 0->0
R:89 S:2 M:55 T:1 N:143 0->0
R:89 S:2 M:55 T:1 N:144 0->0
R:89 S:2 M:55 T:1 N:145 0->0
R:89 S:2 M:55 T:1 N:146 0->0
R:89 S:2 M:55 T:1 N:147 0->0
R:89 S:2 M:55 T:1 N:148 0->0
R:89 S:2 M:55 T:1 N:149 0->0
R:89 S:2 M:55 T:1 N:150 0->0
R:89 S:2 M:55 T:1 N:151 0->0
R:89 S:2 M:55 T:1 N:152 0->0
R:89 S:2 M:55 T:1 N:153 0->0
R:89 S:2 M:55 T:1 N:154 0->0
R:89 S:2 M:55 T:1 N:155 0->0
R:89 S:2 M:55 T:1 N:156 0->0
R:89 S:2 M:55 T:1 N:157 0->0
R:89 S:2 M:55 T:1 N:158 0->0
R:89 S:2 M:55 T:1 N:159 0->0
R:89 S:2 M:55 T:1 N:160 0->0
 DO[  210]    OFF
 DO[  211]    OFF
 DO[  212]    OFF
 DO[  213]    OFF
 DO[  214]    OFF
 DO[  215]    OFF
 DO[  216]    OFF
 DO[  217]    OFF
 DO[  218]    OFF
 DO[  219]    OFF
 DO[  220]    OFF
 DO[  221]    ON 
 DO[  222]    OFF
 DO[  223]    ON 
 DO[  224]    OFF
 DO[  225]    OFF
 DO[  226]    OFF
 DO[  227]    OFF
 DO[  228]    OFF
 DO[  229]    OFF
 DO[  230]    OFF
 DO[  231]    OFF
 DO[  232]    OFF
 DO[  233]    OFF
 DO[  234]    OFF
 DO[  235]    OFF
 DO[  236]    OFF
 DO[  237]    OFF
 DO[  238]    OFF
 DO[  239]    OFF
 DO[  240]    OFF
 DO[  241]    OFF
R:89 S:3 M:55 T:2 N:33 0->0
R:89 S:3 M:55 T:2 N:34 0->0
R:89 S:3 M:55 T:2 N:35 0->0
R:89 S:3 M:55 T:2 N:36 0->0
R:89 S:3 M:55 T:2 N:37 0->0
R:89 S:3 M:55 T:2 N:38 0->0
R:89 S:3 M:55 T:2 N:39 0->0
R:89 S:3 M:55 T:2 N:40 0->0
 DO[  242]    OFF
 DO[  243]    OFF
 DO[  244]    OFF
 DO[  245]    OFF
 DO[  246]    OFF
 DO[  247]    OFF
 DO[  248]    OFF
 DO[  249]    OFF
Tick:   1014
TB:     753232552
28-AUG-21 20:36 :40
========================================
 DO[  337]    OFF
 DO[  338]    OFF
 DO[  339]    OFF
 DO[  340]    OFF
 DO[  341]    OFF
 DO[  342]    OFF
 DO[  343]    OFF
 DO[  344]    OFF
 DO[  345]    OFF
R:89 S:2 M:55 T:2 N:122 0->0
R:89 S:2 M:55 T:2 N:123 0->0
R:89 S:2 M:55 T:2 N:124 0->0
R:89 S:2 M:55 T:2 N:125 0->0
R:89 S:2 M:55 T:2 N:126 0->0
R:89 S:2 M:55 T:2 N:127 0->0
R:89 S:2 M:55 T:2 N:128 0->0
R:89 S:2 M:55 T:2 N:129 0->0
R:89 S:2 M:55 T:2 N:130 0->0
R:89 S:2 M:55 T:2 N:131 0->0
R:89 S:2 M:55 T:2 N:132 0->0
R:89 S:2 M:55 T:2 N:133 0->0
R:89 S:2 M:55 T:2 N:134 0->0
R:89 S:2 M:55 T:2 N:135 0->0
R:89 S:2 M:55 T:2 N:136 0->0
R:89 S:2 M:55 T:2 N:137 0->0
R:89 S:2 M:55 T:2 N:138 0->0
R:89 S:2 M:55 T:2 N:139 0->0
R:89 S:2 M:55 T:2 N:140 0->0
R:89 S:2 M:55 T:2 N:141 0->0
R:89 S:2 M:55 T:2 N:142 0->0
R:89 S:2 M:55 T:2 N:143 0->0
R:89 S:2 M:55 T:2 N:144 0->0
R:89 S:2 M:55 T:2 N:145 0->0
R:89 S:2 M:55 T:2 N:146 0->0
R:89 S:2 M:55 T:2 N:147 0->0
R:89 S:2 M:55 T:2 N:148 0->0
R:89 S:2 M:55 T:2 N:149 0->0
R:89 S:2 M:55 T:2 N:150 0->0
R:89 S:2 M:55 T:2 N:151 0->0
R:89 S:2 M:55 T:2 N:152 0->0
R:89 S:2 M:55 T:2 N:153 0->0
R:89 S:2 M:55 T:2 N:154 0->0
R:89 S:2 M:55 T:2 N:155 0->0
R:89 S:2 M:55 T:2 N:156 0->0
R:89 S:2 M:55 T:2 N:157 0->0
R:89 S:2 M:55 T:2 N:158 0->0
R:89 S:2 M:55 T:2 N:159 0->0
R:89 S:2 M:55 T:2 N:160 0->0
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DI[  145]    OFF
 DI[  146]    OFF
 DI[  147]    OFF
 DI[  148]    OFF
 DI[  149]    OFF
 DI[  150]    OFF
 DI[  151]    OFF
 DI[  152]    OFF
 DI[  153]    OFF
 DI[  154]    OFF
 DI[  155]    OFF
 DI[  156]    OFF
 DI[  157]    OFF
 DI[  158]    OFF
 DI[  159]    OFF
 DI[  160]    OFF
R:89 S:2 M:55 T:1 N:33 0->0
R:89 S:2 M:55 T:1 N:34 0->0
R:89 S:2 M:55 T:1 N:35 0->0
R:89 S:2 M:55 T:1 N:36 0->0
R:89 S:2 M:55 T:1 N:37 0->0
R:89 S:2 M:55 T:1 N:38 0->0
R:89 S:2 M:55 T:1 N:39 0->0
R:89 S:2 M:55 T:1 N:40 0->0
 DI[  161]    OFF
 DI[  162]    OFF
 DI[  163]    OFF
 DI[  164]    OFF
 DI[  165]    OFF
 DI[  166]    OFF
 DI[  167]    OFF
 DI[  168]    OFF
 DI[  169]    OFF
 DI[  170]    OFF
 DI[  171]    OFF
 DI[  172]    OFF
 DI[  173]    OFF
 DI[  174]    OFF
 DI[  175]    OFF
 DI[  176]    OFF
 DI[  177]    OFF
 DI[  178]    OFF
 DI[  179]    OFF
 DI[  180]    OFF
 DI[  181]    OFF
 DI[  182]    OFF
 DI[  183]    OFF
 DI[  184]    OFF
R:89 S:2 M:55 T:1 N:65 0->0
R:89 S:2 M:55 T:1 N:66 0->0
R:89 S:2 M:55 T:1 N:67 0->0
R:89 S:2 M:55 T:1 N:68 0->0
R:89 S:2 M:55 T:1 N:69 0->0
R:89 S:2 M:55 T:1 N:70 0->0
R:89 S:2 M:55 T:1 N:71 0->0
R:89 S:2 M:55 T:1 N:72 0->0
R:89 S:2 M:55 T:1 N:73 0->0
R:89 S:2 M:55 T:1 N:74 0->0
R:89 S:2 M:55 T:1 N:75 0->0
R:89 S:2 M:55 T:1 N:76 0->0
R:89 S:2 M:55 T:1 N:77 0->0
R:89 S:2 M:55 T:1 N:78 0->0
R:89 S:2 M:55 T:1 N:79 0->0
R:89 S:2 M:55 T:1 N:80 0->0
Tick:   1013
TB:     753231726
28-AUG-21 20:36 :40
========================================
 DI[  313]    OFF
 DI[  314]    OFF
 DI[  315]    OFF
 DI[  316]    OFF
 DI[  317]    OFF
 DI[  318]    OFF
 DI[  319]    OFF
 DI[  320]    OFF
 DI[  321]    OFF
 DI[  322]    OFF
 DI[  323]    OFF
 DI[  324]    OFF
 DI[  325]    OFF
 DI[  326]    OFF
 DI[  327]    OFF
 DI[  328]    OFF
 GO[   11]    0
 GO[   12]    0
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    ON 
 DO[  141]    OFF
 DO[  142]    ON 
 DO[  143]    OFF
 DO[  144]    OFF
 DO[  145]    OFF
 DO[  146]    OFF
 DO[  147]    OFF
 DO[  148]    OFF
 DO[  149]    OFF
 DO[  150]    OFF
 DO[  151]    OFF
 DO[  152]    OFF
 DO[  153]    OFF
 DO[  154]    OFF
 DO[  155]    OFF
 DO[  156]    OFF
 DO[  157]    OFF
 DO[  158]    OFF
 DO[  159]    OFF
 DO[  160]    OFF
R:89 S:2 M:55 T:2 N:33 0->0
R:89 S:2 M:55 T:2 N:34 0->0
R:89 S:2 M:55 T:2 N:35 0->0
R:89 S:2 M:55 T:2 N:36 0->0
R:89 S:2 M:55 T:2 N:37 0->0
R:89 S:2 M:55 T:2 N:38 0->0
R:89 S:2 M:55 T:2 N:39 0->0
R:89 S:2 M:55 T:2 N:40 0->0
 DO[  161]    OFF
 DO[  162]    OFF
 DO[  163]    OFF
 DO[  164]    OFF
 DO[  165]    OFF
 DO[  166]    OFF
 DO[  167]    OFF
 DO[  168]    OFF
 DO[  169]    OFF
 DO[  170]    OFF
 DO[  171]    OFF
 DO[  172]    ON 
 DO[  173]    OFF
 DO[  174]    ON 
 DO[  175]    OFF
 DO[  176]    OFF
 DO[  177]    OFF
 DO[  178]    OFF
 DO[  179]    OFF
 DO[  180]    OFF
 DO[  181]    OFF
 DO[  182]    OFF
 DO[  183]    OFF
 DO[  184]    OFF
 DO[  185]    OFF
R:89 S:2 M:55 T:2 N:66 0->0
R:89 S:2 M:55 T:2 N:67 0->0
R:89 S:2 M:55 T:2 N:68 0->0
R:89 S:2 M:55 T:2 N:69 0->0
R:89 S:2 M:55 T:2 N:70 0->0
R:89 S:2 M:55 T:2 N:71 0->0
R:89 S:2 M:55 T:2 N:72 0->0
R:89 S:2 M:55 T:2 N:73 0->0
R:89 S:2 M:55 T:2 N:74 0->0
R:89 S:2 M:55 T:2 N:75 0->0
R:89 S:2 M:55 T:2 N:76 0->0
R:89 S:2 M:55 T:2 N:77 0->0
R:89 S:2 M:55 T:2 N:78 0->0
R:89 S:2 M:55 T:2 N:79 0->0
R:89 S:2 M:55 T:2 N:80 0->0
 DO[  193]    OFF
 DO[  194]    OFF
 DO[  195]    OFF
 DO[  196]    OFF
 DO[  197]    OFF
 DO[  198]    OFF
 DO[  199]    OFF
 DO[  200]    OFF
 DO[  201]    OFF
 DO[  202]    OFF
 DO[  203]    OFF
 DO[  204]    OFF
 DO[  205]    OFF
 DO[  206]    OFF
 DO[  207]    OFF
 DO[  208]    OFF
 DO[  209]    OFF
R:89 S:2 M:55 T:2 N:98 0->0
R:89 S:2 M:55 T:2 N:99 0->0
R:89 S:2 M:55 T:2 N:100 0->0
R:89 S:2 M:55 T:2 N:101 0->0
R:89 S:2 M:55 T:2 N:102 0->0
R:89 S:2 M:55 T:2 N:103 0->0
R:89 S:2 M:55 T:2 N:104 0->0
 DO[  329]    OFF
 DO[  330]    OFF
 DO[  331]    OFF
 DO[  332]    OFF
 DO[  333]    OFF
 DO[  334]    OFF
 DO[  335]    OFF
 DO[  336]    OFF
Tick:   1012
TB:     753230861
28-AUG-21 20:36 :40
========================================
 GI[    1]    0
 DI[   17]    OFF
 UI[   17]    OFF
 DI[   18]    OFF
 UI[   18]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  297]    OFF
 DI[  298]    OFF
 DI[  299]    OFF
 DI[  300]    OFF
 DI[  301]    OFF
 DI[  302]    OFF
 DI[  303]    OFF
 DI[  304]    OFF
 DI[  305]    OFF
 DI[  306]    OFF
 DI[  307]    OFF
 DI[  308]    OFF
 DI[  309]    OFF
 DI[  310]    OFF
 DI[  311]    OFF
 DI[  312]    OFF
Tick:   1011
TB:     753222520
28-AUG-21 20:36 :40
========================================
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  297]    OFF
 DO[  298]    OFF
 DO[  299]    OFF
 DO[  300]    OFF
 DO[  301]    OFF
 DO[  302]    OFF
 DO[  303]    OFF
 DO[  304]    OFF
 DO[  305]    OFF
 DO[  306]    OFF
 DO[  307]    OFF
 DO[  308]    OFF
 DO[  309]    OFF
 DO[  310]    OFF
 DO[  311]    OFF
 DO[  312]    OFF
 DO[  313]    OFF
 DO[  314]    OFF
 DO[  315]    OFF
 DO[  316]    OFF
 DO[  317]    OFF
 DO[  318]    OFF
 DO[  319]    OFF
 DO[  320]    OFF
 DO[  321]    OFF
 DO[  322]    OFF
 DO[  323]    OFF
 DO[  324]    OFF
 DO[  325]    OFF
 DO[  326]    OFF
 DO[  327]    OFF
 DO[  328]    OFF
 DI[    1]    ON 
 UI[    1]    ON 
 DI[    2]    ON 
 UI[    2]    ON 
 DI[    3]    ON 
 UI[    3]    ON 
 DI[    4]    OFF
 UI[    4]    OFF
 DI[    5]    OFF
 UI[    5]    OFF
 DI[    6]    OFF
 UI[    6]    OFF
 DI[    7]    OFF
 UI[    7]    OFF
 DI[    8]    ON 
 UI[    8]    ON 
 DI[    9]    OFF
 UI[    9]    OFF
 DI[   10]    OFF
 UI[   10]    OFF
 DI[   11]    OFF
 UI[   11]    OFF
 DI[   12]    OFF
 UI[   12]    OFF
 DI[   13]    OFF
 UI[   13]    OFF
 DI[   14]    OFF
 UI[   14]    OFF
 DI[   15]    OFF
 UI[   15]    OFF
 DI[   16]    OFF
 UI[   16]    OFF
Tick:   1010
TB:     753158884
28-AUG-21 20:36 :40
========================================
 GO[    4]    0
 GO[    5]    0
 DO[  481]    OFF
 DO[  482]    OFF
 DO[  483]    OFF
 DO[  484]    OFF
 DO[  485]    OFF
 DO[  486]    OFF
 DO[  487]    OFF
 DO[  488]    OFF
 DO[  489]    OFF
 DO[  490]    OFF
 DO[  491]    OFF
 DO[  492]    OFF
 DO[  493]    OFF
 DO[  494]    OFF
 DO[  495]    OFF
 DO[  496]    OFF
 DO[  497]    OFF
 DO[  498]    OFF
 DO[  499]    OFF
 DO[  500]    OFF
 DO[  501]    OFF
 DO[  502]    OFF
 DO[  503]    OFF
 DO[  504]    OFF
 DO[  505]    OFF
 DO[  506]    OFF
 DO[  507]    OFF
 DO[  508]    OFF
 DO[  509]    OFF
 DO[  510]    OFF
 DO[  511]    OFF
 DO[  512]    OFF
R:88 S:1 M:53 T:2 N:33 0->0
R:88 S:1 M:53 T:2 N:34 0->0
R:88 S:1 M:53 T:2 N:35 0->0
R:88 S:1 M:53 T:2 N:36 0->0
R:88 S:1 M:53 T:2 N:37 0->0
R:88 S:1 M:53 T:2 N:38 0->0
R:88 S:1 M:53 T:2 N:39 0->0
R:88 S:1 M:53 T:2 N:40 0->0
 GI[    4]    0
 GI[    5]    0
 DI[  481]    OFF
 DI[  482]    OFF
 DI[  483]    OFF
 DI[  484]    OFF
 DI[  485]    OFF
 DI[  486]    OFF
 DI[  487]    OFF
 DI[  488]    OFF
 DI[  489]    OFF
 DI[  490]    OFF
 DI[  491]    OFF
 DI[  492]    OFF
 DI[  493]    OFF
 DI[  494]    OFF
 DI[  495]    OFF
 DI[  496]    OFF
 DI[  497]    OFF
 DI[  498]    OFF
 DI[  499]    OFF
 DI[  500]    OFF
 DI[  501]    OFF
 DI[  502]    OFF
 DI[  503]    OFF
 DI[  504]    OFF
 DI[  505]    OFF
 DI[  506]    OFF
 DI[  507]    OFF
 DI[  508]    OFF
 DI[  509]    OFF
 DI[  510]    OFF
 DI[  511]    OFF
 DI[  512]    OFF
R:88 S:1 M:53 T:1 N:33 0->0
R:88 S:1 M:53 T:1 N:34 0->0
R:88 S:1 M:53 T:1 N:35 0->0
R:88 S:1 M:53 T:1 N:36 0->0
R:88 S:1 M:53 T:1 N:37 0->0
R:88 S:1 M:53 T:1 N:38 0->0
R:88 S:1 M:53 T:1 N:39 0->0
R:88 S:1 M:53 T:1 N:40 0->0
 DO[    1]    OFF
 UO[    1]    OFF
 DO[    2]    OFF
 UO[    2]    OFF
 DO[    3]    OFF
 UO[    3]    OFF
 DO[    4]    OFF
 UO[    4]    OFF
 DO[    5]    OFF
 UO[    5]    OFF
 DO[    6]    OFF
 UO[    6]    OFF
 DO[    7]    OFF
 UO[    7]    OFF
 DO[    8]    OFF
 UO[    8]    OFF
 DO[    9]    OFF
 UO[    9]    OFF
 DO[   10]    OFF
 UO[   10]    OFF
 DO[   11]    OFF
 UO[   11]    OFF
 DO[   12]    OFF
 UO[   12]    OFF
 DO[   13]    OFF
 UO[   13]    OFF
 DO[   14]    OFF
 UO[   14]    OFF
 DO[   15]    OFF
 UO[   15]    OFF
 DO[   16]    OFF
 UO[   16]    OFF
 DO[   17]    OFF
 UO[   17]    OFF
 DO[   18]    OFF
 UO[   18]    OFF
 DO[   19]    OFF
 UO[   19]    OFF
 DO[   20]    OFF
 UO[   20]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
Tick:   1009
TB:     753158091
28-AUG-21 20:36 :40
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    ON 
 SI[    9]    ON 
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
SPI[    1]    OFF
SPI[    2]    OFF
SPI[    3]    OFF
SPI[    4]    OFF
SPI[    5]    OFF
SPI[    6]    OFF
SPI[    7]    OFF
SPI[    8]    OFF
SPI[    9]    OFF
SPI[   10]    OFF
SPI[   11]    OFF
SPI[   12]    OFF
SPI[   13]    OFF
SPI[   14]    OFF
SPI[   15]    OFF
SPI[   16]    OFF
SPI[   17]    OFF
SPI[   18]    OFF
SPI[   19]    OFF
SPI[   20]    OFF
SPI[   21]    OFF
SPI[   22]    OFF
SPI[   23]    OFF
SPI[   24]    OFF
SPI[   25]    OFF
SPI[   26]    OFF
SPI[   27]    OFF
SPI[   28]    OFF
SPI[   29]    OFF
SPI[   30]    OFF
SPI[   31]    OFF
SPI[   32]    OFF
SPI[   33]    OFF
SPI[   34]    OFF
SPI[   35]    OFF
SPI[   36]    OFF
SPI[   37]    OFF
SPI[   38]    OFF
SPI[   39]    OFF
SPI[   40]    OFF
SPI[   41]    OFF
SPI[   42]    OFF
SPI[   43]    OFF
SPI[   44]    OFF
SPI[   45]    OFF
SPI[   46]    OFF
SPI[   47]    OFF
SPI[   48]    OFF
SPI[   49]    OFF
SPI[   50]    OFF
SPI[   51]    OFF
SPI[   52]    OFF
SPI[   53]    OFF
SPI[   54]    OFF
SPI[   55]    OFF
SPI[   56]    OFF
SPI[   57]    OFF
SPI[   58]    OFF
SPI[   59]    OFF
SPI[   60]    OFF
SPI[   61]    OFF
SPI[   62]    OFF
SPI[   63]    OFF
SPI[   64]    OFF
SSI[    1]    OFF
SSI[    2]    OFF
SSI[    3]    OFF
SSI[    4]    OFF
SSI[    5]    OFF
SSI[    6]    OFF
SSI[    7]    OFF
SSI[    8]    OFF
SSI[    9]    OFF
SSI[   10]    OFF
SSI[   11]    OFF
Tick:   1008
TB:     753157152
28-AUG-21 20:36 :40
