ERRMOT.LS      Robot Name ROBOT 28-AUG-21 20:35:46  

1" 28-AUG-21 20:35:08 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 28-AUG-21 20:34:52 " SRVO-233 TP OFF in T1,T2                          " " SERVO                         00110110" 
3" 28-AUG-21 20:34:50 " SRVO-302 Set Hand broken to ENABLE                " " SERVO                         00110110" 
4" 28-AUG-21 20:34:50 " SRVO-302 Set Hand broken to ENABLE                " " SERVO                         00110110" 
