LOGBOOK.LS     Robot Name ROBOT 28-AUG-21 20:46:32  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'LOADFRAME.LS' is saved           
28-AUG-21 20:46 :32
========================================
FILE 'LOAD.LS' is saved                
28-AUG-21 20:46 :32
========================================
FILE 'INIT_APPCH_OFST.LS' is saved     
28-AUG-21 20:46 :32
========================================
FILE 'INIT.LS' is saved                
28-AUG-21 20:46 :32
========================================
FILE 'INCR_POSITION.LS' is saved       
28-AUG-21 20:46 :32
========================================
FILE 'HIST.LS' is saved                
28-AUG-21 20:46 :32
========================================
FILE 'HEAVYPAYLOAD.LS' is saved        
28-AUG-21 20:46 :32
========================================
FILE 'GRIP_2_OPEN.LS' is saved         
28-AUG-21 20:46 :32
========================================
FILE 'GRIP_2_CLOSE.LS' is saved        
28-AUG-21 20:46 :32
========================================
FILE 'GRIP_1_OPEN.LS' is saved         
28-AUG-21 20:46 :32
========================================
FILE 'GRIP_1_CLOSE.LS' is saved        
28-AUG-21 20:46 :32
========================================
FILE 'GRIPPER_OPEN.LS' is saved        
28-AUG-21 20:46 :32
========================================
FILE 'GRIPPER_CLOSE.LS' is saved       
28-AUG-21 20:46 :32
========================================
FILE 'GRID.LS' is saved                
28-AUG-21 20:46 :32
========================================
FILE 'GO_SAFE_PERCH.LS' is saved       
28-AUG-21 20:46 :32
========================================
FILE 'GO_PERCH.LS' is saved            
28-AUG-21 20:46 :32
========================================
FILE 'GO_MID_PT.LS' is saved           
28-AUG-21 20:46 :32
========================================
FILE 'GO_HOME.LS' is saved             
28-AUG-21 20:46 :32
========================================
FILE 'GOPERCHERR.LS' is saved          
28-AUG-21 20:46 :32
========================================
FILE 'GOMIDPTERR.LS' is saved          
28-AUG-21 20:46 :32
========================================
FILE 'GET_ROW_COL.LS' is saved         
28-AUG-21 20:46 :32
========================================
FILE 'GET_PL_APP_PT.LS' is saved       
28-AUG-21 20:46 :32
========================================
FILE 'GET_PLACE_ROW_COL.LS' is saved   
28-AUG-21 20:46 :32
========================================
FILE 'GET_PLACE_PT.LS' is saved        
28-AUG-21 20:46 :32
========================================
FILE 'GET_PICK_PT.LS' is saved         
28-AUG-21 20:46 :32
========================================
FILE 'GET_PART.LS' is saved            
28-AUG-21 20:46 :32
========================================
FILE 'GET_APPCH_PT.LS' is saved        
28-AUG-21 20:46 :32
========================================
FILE 'GETDATA.LS' is saved             
28-AUG-21 20:46 :32
========================================
FILE 'ERRSYS.LS' is saved              
28-AUG-21 20:46 :32
========================================
FILE 'ERRPWD.LS' is saved              
28-AUG-21 20:46 :32
========================================
FILE 'ERROR.LS' is saved               
28-AUG-21 20:46 :32
========================================
FILE 'ERRMOT.LS' is saved              
28-AUG-21 20:46 :32
========================================
FILE 'ERRHIST.LS' is saved             
28-AUG-21 20:46 :30
========================================
FILE 'ERREXT.LS' is saved              
28-AUG-21 20:46 :30
========================================
FILE 'ERRCURR.LS' is saved             
28-AUG-21 20:46 :30
========================================
FILE 'ERRCOMM.LS' is saved             
28-AUG-21 20:46 :30
========================================
FILE 'ERRAPP.LS' is saved              
28-AUG-21 20:46 :30
========================================
FILE 'ERRALL.LS' is saved              
28-AUG-21 20:46 :30
========================================
FILE 'ERRACT.LS' is saved              
28-AUG-21 20:46 :30
========================================
FILE 'EMPTYPAYLOAD.LS' is saved        
28-AUG-21 20:46 :30
========================================
FILE 'CLOSE_CHUCK.LS' is saved         
28-AUG-21 20:46 :30
========================================
FILE 'CHK_PART_PRES.LS' is saved       
28-AUG-21 20:46 :30
========================================
FILE 'CHK_PALLET_POSITION.LS' is saved 
28-AUG-21 20:46 :30
========================================
FILE 'CHK_GRIP_STATUS.LS' is saved     
28-AUG-21 20:46 :30
========================================
FILE 'CHK_CHUCK_STATUS.LS' is saved    
28-AUG-21 20:46 :30
========================================
FILE 'CHECK_GRIP_OPER.LS' is saved     
28-AUG-21 20:46 :30
========================================
FILE 'CHECK_CHUCK_OPER.LS' is saved    
28-AUG-21 20:46 :30
========================================
FILE 'BS.LS' is saved                  
28-AUG-21 20:46 :30
========================================
FILE 'BG001.LS' is saved               
28-AUG-21 20:46 :30
========================================
FILE '-BCKEDT-.LS' is saved            
28-AUG-21 20:46 :30
========================================
FILE '-BCKED9-.LS' is saved            
28-AUG-21 20:46 :30
========================================
FILE '-BCKED8-.LS' is saved            
28-AUG-21 20:46 :30
========================================
F4(  YES   ) is pressed                
28-AUG-21 20:46 :30
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [UD1:\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
Overwrite?                                                                      
                          YES      NO                                           
========================================
F1(DO_COPY ) is pressed                
28-AUG-21 20:46 :30
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [UD1:\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
                                                                                
DO_COPY                 [CHOICE] CANCEL                                         
========================================
'USB Disk (UD1:)' is selected          
28-AUG-21 20:46 :28
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [***\\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
28-AUG-21 20:46 :26
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\COPY\\\\\\\\\\\\\\\\\\\\\       0 1                                        
From Path:                         1/3                                          
 MD:\                                                                           
From Filename:                                                                  
 *.LS                                                                           
                                                                                
To Device:                 [***\\\\\]                                           
To Directory:                                                                   
 \                                                                              
To Filename:                                                                    
 *.LS                                                                           
                                                                                
                                                                                
                                                                                
DO_COPY                 [CHOICE] CANCEL                                         
========================================
F2(  COPY  ) is pressed                
28-AUG-21 20:46 :24
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
MD:\*.*                           5/32                                          
   1 *       *   (all files)                                                    
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
\\\5\*\\\\\\\LS\\(all\KAREL\listings)\\\                                        
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
                                                                                
 DELETE   COPY  DISPLAY [INSTAL][VIEW ]>                                        
========================================
'Mem Device (MD:)' is selected         
28-AUG-21 20:46 :18
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
FR:\*.*                           1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
'Set Device' is selected               
28-AUG-21 20:46 :16
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
FR:\*.*                           1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP]|UTIL |>                                        
========================================
F5([UTIL ]>) is pressed                
28-AUG-21 20:46 :14
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
FILE\\\\\\\\\\\\\\\\\\\\\\\\\\       0 1                                        
FR:\*.*                           1/32                                          
\\\1\*\\\\\\\*\\\(all\files)\\\\\\\\\\\\                                        
   2 *       KL  (all KAREL source)                                             
   3 *       CF  (all command files)                                            
   4 *       TX  (all text files)                                               
   5 *       LS  (all KAREL listings)                                           
   6 *       DT  (all KAREL data files)                                         
   7 *       PC  (all KAREL p-code)                                             
   8 *       TP  (all TP programs)                                              
   9 *       MN  (all MN programs)                                              
  10 *       VR  (all variable files)                                           
  11 *       SV  (all system files)                                             
Press DIR to generate directory                                                 
[ TYPE ] [ DIR ]  LOAD  [BACKUP][UTIL ]>                                        
========================================
Menu changed 'FILE'                    
28-AUG-21 20:46 :10
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:46 :00
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:46 :00
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:46 :00
========================================
SRVO-003 Deadman switch released       
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:46 :00
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:46 :00
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:46 :00
========================================
SYST-045 TP enabled in AUTO mode       
                                       
                                       
STOP.G                        00100110 
28-AUG-21 20:45 :58
========================================
Focus changed to ''                    
28-AUG-21 20:45 :58
========================================
FILE 'T_NOVICE.LS' is saved            
28-AUG-21 20:45 :58
========================================
FILE 'T_TUTORIAL.LS' is saved          
28-AUG-21 20:45 :58
========================================
FILE 'T_VACOFF.LS' is saved            
28-AUG-21 20:45 :58
========================================
FILE 'T_VACON.LS' is saved             
28-AUG-21 20:45 :58
========================================
FILE 'T_FINCLOS.LS' is saved           
28-AUG-21 20:45 :58
========================================
FILE 'T_FINOPEN.LS' is saved           
28-AUG-21 20:45 :58
========================================
FILE 'T_RAWCLOS.LS' is saved           
28-AUG-21 20:45 :58
========================================
FILE 'T_RAWOPEN.LS' is saved           
28-AUG-21 20:45 :58
========================================
FILE 'T_GRIPCLOS.LS' is saved          
28-AUG-21 20:45 :58
========================================
FILE 'T_GRIPOPEN.LS' is saved          
28-AUG-21 20:45 :58
========================================
FILE 'T_PICKPLACE.LS' is saved         
28-AUG-21 20:45 :58
========================================
FILE 'T_MOVE_ROBOT.LS' is saved        
28-AUG-21 20:45 :58
========================================
FILE 'TEMPLATES.LS' is saved           
28-AUG-21 20:45 :58
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:39 :32
========================================
Override 100%                          
28-AUG-21 20:39 :32
========================================
Menu changed 'UTILITIES Hints'         
28-AUG-21 20:39 :30
========================================
Override 10%                           
28-AUG-21 20:39 :30
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
28-AUG-21 20:39 :30
========================================
R E S E T                              
                                       
                              00000000 
28-AUG-21 20:39 :30
========================================
Cold start                             
28-AUG-21 20:39 :26
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
26-AUG-21 17:28 :20
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
26-AUG-21 17:28 :18
========================================
R E S E T                              
                                       
                              00000000 
26-AUG-21 17:25 :38
========================================
FILE '_HOME.TP' is saved               
26-AUG-21 17:25 :36
========================================
FILE 'ZDLOG.DG' is saved               
26-AUG-21 17:25 :36
========================================
FILE 'WAIT_ON_CNC.TP' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'VTRNDIAG.LS' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'VIMGDIAG.ZIP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'VDEVDIAG.DAT' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'VCMRINIT.VR' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'VARCHG.XML' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'USR_WORK.VR' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'UPDTLOG.LS' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'UPDATES.DAT' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'UNLOAD.TP' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'TPEINS.XML' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'TPACCN.DG' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'TESTA.TP' is saved               
26-AUG-21 17:25 :36
========================================
FILE 'SYSVARS.SV' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'SYSUIF.SV' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'SYSSERVO.SV' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'SYSPASS.SV' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'SYSMAST.SV' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'SYSMACRO.SV' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'SYSHOST.SV' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'SYSFSAC.SV' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'SYSFRAME.SV' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'SWIUPDT.VR' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'SV_ADJST.TP' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'SUMMARY.DG' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'STRREG.VR' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'SHADOW.DG' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'SET_PICK_OFST.TP' is saved       
26-AUG-21 17:25 :36
========================================
FILE 'SENDSYSV.TP' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'SENDEVNT.TP' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'SENDDATA.TP' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'SECLOG.DG' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'REQMENU.TP' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'RCMSGLIB.DG' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'RCMERR.DG' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'RCMCFG.XML' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'PSRBWLD.CM' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'PR_ONLN.VR' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'PR_OFFLN.VR' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'PROFIBUS.SV' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'POSREG.VR' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'PNS0002.TP' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'PNS0001.TP' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'PLCFMOV.VR' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'PLCFCAL.VR' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'PLACE_PICK.TP' is saved          
26-AUG-21 17:25 :36
========================================
FILE 'PLACE_PART.TP' is saved          
26-AUG-21 17:25 :36
========================================
FILE 'PLACE.TP' is saved               
26-AUG-21 17:25 :36
========================================
FILE 'PICKFRAME.TP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'PICK.TP' is saved                
26-AUG-21 17:25 :36
========================================
FILE 'PALREG.VR' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'ORDERFIL.DAT' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'OPENCHUCK.TP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'NUMREG.VR' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'NOTIFY.DG' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'NEW.TP' is saved                 
26-AUG-21 17:25 :36
========================================
FILE 'MOVE_SAFE.TP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'MOVEHOME.TP' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'MOVE2PICK.TP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'MOVE2PERCHPT.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'MOVE2PERCH90.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'MOVE2MAINT.TP' is saved          
26-AUG-21 17:25 :36
========================================
FILE 'MOVE2LOAD.TP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'MOVE2APPRCH.TP' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'MIXLOGIC.SV' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'MEMCHECK.DG' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'MAIN.TP' is saved                
26-AUG-21 17:25 :36
========================================
FILE 'LR7L.DT' is saved                
26-AUG-21 17:25 :36
========================================
FILE 'LOGBOOK.LS' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'LOADFRAME.TP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'LOAD.TP' is saved                
26-AUG-21 17:25 :36
========================================
FILE 'IRC_STLABEL.VR' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'IRC_STATUS.VR' is saved          
26-AUG-21 17:25 :36
========================================
FILE 'IRC_MSG.VR' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'IRC_COUNTER.VR' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'IPKDMP.ZIP' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'IOSTATUS.CM' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'INIT_APPCH_OFST.TP' is saved     
26-AUG-21 17:25 :36
========================================
FILE 'INIT.TP' is saved                
26-AUG-21 17:25 :36
========================================
FILE 'INCR_POSITION.TP' is saved       
26-AUG-21 17:25 :36
========================================
FILE 'HTTPKCL.VR' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'HTCOLREC.VR' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'HIST.LS' is saved                
26-AUG-21 17:25 :36
========================================
FILE 'HEAVYPAYLOAD.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'HAPTIC.SV' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'GRIP_2_OPEN.TP' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'GRIP_2_CLOSE.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'GRIP_1_OPEN.TP' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'GRIP_1_CLOSE.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'GRIPPER_OPEN.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'GRIPPER_CLOSE.TP' is saved       
26-AUG-21 17:25 :36
========================================
FILE 'GRID.TP' is saved                
26-AUG-21 17:25 :36
========================================
FILE 'GO_SAFE_PERCH.TP' is saved       
26-AUG-21 17:25 :36
========================================
FILE 'GO_PERCH.TP' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'GO_MID_PT.TP' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'GO_HOME.TP' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'GOPERCHERR.TP' is saved          
26-AUG-21 17:25 :36
========================================
FILE 'GOMIDPTERR.TP' is saved          
26-AUG-21 17:25 :36
========================================
FILE 'GIGELOG.DG' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'GET_ROW_COL.TP' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'GET_PL_APP_PT.TP' is saved       
26-AUG-21 17:25 :36
========================================
FILE 'GET_PLACE_ROW_COL.TP' is saved   
26-AUG-21 17:25 :36
========================================
FILE 'GET_PLACE_PT.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'GET_PICK_PT.TP' is saved         
26-AUG-21 17:25 :36
========================================
FILE 'GET_PART.TP' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'GET_APPCH_PT.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'GETDATA.TP' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'GEMDATA.VR' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'FTPLOG.DG' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'FRAMEVAR.VR' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'FLEXUIF.XML' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'FLEXEVENT.DG' is saved           
26-AUG-21 17:25 :36
========================================
FILE 'ETHERNET.DG' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'ERRSYS.LS' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'ERRPWD.LS' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'ERROR.TP' is saved               
26-AUG-21 17:25 :36
========================================
FILE 'ERRMOT.LS' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'ERRHIST.LS' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'ERREXT.LS' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'ERRCURR.LS' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'ERRCOMM.LS' is saved             
26-AUG-21 17:25 :36
========================================
FILE 'ERRAPP.LS' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'ERRALL.LS' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'ERRACT.LS' is saved              
26-AUG-21 17:25 :36
========================================
FILE 'EMPTYPAYLOAD.TP' is saved        
26-AUG-21 17:25 :36
========================================
FILE 'EMAIL.DG' is saved               
26-AUG-21 17:25 :36
========================================
FILE 'DIOCFGSV.IO' is saved            
26-AUG-21 17:25 :36
========================================
FILE 'DF_MOTN0.DF' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DF_LOGI6.DF' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DF_LOGI5.DF' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DF_LOGI4.DF' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DF_LOGI3.DF' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DF_LOGI2.DF' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DF_LOGI1.DF' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DCSVRFY.DG' is saved             
26-AUG-21 17:25 :34
========================================
FILE 'DCSDIFF.DG' is saved             
26-AUG-21 17:25 :34
========================================
FILE 'DCSCHG03.DG' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DCSCHG02.DG' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'DCSCHG01.DG' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'CONSLOG.DG' is saved             
26-AUG-21 17:25 :34
========================================
FILE 'COMSET.VR' is saved              
26-AUG-21 17:25 :34
========================================
FILE 'CLOSE_CHUCK.TP' is saved         
26-AUG-21 17:25 :34
========================================
FILE 'CHK_PART_PRES.TP' is saved       
26-AUG-21 17:25 :34
========================================
FILE 'CHK_PALLET_POSITION.TP' is saved 
26-AUG-21 17:25 :34
========================================
FILE 'CHK_GRIP_STATUS.TP' is saved     
26-AUG-21 17:25 :34
========================================
FILE 'CHK_CHUCK_STATUS.TP' is saved    
26-AUG-21 17:25 :34
========================================
FILE 'CHECK_GRIP_OPER.TP' is saved     
26-AUG-21 17:25 :34
========================================
FILE 'CHECK_CHUCK_OPER.TP' is saved    
26-AUG-21 17:25 :34
========================================
FILE 'CELLIO.SV' is saved              
26-AUG-21 17:25 :34
========================================
FILE 'BS.TP' is saved                  
26-AUG-21 17:25 :34
========================================
FILE 'BICSETUP.VR' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'BG001.TP' is saved               
26-AUG-21 17:25 :34
========================================
FILE 'BACKDATE.DT' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'ATERRJOB.VR' is saved            
26-AUG-21 17:25 :34
========================================
FILE 'AAVMMAIN.VR' is saved            
26-AUG-21 17:25 :34
========================================
FILE '-BCKEDT-.TP' is saved            
26-AUG-21 17:25 :34
========================================
FILE '-BCKED9-.TP' is saved            
26-AUG-21 17:25 :34
========================================
FILE '-BCKED8-.TP' is saved            
26-AUG-21 17:25 :34
========================================
FILE '-BCKED2-.TP' is saved            
26-AUG-21 17:25 :34
========================================
R E S E T                              
                                       
                              00000000 
26-AUG-21 16:55 :34
========================================
FILE '_HOME.TP' is saved               
26-AUG-21 16:55 :34
========================================
FILE 'ZDLOG.DG' is saved               
26-AUG-21 16:55 :34
========================================
FILE 'WAIT_ON_CNC.TP' is saved         
26-AUG-21 16:55 :34
========================================
FILE 'VTRNDIAG.LS' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'VIMGDIAG.ZIP' is saved           
26-AUG-21 16:55 :34
========================================
FILE 'VDEVDIAG.DAT' is saved           
26-AUG-21 16:55 :34
========================================
FILE 'VCMRINIT.VR' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'VARCHG.XML' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'USR_WORK.VR' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'UPDTLOG.LS' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'UPDATES.DAT' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'UNLOAD.TP' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'TPEINS.XML' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'TPACCN.DG' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'TESTA.TP' is saved               
26-AUG-21 16:55 :34
========================================
FILE 'SYSVARS.SV' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'SYSUIF.SV' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'SYSSERVO.SV' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'SYSPASS.SV' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'SYSMAST.SV' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'SYSMACRO.SV' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'SYSHOST.SV' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'SYSFSAC.SV' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'SYSFRAME.SV' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'SWIUPDT.VR' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'SV_ADJST.TP' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'SUMMARY.DG' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'STRREG.VR' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'SHADOW.DG' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'SET_PICK_OFST.TP' is saved       
26-AUG-21 16:55 :34
========================================
FILE 'SENDSYSV.TP' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'SENDEVNT.TP' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'SENDDATA.TP' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'SECLOG.DG' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'REQMENU.TP' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'RCMSGLIB.DG' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'RCMERR.DG' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'RCMCFG.XML' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'PSRBWLD.CM' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'PR_ONLN.VR' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'PR_OFFLN.VR' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'PROFIBUS.SV' is saved            
26-AUG-21 16:55 :34
========================================
FILE 'POSREG.VR' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'PNS0002.TP' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'PNS0001.TP' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'PLCFMOV.VR' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'PLCFCAL.VR' is saved             
26-AUG-21 16:55 :34
========================================
FILE 'PLACE_PICK.TP' is saved          
26-AUG-21 16:55 :34
========================================
FILE 'PLACE_PART.TP' is saved          
26-AUG-21 16:55 :34
========================================
FILE 'PLACE.TP' is saved               
26-AUG-21 16:55 :34
========================================
FILE 'PICKFRAME.TP' is saved           
26-AUG-21 16:55 :34
========================================
FILE 'PICK.TP' is saved                
26-AUG-21 16:55 :34
========================================
FILE 'PALREG.VR' is saved              
26-AUG-21 16:55 :34
========================================
FILE 'ORDERFIL.DAT' is saved           
26-AUG-21 16:55 :34
========================================
FILE 'OPENCHUCK.TP' is saved           
26-AUG-21 16:55 :34
========================================
FILE 'NUMREG.VR' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'NOTIFY.DG' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'NEW.TP' is saved                 
26-AUG-21 16:55 :32
========================================
FILE 'MOVE_SAFE.TP' is saved           
26-AUG-21 16:55 :32
========================================
FILE 'MOVEHOME.TP' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'MOVE2PICK.TP' is saved           
26-AUG-21 16:55 :32
========================================
FILE 'MOVE2PERCHPT.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'MOVE2PERCH90.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'MOVE2MAINT.TP' is saved          
26-AUG-21 16:55 :32
========================================
FILE 'MOVE2LOAD.TP' is saved           
26-AUG-21 16:55 :32
========================================
FILE 'MOVE2APPRCH.TP' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'MIXLOGIC.SV' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'MEMCHECK.DG' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'MAIN.TP' is saved                
26-AUG-21 16:55 :32
========================================
FILE 'LR7L.DT' is saved                
26-AUG-21 16:55 :32
========================================
FILE 'LOGBOOK.LS' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'LOADFRAME.TP' is saved           
26-AUG-21 16:55 :32
========================================
FILE 'LOAD.TP' is saved                
26-AUG-21 16:55 :32
========================================
FILE 'IRC_STLABEL.VR' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'IRC_STATUS.VR' is saved          
26-AUG-21 16:55 :32
========================================
FILE 'IRC_MSG.VR' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'IRC_COUNTER.VR' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'IPKDMP.ZIP' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'IOSTATUS.CM' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'INIT_APPCH_OFST.TP' is saved     
26-AUG-21 16:55 :32
========================================
FILE 'INIT.TP' is saved                
26-AUG-21 16:55 :32
========================================
FILE 'INCR_POSITION.TP' is saved       
26-AUG-21 16:55 :32
========================================
FILE 'HTTPKCL.VR' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'HTCOLREC.VR' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'HIST.LS' is saved                
26-AUG-21 16:55 :32
========================================
FILE 'HEAVYPAYLOAD.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'HAPTIC.SV' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'GRIP_2_OPEN.TP' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'GRIP_2_CLOSE.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'GRIP_1_OPEN.TP' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'GRIP_1_CLOSE.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'GRIPPER_OPEN.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'GRIPPER_CLOSE.TP' is saved       
26-AUG-21 16:55 :32
========================================
FILE 'GRID.TP' is saved                
26-AUG-21 16:55 :32
========================================
FILE 'GO_SAFE_PERCH.TP' is saved       
26-AUG-21 16:55 :32
========================================
FILE 'GO_PERCH.TP' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'GO_MID_PT.TP' is saved           
26-AUG-21 16:55 :32
========================================
FILE 'GO_HOME.TP' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'GOPERCHERR.TP' is saved          
26-AUG-21 16:55 :32
========================================
FILE 'GOMIDPTERR.TP' is saved          
26-AUG-21 16:55 :32
========================================
FILE 'GIGELOG.DG' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'GET_ROW_COL.TP' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'GET_PL_APP_PT.TP' is saved       
26-AUG-21 16:55 :32
========================================
FILE 'GET_PLACE_ROW_COL.TP' is saved   
26-AUG-21 16:55 :32
========================================
FILE 'GET_PLACE_PT.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'GET_PICK_PT.TP' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'GET_PART.TP' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'GET_APPCH_PT.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'GETDATA.TP' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'GEMDATA.VR' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'FTPLOG.DG' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'FRAMEVAR.VR' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'FLEXUIF.XML' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'FLEXEVENT.DG' is saved           
26-AUG-21 16:55 :32
========================================
FILE 'ETHERNET.DG' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'ERRSYS.LS' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'ERRPWD.LS' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'ERROR.TP' is saved               
26-AUG-21 16:55 :32
========================================
FILE 'ERRMOT.LS' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'ERRHIST.LS' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'ERREXT.LS' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'ERRCURR.LS' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'ERRCOMM.LS' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'ERRAPP.LS' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'ERRALL.LS' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'ERRACT.LS' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'EMPTYPAYLOAD.TP' is saved        
26-AUG-21 16:55 :32
========================================
FILE 'EMAIL.DG' is saved               
26-AUG-21 16:55 :32
========================================
FILE 'DIOCFGSV.IO' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DF_MOTN0.DF' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DF_LOGI6.DF' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DF_LOGI5.DF' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DF_LOGI4.DF' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DF_LOGI3.DF' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DF_LOGI2.DF' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DF_LOGI1.DF' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DCSVRFY.DG' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'DCSDIFF.DG' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'DCSCHG03.DG' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DCSCHG02.DG' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'DCSCHG01.DG' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'CONSLOG.DG' is saved             
26-AUG-21 16:55 :32
========================================
FILE 'COMSET.VR' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'CLOSE_CHUCK.TP' is saved         
26-AUG-21 16:55 :32
========================================
FILE 'CHK_PART_PRES.TP' is saved       
26-AUG-21 16:55 :32
========================================
FILE 'CHK_PALLET_POSITION.TP' is saved 
26-AUG-21 16:55 :32
========================================
FILE 'CHK_GRIP_STATUS.TP' is saved     
26-AUG-21 16:55 :32
========================================
FILE 'CHK_CHUCK_STATUS.TP' is saved    
26-AUG-21 16:55 :32
========================================
FILE 'CHECK_GRIP_OPER.TP' is saved     
26-AUG-21 16:55 :32
========================================
FILE 'CHECK_CHUCK_OPER.TP' is saved    
26-AUG-21 16:55 :32
========================================
FILE 'CELLIO.SV' is saved              
26-AUG-21 16:55 :32
========================================
FILE 'BS.TP' is saved                  
26-AUG-21 16:55 :32
========================================
FILE 'BICSETUP.VR' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'BG001.TP' is saved               
26-AUG-21 16:55 :32
========================================
FILE 'BACKDATE.DT' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'ATERRJOB.VR' is saved            
26-AUG-21 16:55 :32
========================================
FILE 'AAVMMAIN.VR' is saved            
26-AUG-21 16:55 :32
========================================
FILE '-BCKEDT-.TP' is saved            
26-AUG-21 16:55 :32
========================================
FILE '-BCKED9-.TP' is saved            
26-AUG-21 16:55 :32
========================================
FILE '-BCKED8-.TP' is saved            
26-AUG-21 16:55 :32
========================================
FILE '-BCKED2-.TP' is saved            
26-AUG-21 16:55 :32
========================================
R E S E T                              
                                       
                              00000000 
26-AUG-21 16:25 :30
========================================
FILE '_HOME.TP' is saved               
26-AUG-21 16:25 :30
========================================
FILE 'ZDLOG.DG' is saved               
26-AUG-21 16:25 :30
========================================
FILE 'WAIT_ON_CNC.TP' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'VTRNDIAG.LS' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'VIMGDIAG.ZIP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'VDEVDIAG.DAT' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'VCMRINIT.VR' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'VARCHG.XML' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'USR_WORK.VR' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'UPDTLOG.LS' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'UPDATES.DAT' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'UNLOAD.TP' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'TPEINS.XML' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'TPACCN.DG' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'TESTA.TP' is saved               
26-AUG-21 16:25 :30
========================================
FILE 'SYSVARS.SV' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'SYSUIF.SV' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'SYSSERVO.SV' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'SYSPASS.SV' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'SYSMAST.SV' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'SYSMACRO.SV' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'SYSHOST.SV' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'SYSFSAC.SV' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'SYSFRAME.SV' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'SWIUPDT.VR' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'SV_ADJST.TP' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'SUMMARY.DG' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'STRREG.VR' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'SHADOW.DG' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'SET_PICK_OFST.TP' is saved       
26-AUG-21 16:25 :30
========================================
FILE 'SENDSYSV.TP' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'SENDEVNT.TP' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'SENDDATA.TP' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'SECLOG.DG' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'REQMENU.TP' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'RCMSGLIB.DG' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'RCMERR.DG' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'RCMCFG.XML' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'PSRBWLD.CM' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'PR_ONLN.VR' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'PR_OFFLN.VR' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'PROFIBUS.SV' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'POSREG.VR' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'PNS0002.TP' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'PNS0001.TP' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'PLCFMOV.VR' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'PLCFCAL.VR' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'PLACE_PICK.TP' is saved          
26-AUG-21 16:25 :30
========================================
FILE 'PLACE_PART.TP' is saved          
26-AUG-21 16:25 :30
========================================
FILE 'PLACE.TP' is saved               
26-AUG-21 16:25 :30
========================================
FILE 'PICKFRAME.TP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'PICK.TP' is saved                
26-AUG-21 16:25 :30
========================================
FILE 'PALREG.VR' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'ORDERFIL.DAT' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'OPENCHUCK.TP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'NUMREG.VR' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'NOTIFY.DG' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'NEW.TP' is saved                 
26-AUG-21 16:25 :30
========================================
FILE 'MOVE_SAFE.TP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'MOVEHOME.TP' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'MOVE2PICK.TP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'MOVE2PERCHPT.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'MOVE2PERCH90.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'MOVE2MAINT.TP' is saved          
26-AUG-21 16:25 :30
========================================
FILE 'MOVE2LOAD.TP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'MOVE2APPRCH.TP' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'MIXLOGIC.SV' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'MEMCHECK.DG' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'MAIN.TP' is saved                
26-AUG-21 16:25 :30
========================================
FILE 'LR7L.DT' is saved                
26-AUG-21 16:25 :30
========================================
FILE 'LOGBOOK.LS' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'LOADFRAME.TP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'LOAD.TP' is saved                
26-AUG-21 16:25 :30
========================================
FILE 'IRC_STLABEL.VR' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'IRC_STATUS.VR' is saved          
26-AUG-21 16:25 :30
========================================
FILE 'IRC_MSG.VR' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'IRC_COUNTER.VR' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'IPKDMP.ZIP' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'IOSTATUS.CM' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'INIT_APPCH_OFST.TP' is saved     
26-AUG-21 16:25 :30
========================================
FILE 'INIT.TP' is saved                
26-AUG-21 16:25 :30
========================================
FILE 'INCR_POSITION.TP' is saved       
26-AUG-21 16:25 :30
========================================
FILE 'HTTPKCL.VR' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'HTCOLREC.VR' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'HIST.LS' is saved                
26-AUG-21 16:25 :30
========================================
FILE 'HEAVYPAYLOAD.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'HAPTIC.SV' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'GRIP_2_OPEN.TP' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'GRIP_2_CLOSE.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'GRIP_1_OPEN.TP' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'GRIP_1_CLOSE.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'GRIPPER_OPEN.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'GRIPPER_CLOSE.TP' is saved       
26-AUG-21 16:25 :30
========================================
FILE 'GRID.TP' is saved                
26-AUG-21 16:25 :30
========================================
FILE 'GO_SAFE_PERCH.TP' is saved       
26-AUG-21 16:25 :30
========================================
FILE 'GO_PERCH.TP' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'GO_MID_PT.TP' is saved           
26-AUG-21 16:25 :30
========================================
FILE 'GO_HOME.TP' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'GOPERCHERR.TP' is saved          
26-AUG-21 16:25 :30
========================================
FILE 'GOMIDPTERR.TP' is saved          
26-AUG-21 16:25 :30
========================================
FILE 'GIGELOG.DG' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'GET_ROW_COL.TP' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'GET_PL_APP_PT.TP' is saved       
26-AUG-21 16:25 :30
========================================
FILE 'GET_PLACE_ROW_COL.TP' is saved   
26-AUG-21 16:25 :30
========================================
FILE 'GET_PLACE_PT.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'GET_PICK_PT.TP' is saved         
26-AUG-21 16:25 :30
========================================
FILE 'GET_PART.TP' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'GET_APPCH_PT.TP' is saved        
26-AUG-21 16:25 :30
========================================
FILE 'GETDATA.TP' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'GEMDATA.VR' is saved             
26-AUG-21 16:25 :30
========================================
FILE 'FTPLOG.DG' is saved              
26-AUG-21 16:25 :30
========================================
FILE 'FRAMEVAR.VR' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'FLEXUIF.XML' is saved            
26-AUG-21 16:25 :30
========================================
FILE 'FLEXEVENT.DG' is saved           
26-AUG-21 16:25 :28
========================================
FILE 'ETHERNET.DG' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'ERRSYS.LS' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'ERRPWD.LS' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'ERROR.TP' is saved               
26-AUG-21 16:25 :28
========================================
FILE 'ERRMOT.LS' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'ERRHIST.LS' is saved             
26-AUG-21 16:25 :28
========================================
FILE 'ERREXT.LS' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'ERRCURR.LS' is saved             
26-AUG-21 16:25 :28
========================================
FILE 'ERRCOMM.LS' is saved             
26-AUG-21 16:25 :28
========================================
FILE 'ERRAPP.LS' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'ERRALL.LS' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'ERRACT.LS' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'EMPTYPAYLOAD.TP' is saved        
26-AUG-21 16:25 :28
========================================
FILE 'EMAIL.DG' is saved               
26-AUG-21 16:25 :28
========================================
FILE 'DIOCFGSV.IO' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DF_MOTN0.DF' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DF_LOGI6.DF' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DF_LOGI5.DF' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DF_LOGI4.DF' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DF_LOGI3.DF' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DF_LOGI2.DF' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DF_LOGI1.DF' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DCSVRFY.DG' is saved             
26-AUG-21 16:25 :28
========================================
FILE 'DCSDIFF.DG' is saved             
26-AUG-21 16:25 :28
========================================
FILE 'DCSCHG03.DG' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DCSCHG02.DG' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'DCSCHG01.DG' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'CONSLOG.DG' is saved             
26-AUG-21 16:25 :28
========================================
FILE 'COMSET.VR' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'CLOSE_CHUCK.TP' is saved         
26-AUG-21 16:25 :28
========================================
FILE 'CHK_PART_PRES.TP' is saved       
26-AUG-21 16:25 :28
========================================
FILE 'CHK_PALLET_POSITION.TP' is saved 
26-AUG-21 16:25 :28
========================================
FILE 'CHK_GRIP_STATUS.TP' is saved     
26-AUG-21 16:25 :28
========================================
FILE 'CHK_CHUCK_STATUS.TP' is saved    
26-AUG-21 16:25 :28
========================================
FILE 'CHECK_GRIP_OPER.TP' is saved     
26-AUG-21 16:25 :28
========================================
FILE 'CHECK_CHUCK_OPER.TP' is saved    
26-AUG-21 16:25 :28
========================================
FILE 'CELLIO.SV' is saved              
26-AUG-21 16:25 :28
========================================
FILE 'BS.TP' is saved                  
26-AUG-21 16:25 :28
========================================
FILE 'BICSETUP.VR' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'BG001.TP' is saved               
26-AUG-21 16:25 :28
========================================
FILE 'BACKDATE.DT' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'ATERRJOB.VR' is saved            
26-AUG-21 16:25 :28
========================================
FILE 'AAVMMAIN.VR' is saved            
26-AUG-21 16:25 :28
========================================
FILE '-BCKEDT-.TP' is saved            
26-AUG-21 16:25 :28
========================================
FILE '-BCKED9-.TP' is saved            
26-AUG-21 16:25 :28
========================================
FILE '-BCKED8-.TP' is saved            
26-AUG-21 16:25 :28
========================================
FILE '-BCKED2-.TP' is saved            
26-AUG-21 16:25 :28
========================================
F4([CHOICE]) is pressed                
26-AUG-21 16:12 :04
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
System/Config\\\\\\\\\\\\\\\\\       0 0                                        
                                  42/65                                         
26  Auto display of alarm menu:   FALSE                                         
27  Force Message:         ENABLE                                               
28  Allow Force I/O in AUTO mode: TRUE                                          
29  Allow chg. ovrd. in AUTO mode:TRUE                                          
30  Signal to set in AUTO mode DO[    0]                                        
31  Signal to set in T1 mode   DO[    0]                                        
32  Signal to set in T2 mode   DO[    0]                                        
33  Signal to set if E-STOP    DO[    0]                                        
34  Set if INPUT SIMULATED     DO[    0]                                        
35  Set if OUTPUT SIMULATED    DO[    0]                                        
36  Sim. Input Wait Delay:      0.00 sec                                        
37  Set if Sim. Skip Enabled:  DO[    0]                                        
38  Set when prompt displayed: DO[    0]                                        
39  Output when WAIT on Input:<*DETAIL*>                                        
40  Signal if OVERRIDE = 100   DO[    0]                                        
41  Hand broken :             <*GROUPS*>                                        
42  Remote/Local setup:    OP\panel\key                                         
43    External I/O(ON:Remote):DI [  137]                                        
44  UOP auto assignment:  None                                                  
45  Multi Program Selection:      TRUE                                          
46  WAIT at Taught Position:      FALSE                                         
                                                                                
[ TYPE ]                [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
26-AUG-21 16:12 :04
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
System/Config\\\\\\\\\\\\\\\\\       0 0                                        
                                  42/65                                         
26  Auto display of alarm menu:   FALSE                                         
27  Force Message:         ENABLE                                               
28  Allow Force I/O in AUTO mode: TRUE                                          
29  Allow chg. ovrd. in AUTO mode:TRUE                                          
30  Signal to set in AUTO mode DO[    0]                                        
31  Signal to set in T1 mode   DO[    0]                                        
32  Signal to set in T2 mode   DO[    0]                                        
33  Signal to set if E-STOP    DO[    0]                                        
34  Set if INPUT SIMULATED     DO[    0]                                        
35  Set if OUTPUT SIMULATED    DO[    0]                                        
36  Sim. Input Wait Delay:      0.00 sec                                        
37  Set if Sim. Skip Enabled:  DO[    0]                                        
38  Set when prompt displayed: DO[    0]                                        
39  Output when WAIT on Input:<*DETAIL*>                                        
40  Signal if OVERRIDE = 100   DO[    0]                                        
41  Hand broken :             <*GROUPS*>                                        
42  Remote/Local setup:    OP\panel\key                                         
43    External I/O(ON:Remote):DI [  137]                                        
44  UOP auto assignment:  None                                                  
45  Multi Program Selection:      TRUE                                          
46  WAIT at Taught Position:      FALSE                                         
                                                                                
[ TYPE ]                [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
26-AUG-21 16:12 :04
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
System/Config\\\\\\\\\\\\\\\\\       0 0                                        
                                  42/65                                         
26  Auto display of alarm menu:   FALSE                                         
27  Force Message:         ENABLE                                               
28  Allow Force I/O in AUTO mode: TRUE                                          
29  Allow chg. ovrd. in AUTO mode:TRUE                                          
30  Signal to set in AUTO mode DO[    0]                                        
31  Signal to set in T1 mode   DO[    0]                                        
32  Signal to set in T2 mode   DO[    0]                                        
33  Signal to set if E-STOP    DO[    0]                                        
34  Set if INPUT SIMULATED     DO[    0]                                        
35  Set if OUTPUT SIMULATED    DO[    0]                                        
36  Sim. Input Wait Delay:      0.00 sec                                        
37  Set if Sim. Skip Enabled:  DO[    0]                                        
38  Set when prompt displayed: DO[    0]                                        
39  Output when WAIT on Input:<*DETAIL*>                                        
40  Signal if OVERRIDE = 100   DO[    0]                                        
41  Hand broken :             <*GROUPS*>                                        
42  Remote/Local setup:    OP\panel\key                                         
43    External I/O(ON:Remote):DI [  137]                                        
44  UOP auto assignment:  None                                                  
45  Multi Program Selection:      TRUE                                          
46  WAIT at Taught Position:      FALSE                                         
                                                                                
[ TYPE ]                [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
26-AUG-21 16:12 :00
--Screen image--------------------------
                                                                                
CLOSE_CHUCK       LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
System/Config\\\\\\\\\\\\\\\\\       0 0                                        
                                  42/65                                         
26  Auto display of alarm menu:   FALSE                                         
27  Force Message:         ENABLE                                               
28  Allow Force I/O in AUTO mode: TRUE                                          
29  Allow chg. ovrd. in AUTO mode:TRUE                                          
30  Signal to set in AUTO mode DO[    0]                                        
31  Signal to set in T1 mode   DO[    0]                                        
32  Signal to set in T2 mode   DO[    0]                                        
33  Signal to set if E-STOP    DO[    0]                                        
34  Set if INPUT SIMULATED     DO[    0]                                        
35  Set if OUTPUT SIMULATED    DO[    0]                                        
36  Sim. Input Wait Delay:      0.00 sec                                        
37  Set if Sim. Skip Enabled:  DO[    0]                                        
38  Set when prompt displayed: DO[    0]                                        
39  Output when WAIT on Input:<*DETAIL*>                                        
40  Signal if OVERRIDE = 100   DO[    0]                                        
41  Hand broken :             <*GROUPS*>                                        
42  Remote/Local setup:    OP\panel\key                                         
43    External I/O(ON:Remote):DI [  137]                                        
44  UOP auto assignment:  None                                                  
45  Multi Program Selection:      TRUE                                          
46  WAIT at Taught Position:      FALSE                                         
                                                                                
[ TYPE ]                [CHOICE]                                                
========================================
ENTER is pressed                       
26-AUG-21 16:11 :54
========================================
ENTER is pressed                       
26-AUG-21 16:11 :52
========================================
R E S E T                              
                                       
                              00000000 
26-AUG-21 15:55 :28
========================================
FILE '_HOME.TP' is saved               
26-AUG-21 15:55 :28
========================================
FILE 'ZDLOG.DG' is saved               
26-AUG-21 15:55 :28
========================================
FILE 'WAIT_ON_CNC.TP' is saved         
26-AUG-21 15:55 :28
========================================
FILE 'VTRNDIAG.LS' is saved            
26-AUG-21 15:55 :28
========================================
FILE 'VIMGDIAG.ZIP' is saved           
26-AUG-21 15:55 :28
========================================
FILE 'VDEVDIAG.DAT' is saved           
26-AUG-21 15:55 :28
========================================
FILE 'VCMRINIT.VR' is saved            
26-AUG-21 15:55 :28
========================================
FILE 'VARCHG.XML' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'USR_WORK.VR' is saved            
26-AUG-21 15:55 :28
========================================
FILE 'UPDTLOG.LS' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'UPDATES.DAT' is saved            
26-AUG-21 15:55 :28
========================================
FILE 'UNLOAD.TP' is saved              
26-AUG-21 15:55 :28
========================================
FILE 'TPEINS.XML' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'TPACCN.DG' is saved              
26-AUG-21 15:55 :28
========================================
FILE 'TESTA.TP' is saved               
26-AUG-21 15:55 :28
========================================
FILE 'SYSVARS.SV' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'SYSUIF.SV' is saved              
26-AUG-21 15:55 :28
========================================
FILE 'SYSSERVO.SV' is saved            
26-AUG-21 15:55 :28
========================================
FILE 'SYSPASS.SV' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'SYSMAST.SV' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'SYSMACRO.SV' is saved            
26-AUG-21 15:55 :28
========================================
FILE 'SYSHOST.SV' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'SYSFSAC.SV' is saved             
26-AUG-21 15:55 :28
========================================
FILE 'SYSFRAME.SV' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'SWIUPDT.VR' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'SV_ADJST.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'SUMMARY.DG' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'STRREG.VR' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'SHADOW.DG' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'SET_PICK_OFST.TP' is saved       
26-AUG-21 15:55 :26
========================================
FILE 'SENDSYSV.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'SENDEVNT.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'SENDDATA.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'SECLOG.DG' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'REQMENU.TP' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'RCMSGLIB.DG' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'RCMERR.DG' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'RCMCFG.XML' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'PSRBWLD.CM' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'PR_ONLN.VR' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'PR_OFFLN.VR' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'PROFIBUS.SV' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'POSREG.VR' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'PNS0002.TP' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'PNS0001.TP' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'PLCFMOV.VR' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'PLCFCAL.VR' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'PLACE_PICK.TP' is saved          
26-AUG-21 15:55 :26
========================================
FILE 'PLACE_PART.TP' is saved          
26-AUG-21 15:55 :26
========================================
FILE 'PLACE.TP' is saved               
26-AUG-21 15:55 :26
========================================
FILE 'PICKFRAME.TP' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'PICK.TP' is saved                
26-AUG-21 15:55 :26
========================================
FILE 'PALREG.VR' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'ORDERFIL.DAT' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'OPENCHUCK.TP' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'NUMREG.VR' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'NOTIFY.DG' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'NEW.TP' is saved                 
26-AUG-21 15:55 :26
========================================
FILE 'MOVE_SAFE.TP' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'MOVEHOME.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'MOVE2PICK.TP' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'MOVE2PERCHPT.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'MOVE2PERCH90.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'MOVE2MAINT.TP' is saved          
26-AUG-21 15:55 :26
========================================
FILE 'MOVE2LOAD.TP' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'MOVE2APPRCH.TP' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'MIXLOGIC.SV' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'MEMCHECK.DG' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'MAIN.TP' is saved                
26-AUG-21 15:55 :26
========================================
FILE 'LR7L.DT' is saved                
26-AUG-21 15:55 :26
========================================
FILE 'LOGBOOK.LS' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'LOADFRAME.TP' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'LOAD.TP' is saved                
26-AUG-21 15:55 :26
========================================
FILE 'IRC_STLABEL.VR' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'IRC_STATUS.VR' is saved          
26-AUG-21 15:55 :26
========================================
FILE 'IRC_MSG.VR' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'IRC_COUNTER.VR' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'IPKDMP.ZIP' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'IOSTATUS.CM' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'INIT_APPCH_OFST.TP' is saved     
26-AUG-21 15:55 :26
========================================
FILE 'INIT.TP' is saved                
26-AUG-21 15:55 :26
========================================
FILE 'INCR_POSITION.TP' is saved       
26-AUG-21 15:55 :26
========================================
FILE 'HTTPKCL.VR' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'HTCOLREC.VR' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'HIST.LS' is saved                
26-AUG-21 15:55 :26
========================================
FILE 'HEAVYPAYLOAD.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'HAPTIC.SV' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'GRIP_2_OPEN.TP' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'GRIP_2_CLOSE.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'GRIP_1_OPEN.TP' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'GRIP_1_CLOSE.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'GRIPPER_OPEN.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'GRIPPER_CLOSE.TP' is saved       
26-AUG-21 15:55 :26
========================================
FILE 'GRID.TP' is saved                
26-AUG-21 15:55 :26
========================================
FILE 'GO_SAFE_PERCH.TP' is saved       
26-AUG-21 15:55 :26
========================================
FILE 'GO_PERCH.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'GO_MID_PT.TP' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'GO_HOME.TP' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'GOPERCHERR.TP' is saved          
26-AUG-21 15:55 :26
========================================
FILE 'GOMIDPTERR.TP' is saved          
26-AUG-21 15:55 :26
========================================
FILE 'GIGELOG.DG' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'GET_ROW_COL.TP' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'GET_PL_APP_PT.TP' is saved       
26-AUG-21 15:55 :26
========================================
FILE 'GET_PLACE_ROW_COL.TP' is saved   
26-AUG-21 15:55 :26
========================================
FILE 'GET_PLACE_PT.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'GET_PICK_PT.TP' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'GET_PART.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'GET_APPCH_PT.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'GETDATA.TP' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'GEMDATA.VR' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'FTPLOG.DG' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'FRAMEVAR.VR' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'FLEXUIF.XML' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'FLEXEVENT.DG' is saved           
26-AUG-21 15:55 :26
========================================
FILE 'ETHERNET.DG' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'ERRSYS.LS' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'ERRPWD.LS' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'ERROR.TP' is saved               
26-AUG-21 15:55 :26
========================================
FILE 'ERRMOT.LS' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'ERRHIST.LS' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'ERREXT.LS' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'ERRCURR.LS' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'ERRCOMM.LS' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'ERRAPP.LS' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'ERRALL.LS' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'ERRACT.LS' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'EMPTYPAYLOAD.TP' is saved        
26-AUG-21 15:55 :26
========================================
FILE 'EMAIL.DG' is saved               
26-AUG-21 15:55 :26
========================================
FILE 'DIOCFGSV.IO' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DF_MOTN0.DF' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DF_LOGI6.DF' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DF_LOGI5.DF' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DF_LOGI4.DF' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DF_LOGI3.DF' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DF_LOGI2.DF' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DF_LOGI1.DF' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DCSVRFY.DG' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'DCSDIFF.DG' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'DCSCHG03.DG' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DCSCHG02.DG' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'DCSCHG01.DG' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'CONSLOG.DG' is saved             
26-AUG-21 15:55 :26
========================================
FILE 'COMSET.VR' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'CLOSE_CHUCK.TP' is saved         
26-AUG-21 15:55 :26
========================================
FILE 'CHK_PART_PRES.TP' is saved       
26-AUG-21 15:55 :26
========================================
FILE 'CHK_PALLET_POSITION.TP' is saved 
26-AUG-21 15:55 :26
========================================
FILE 'CHK_GRIP_STATUS.TP' is saved     
26-AUG-21 15:55 :26
========================================
FILE 'CHK_CHUCK_STATUS.TP' is saved    
26-AUG-21 15:55 :26
========================================
FILE 'CHECK_GRIP_OPER.TP' is saved     
26-AUG-21 15:55 :26
========================================
FILE 'CHECK_CHUCK_OPER.TP' is saved    
26-AUG-21 15:55 :26
========================================
FILE 'CELLIO.SV' is saved              
26-AUG-21 15:55 :26
========================================
FILE 'BS.TP' is saved                  
26-AUG-21 15:55 :26
========================================
FILE 'BICSETUP.VR' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'BG001.TP' is saved               
26-AUG-21 15:55 :26
========================================
FILE 'BACKDATE.DT' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'ATERRJOB.VR' is saved            
26-AUG-21 15:55 :26
========================================
FILE 'AAVMMAIN.VR' is saved            
26-AUG-21 15:55 :26
========================================
FILE '-BCKEDT-.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE '-BCKED9-.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE '-BCKED8-.TP' is saved            
26-AUG-21 15:55 :26
========================================
FILE '-BCKED2-.TP' is saved            
26-AUG-21 15:55 :26
========================================
R E S E T                              
                                       
                              00000000 
26-AUG-21 15:25 :24
========================================
FILE '_HOME.TP' is saved               
26-AUG-21 15:25 :24
========================================
FILE 'ZDLOG.DG' is saved               
26-AUG-21 15:25 :24
========================================
FILE 'WAIT_ON_CNC.TP' is saved         
26-AUG-21 15:25 :24
========================================
FILE 'VTRNDIAG.LS' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'VIMGDIAG.ZIP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'VDEVDIAG.DAT' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'VCMRINIT.VR' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'VARCHG.XML' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'USR_WORK.VR' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'UPDTLOG.LS' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'UPDATES.DAT' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'UNLOAD.TP' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'TPEINS.XML' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'TPACCN.DG' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'TESTA.TP' is saved               
26-AUG-21 15:25 :24
========================================
FILE 'SYSVARS.SV' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'SYSUIF.SV' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'SYSSERVO.SV' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'SYSPASS.SV' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'SYSMAST.SV' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'SYSMACRO.SV' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'SYSHOST.SV' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'SYSFSAC.SV' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'SYSFRAME.SV' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'SWIUPDT.VR' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'SV_ADJST.TP' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'SUMMARY.DG' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'STRREG.VR' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'SHADOW.DG' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'SET_PICK_OFST.TP' is saved       
26-AUG-21 15:25 :24
========================================
FILE 'SENDSYSV.TP' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'SENDEVNT.TP' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'SENDDATA.TP' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'SECLOG.DG' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'REQMENU.TP' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'RCMSGLIB.DG' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'RCMERR.DG' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'RCMCFG.XML' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'PSRBWLD.CM' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'PR_ONLN.VR' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'PR_OFFLN.VR' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'PROFIBUS.SV' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'POSREG.VR' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'PNS0002.TP' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'PNS0001.TP' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'PLCFMOV.VR' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'PLCFCAL.VR' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'PLACE_PICK.TP' is saved          
26-AUG-21 15:25 :24
========================================
FILE 'PLACE_PART.TP' is saved          
26-AUG-21 15:25 :24
========================================
FILE 'PLACE.TP' is saved               
26-AUG-21 15:25 :24
========================================
FILE 'PICKFRAME.TP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'PICK.TP' is saved                
26-AUG-21 15:25 :24
========================================
FILE 'PALREG.VR' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'ORDERFIL.DAT' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'OPENCHUCK.TP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'NUMREG.VR' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'NOTIFY.DG' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'NEW.TP' is saved                 
26-AUG-21 15:25 :24
========================================
FILE 'MOVE_SAFE.TP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'MOVEHOME.TP' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'MOVE2PICK.TP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'MOVE2PERCHPT.TP' is saved        
26-AUG-21 15:25 :24
========================================
FILE 'MOVE2PERCH90.TP' is saved        
26-AUG-21 15:25 :24
========================================
FILE 'MOVE2MAINT.TP' is saved          
26-AUG-21 15:25 :24
========================================
FILE 'MOVE2LOAD.TP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'MOVE2APPRCH.TP' is saved         
26-AUG-21 15:25 :24
========================================
FILE 'MIXLOGIC.SV' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'MEMCHECK.DG' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'MAIN.TP' is saved                
26-AUG-21 15:25 :24
========================================
FILE 'LR7L.DT' is saved                
26-AUG-21 15:25 :24
========================================
FILE 'LOGBOOK.LS' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'LOADFRAME.TP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'LOAD.TP' is saved                
26-AUG-21 15:25 :24
========================================
FILE 'IRC_STLABEL.VR' is saved         
26-AUG-21 15:25 :24
========================================
FILE 'IRC_STATUS.VR' is saved          
26-AUG-21 15:25 :24
========================================
FILE 'IRC_MSG.VR' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'IRC_COUNTER.VR' is saved         
26-AUG-21 15:25 :24
========================================
FILE 'IPKDMP.ZIP' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'IOSTATUS.CM' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'INIT_APPCH_OFST.TP' is saved     
26-AUG-21 15:25 :24
========================================
FILE 'INIT.TP' is saved                
26-AUG-21 15:25 :24
========================================
FILE 'INCR_POSITION.TP' is saved       
26-AUG-21 15:25 :24
========================================
FILE 'HTTPKCL.VR' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'HTCOLREC.VR' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'HIST.LS' is saved                
26-AUG-21 15:25 :24
========================================
FILE 'HEAVYPAYLOAD.TP' is saved        
26-AUG-21 15:25 :24
========================================
FILE 'HAPTIC.SV' is saved              
26-AUG-21 15:25 :24
========================================
FILE 'GRIP_2_OPEN.TP' is saved         
26-AUG-21 15:25 :24
========================================
FILE 'GRIP_2_CLOSE.TP' is saved        
26-AUG-21 15:25 :24
========================================
FILE 'GRIP_1_OPEN.TP' is saved         
26-AUG-21 15:25 :24
========================================
FILE 'GRIP_1_CLOSE.TP' is saved        
26-AUG-21 15:25 :24
========================================
FILE 'GRIPPER_OPEN.TP' is saved        
26-AUG-21 15:25 :24
========================================
FILE 'GRIPPER_CLOSE.TP' is saved       
26-AUG-21 15:25 :24
========================================
FILE 'GRID.TP' is saved                
26-AUG-21 15:25 :24
========================================
FILE 'GO_SAFE_PERCH.TP' is saved       
26-AUG-21 15:25 :24
========================================
FILE 'GO_PERCH.TP' is saved            
26-AUG-21 15:25 :24
========================================
FILE 'GO_MID_PT.TP' is saved           
26-AUG-21 15:25 :24
========================================
FILE 'GO_HOME.TP' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'GOPERCHERR.TP' is saved          
26-AUG-21 15:25 :24
========================================
FILE 'GOMIDPTERR.TP' is saved          
26-AUG-21 15:25 :24
========================================
FILE 'GIGELOG.DG' is saved             
26-AUG-21 15:25 :24
========================================
FILE 'GET_ROW_COL.TP' is saved         
26-AUG-21 15:25 :24
========================================
FILE 'GET_PL_APP_PT.TP' is saved       
26-AUG-21 15:25 :24
========================================
FILE 'GET_PLACE_ROW_COL.TP' is saved   
26-AUG-21 15:25 :24
========================================
FILE 'GET_PLACE_PT.TP' is saved        
26-AUG-21 15:25 :24
========================================
FILE 'GET_PICK_PT.TP' is saved         
26-AUG-21 15:25 :22
========================================
FILE 'GET_PART.TP' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'GET_APPCH_PT.TP' is saved        
26-AUG-21 15:25 :22
========================================
FILE 'GETDATA.TP' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'GEMDATA.VR' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'FTPLOG.DG' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'FRAMEVAR.VR' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'FLEXUIF.XML' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'FLEXEVENT.DG' is saved           
26-AUG-21 15:25 :22
========================================
FILE 'ETHERNET.DG' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'ERRSYS.LS' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'ERRPWD.LS' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'ERROR.TP' is saved               
26-AUG-21 15:25 :22
========================================
FILE 'ERRMOT.LS' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'ERRHIST.LS' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'ERREXT.LS' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'ERRCURR.LS' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'ERRCOMM.LS' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'ERRAPP.LS' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'ERRALL.LS' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'ERRACT.LS' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'EMPTYPAYLOAD.TP' is saved        
26-AUG-21 15:25 :22
========================================
FILE 'EMAIL.DG' is saved               
26-AUG-21 15:25 :22
========================================
FILE 'DIOCFGSV.IO' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DF_MOTN0.DF' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DF_LOGI6.DF' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DF_LOGI5.DF' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DF_LOGI4.DF' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DF_LOGI3.DF' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DF_LOGI2.DF' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DF_LOGI1.DF' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DCSVRFY.DG' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'DCSDIFF.DG' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'DCSCHG03.DG' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DCSCHG02.DG' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'DCSCHG01.DG' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'CONSLOG.DG' is saved             
26-AUG-21 15:25 :22
========================================
FILE 'COMSET.VR' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'CLOSE_CHUCK.TP' is saved         
26-AUG-21 15:25 :22
========================================
FILE 'CHK_PART_PRES.TP' is saved       
26-AUG-21 15:25 :22
========================================
FILE 'CHK_PALLET_POSITION.TP' is saved 
26-AUG-21 15:25 :22
========================================
FILE 'CHK_GRIP_STATUS.TP' is saved     
26-AUG-21 15:25 :22
========================================
FILE 'CHK_CHUCK_STATUS.TP' is saved    
26-AUG-21 15:25 :22
========================================
FILE 'CHECK_GRIP_OPER.TP' is saved     
26-AUG-21 15:25 :22
========================================
FILE 'CHECK_CHUCK_OPER.TP' is saved    
26-AUG-21 15:25 :22
========================================
FILE 'CELLIO.SV' is saved              
26-AUG-21 15:25 :22
========================================
FILE 'BS.TP' is saved                  
26-AUG-21 15:25 :22
========================================
FILE 'BICSETUP.VR' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'BG001.TP' is saved               
26-AUG-21 15:25 :22
========================================
FILE 'BACKDATE.DT' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'ATERRJOB.VR' is saved            
26-AUG-21 15:25 :22
========================================
FILE 'AAVMMAIN.VR' is saved            
26-AUG-21 15:25 :22
========================================
FILE '-BCKEDT-.TP' is saved            
26-AUG-21 15:25 :22
========================================
FILE '-BCKED9-.TP' is saved            
26-AUG-21 15:25 :22
========================================
FILE '-BCKED8-.TP' is saved            
26-AUG-21 15:25 :22
========================================
FILE '-BCKED2-.TP' is saved            
26-AUG-21 15:25 :22
========================================
Focus changed to 'System/Config'       
26-AUG-21 14:55 :32
========================================
R E S E T                              
                                       
                              00000000 
26-AUG-21 14:55 :22
========================================
FILE '_HOME.TP' is saved               
26-AUG-21 14:55 :22
========================================
FILE 'ZDLOG.DG' is saved               
26-AUG-21 14:55 :22
========================================
FILE 'WAIT_ON_CNC.TP' is saved         
26-AUG-21 14:55 :22
========================================
FILE 'VTRNDIAG.LS' is saved            
26-AUG-21 14:55 :22
========================================
FILE 'VIMGDIAG.ZIP' is saved           
26-AUG-21 14:55 :22
========================================
FILE 'VDEVDIAG.DAT' is saved           
26-AUG-21 14:55 :22
========================================
FILE 'VCMRINIT.VR' is saved            
26-AUG-21 14:55 :22
========================================
FILE 'VARCHG.XML' is saved             
26-AUG-21 14:55 :22
========================================
FILE 'USR_WORK.VR' is saved            
26-AUG-21 14:55 :22
========================================
FILE 'UPDTLOG.LS' is saved             
26-AUG-21 14:55 :22
========================================
FILE 'UPDATES.DAT' is saved            
26-AUG-21 14:55 :22
========================================
FILE 'UNLOAD.TP' is saved              
26-AUG-21 14:55 :22
========================================
FILE 'TPEINS.XML' is saved             
26-AUG-21 14:55 :22
========================================
FILE 'TPACCN.DG' is saved              
26-AUG-21 14:55 :22
========================================
FILE 'TESTA.TP' is saved               
26-AUG-21 14:55 :22
========================================
FILE 'SYSVARS.SV' is saved             
26-AUG-21 14:55 :22
========================================
FILE 'SYSUIF.SV' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'SYSSERVO.SV' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'SYSPASS.SV' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'SYSMAST.SV' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'SYSMACRO.SV' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'SYSHOST.SV' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'SYSFSAC.SV' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'SYSFRAME.SV' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'SWIUPDT.VR' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'SV_ADJST.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'SUMMARY.DG' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'STRREG.VR' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'SHADOW.DG' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'SET_PICK_OFST.TP' is saved       
26-AUG-21 14:55 :20
========================================
FILE 'SENDSYSV.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'SENDEVNT.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'SENDDATA.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'SECLOG.DG' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'REQMENU.TP' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'RCMSGLIB.DG' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'RCMERR.DG' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'RCMCFG.XML' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'PSRBWLD.CM' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'PR_ONLN.VR' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'PR_OFFLN.VR' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'PROFIBUS.SV' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'POSREG.VR' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'PNS0002.TP' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'PNS0001.TP' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'PLCFMOV.VR' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'PLCFCAL.VR' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'PLACE_PICK.TP' is saved          
26-AUG-21 14:55 :20
========================================
FILE 'PLACE_PART.TP' is saved          
26-AUG-21 14:55 :20
========================================
FILE 'PLACE.TP' is saved               
26-AUG-21 14:55 :20
========================================
FILE 'PICKFRAME.TP' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'PICK.TP' is saved                
26-AUG-21 14:55 :20
========================================
FILE 'PALREG.VR' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'ORDERFIL.DAT' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'OPENCHUCK.TP' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'NUMREG.VR' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'NOTIFY.DG' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'NEW.TP' is saved                 
26-AUG-21 14:55 :20
========================================
FILE 'MOVE_SAFE.TP' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'MOVEHOME.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'MOVE2PICK.TP' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'MOVE2PERCHPT.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'MOVE2PERCH90.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'MOVE2MAINT.TP' is saved          
26-AUG-21 14:55 :20
========================================
FILE 'MOVE2LOAD.TP' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'MOVE2APPRCH.TP' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'MIXLOGIC.SV' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'MEMCHECK.DG' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'MAIN.TP' is saved                
26-AUG-21 14:55 :20
========================================
FILE 'LR7L.DT' is saved                
26-AUG-21 14:55 :20
========================================
FILE 'LOGBOOK.LS' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'LOADFRAME.TP' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'LOAD.TP' is saved                
26-AUG-21 14:55 :20
========================================
FILE 'IRC_STLABEL.VR' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'IRC_STATUS.VR' is saved          
26-AUG-21 14:55 :20
========================================
FILE 'IRC_MSG.VR' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'IRC_COUNTER.VR' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'IPKDMP.ZIP' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'IOSTATUS.CM' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'INIT_APPCH_OFST.TP' is saved     
26-AUG-21 14:55 :20
========================================
FILE 'INIT.TP' is saved                
26-AUG-21 14:55 :20
========================================
FILE 'INCR_POSITION.TP' is saved       
26-AUG-21 14:55 :20
========================================
FILE 'HTTPKCL.VR' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'HTCOLREC.VR' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'HIST.LS' is saved                
26-AUG-21 14:55 :20
========================================
FILE 'HEAVYPAYLOAD.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'HAPTIC.SV' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'GRIP_2_OPEN.TP' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'GRIP_2_CLOSE.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'GRIP_1_OPEN.TP' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'GRIP_1_CLOSE.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'GRIPPER_OPEN.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'GRIPPER_CLOSE.TP' is saved       
26-AUG-21 14:55 :20
========================================
FILE 'GRID.TP' is saved                
26-AUG-21 14:55 :20
========================================
FILE 'GO_SAFE_PERCH.TP' is saved       
26-AUG-21 14:55 :20
========================================
FILE 'GO_PERCH.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'GO_MID_PT.TP' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'GO_HOME.TP' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'GOPERCHERR.TP' is saved          
26-AUG-21 14:55 :20
========================================
FILE 'GOMIDPTERR.TP' is saved          
26-AUG-21 14:55 :20
========================================
FILE 'GIGELOG.DG' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'GET_ROW_COL.TP' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'GET_PL_APP_PT.TP' is saved       
26-AUG-21 14:55 :20
========================================
FILE 'GET_PLACE_ROW_COL.TP' is saved   
26-AUG-21 14:55 :20
========================================
FILE 'GET_PLACE_PT.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'GET_PICK_PT.TP' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'GET_PART.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'GET_APPCH_PT.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'GETDATA.TP' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'GEMDATA.VR' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'FTPLOG.DG' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'FRAMEVAR.VR' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'FLEXUIF.XML' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'FLEXEVENT.DG' is saved           
26-AUG-21 14:55 :20
========================================
FILE 'ETHERNET.DG' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'ERRSYS.LS' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'ERRPWD.LS' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'ERROR.TP' is saved               
26-AUG-21 14:55 :20
========================================
FILE 'ERRMOT.LS' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'ERRHIST.LS' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'ERREXT.LS' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'ERRCURR.LS' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'ERRCOMM.LS' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'ERRAPP.LS' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'ERRALL.LS' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'ERRACT.LS' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'EMPTYPAYLOAD.TP' is saved        
26-AUG-21 14:55 :20
========================================
FILE 'EMAIL.DG' is saved               
26-AUG-21 14:55 :20
========================================
FILE 'DIOCFGSV.IO' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DF_MOTN0.DF' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DF_LOGI6.DF' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DF_LOGI5.DF' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DF_LOGI4.DF' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DF_LOGI3.DF' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DF_LOGI2.DF' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DF_LOGI1.DF' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DCSVRFY.DG' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'DCSDIFF.DG' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'DCSCHG03.DG' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DCSCHG02.DG' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'DCSCHG01.DG' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'CONSLOG.DG' is saved             
26-AUG-21 14:55 :20
========================================
FILE 'COMSET.VR' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'CLOSE_CHUCK.TP' is saved         
26-AUG-21 14:55 :20
========================================
FILE 'CHK_PART_PRES.TP' is saved       
26-AUG-21 14:55 :20
========================================
FILE 'CHK_PALLET_POSITION.TP' is saved 
26-AUG-21 14:55 :20
========================================
FILE 'CHK_GRIP_STATUS.TP' is saved     
26-AUG-21 14:55 :20
========================================
FILE 'CHK_CHUCK_STATUS.TP' is saved    
26-AUG-21 14:55 :20
========================================
FILE 'CHECK_GRIP_OPER.TP' is saved     
26-AUG-21 14:55 :20
========================================
FILE 'CHECK_CHUCK_OPER.TP' is saved    
26-AUG-21 14:55 :20
========================================
FILE 'CELLIO.SV' is saved              
26-AUG-21 14:55 :20
========================================
FILE 'BS.TP' is saved                  
26-AUG-21 14:55 :20
========================================
FILE 'BICSETUP.VR' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'BG001.TP' is saved               
26-AUG-21 14:55 :20
========================================
FILE 'BACKDATE.DT' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'ATERRJOB.VR' is saved            
26-AUG-21 14:55 :20
========================================
FILE 'AAVMMAIN.VR' is saved            
26-AUG-21 14:55 :20
========================================
FILE '-BCKEDT-.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE '-BCKED9-.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE '-BCKED8-.TP' is saved            
26-AUG-21 14:55 :20
========================================
FILE '-BCKED2-.TP' is saved            
26-AUG-21 14:55 :20
========================================
R E S E T                              
                                       
                              00000000 
26-AUG-21 14:25 :18
========================================
FILE '_HOME.TP' is saved               
26-AUG-21 14:25 :18
========================================
FILE 'ZDLOG.DG' is saved               
26-AUG-21 14:25 :18
========================================
FILE 'WAIT_ON_CNC.TP' is saved         
26-AUG-21 14:25 :18
========================================
FILE 'VTRNDIAG.LS' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'VIMGDIAG.ZIP' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'VDEVDIAG.DAT' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'VCMRINIT.VR' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'VARCHG.XML' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'USR_WORK.VR' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'UPDTLOG.LS' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'UPDATES.DAT' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'UNLOAD.TP' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'TPEINS.XML' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'TPACCN.DG' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'TESTA.TP' is saved               
26-AUG-21 14:25 :18
========================================
FILE 'SYSVARS.SV' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'SYSUIF.SV' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'SYSSERVO.SV' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'SYSPASS.SV' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'SYSMAST.SV' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'SYSMACRO.SV' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'SYSHOST.SV' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'SYSFSAC.SV' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'SYSFRAME.SV' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'SWIUPDT.VR' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'SV_ADJST.TP' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'SUMMARY.DG' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'STRREG.VR' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'SHADOW.DG' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'SET_PICK_OFST.TP' is saved       
26-AUG-21 14:25 :18
========================================
FILE 'SENDSYSV.TP' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'SENDEVNT.TP' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'SENDDATA.TP' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'SECLOG.DG' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'REQMENU.TP' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'RCMSGLIB.DG' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'RCMERR.DG' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'RCMCFG.XML' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'PSRBWLD.CM' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'PR_ONLN.VR' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'PR_OFFLN.VR' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'PROFIBUS.SV' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'POSREG.VR' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'PNS0002.TP' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'PNS0001.TP' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'PLCFMOV.VR' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'PLCFCAL.VR' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'PLACE_PICK.TP' is saved          
26-AUG-21 14:25 :18
========================================
FILE 'PLACE_PART.TP' is saved          
26-AUG-21 14:25 :18
========================================
FILE 'PLACE.TP' is saved               
26-AUG-21 14:25 :18
========================================
FILE 'PICKFRAME.TP' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'PICK.TP' is saved                
26-AUG-21 14:25 :18
========================================
FILE 'PALREG.VR' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'ORDERFIL.DAT' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'OPENCHUCK.TP' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'NUMREG.VR' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'NOTIFY.DG' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'NEW.TP' is saved                 
26-AUG-21 14:25 :18
========================================
FILE 'MOVE_SAFE.TP' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'MOVEHOME.TP' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'MOVE2PICK.TP' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'MOVE2PERCHPT.TP' is saved        
26-AUG-21 14:25 :18
========================================
FILE 'MOVE2PERCH90.TP' is saved        
26-AUG-21 14:25 :18
========================================
FILE 'MOVE2MAINT.TP' is saved          
26-AUG-21 14:25 :18
========================================
FILE 'MOVE2LOAD.TP' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'MOVE2APPRCH.TP' is saved         
26-AUG-21 14:25 :18
========================================
FILE 'MIXLOGIC.SV' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'MEMCHECK.DG' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'MAIN.TP' is saved                
26-AUG-21 14:25 :18
========================================
FILE 'LR7L.DT' is saved                
26-AUG-21 14:25 :18
========================================
FILE 'LOGBOOK.LS' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'LOADFRAME.TP' is saved           
26-AUG-21 14:25 :18
========================================
FILE 'LOAD.TP' is saved                
26-AUG-21 14:25 :18
========================================
FILE 'IRC_STLABEL.VR' is saved         
26-AUG-21 14:25 :18
========================================
FILE 'IRC_STATUS.VR' is saved          
26-AUG-21 14:25 :18
========================================
FILE 'IRC_MSG.VR' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'IRC_COUNTER.VR' is saved         
26-AUG-21 14:25 :18
========================================
FILE 'IPKDMP.ZIP' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'IOSTATUS.CM' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'INIT_APPCH_OFST.TP' is saved     
26-AUG-21 14:25 :18
========================================
FILE 'INIT.TP' is saved                
26-AUG-21 14:25 :18
========================================
FILE 'INCR_POSITION.TP' is saved       
26-AUG-21 14:25 :18
========================================
FILE 'HTTPKCL.VR' is saved             
26-AUG-21 14:25 :18
========================================
FILE 'HTCOLREC.VR' is saved            
26-AUG-21 14:25 :18
========================================
FILE 'HIST.LS' is saved                
26-AUG-21 14:25 :18
========================================
FILE 'HEAVYPAYLOAD.TP' is saved        
26-AUG-21 14:25 :18
========================================
FILE 'HAPTIC.SV' is saved              
26-AUG-21 14:25 :18
========================================
FILE 'GRIP_2_OPEN.TP' is saved         
26-AUG-21 14:25 :16
========================================
FILE 'GRIP_2_CLOSE.TP' is saved        
26-AUG-21 14:25 :16
========================================
FILE 'GRIP_1_OPEN.TP' is saved         
26-AUG-21 14:25 :16
========================================
FILE 'GRIP_1_CLOSE.TP' is saved        
26-AUG-21 14:25 :16
========================================
FILE 'GRIPPER_OPEN.TP' is saved        
26-AUG-21 14:25 :16
========================================
FILE 'GRIPPER_CLOSE.TP' is saved       
26-AUG-21 14:25 :16
========================================
FILE 'GRID.TP' is saved                
26-AUG-21 14:25 :16
========================================
FILE 'GO_SAFE_PERCH.TP' is saved       
26-AUG-21 14:25 :16
========================================
FILE 'GO_PERCH.TP' is saved            
26-AUG-21 14:25 :16
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 SO[    3]    ON  -> OFF
Tick:   379644
TB:     2055060614
28-AUG-21 20:46 :00
========================================
 SO[    3]    OFF -> ON 
Tick:   379388
TB:     2052173976
28-AUG-21 20:46 :00
========================================
 SO[    7]    OFF -> ON 
Tick:   379356
TB:     2051750868
28-AUG-21 20:45 :58
========================================
 SO[    3]    ON  -> OFF
Tick:   3708
TB:     -1810052663
28-AUG-21 20:39 :32
========================================
 SO[    0]    ON  -> OFF
Tick:   3612
TB:     -1811252665
28-AUG-21 20:39 :32
========================================
 SO[    0]    OFF -> ON 
Tick:   1308
TB:     -1834730777
28-AUG-21 20:39 :30
========================================
 SO[    3]    OFF -> ON 
Tick:   1020
TB:     -1844287139
28-AUG-21 20:39 :30
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    ON 
 SI[    9]    ON 
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
SSI[    1]    OFF
SSI[    2]    OFF
SSI[    3]    OFF
SSI[    4]    OFF
SSI[    5]    OFF
SSI[    6]    OFF
SSI[    7]    OFF
SSI[    8]    OFF
SSI[    9]    OFF
SSI[   10]    OFF
SSI[   11]    OFF
SSI[   12]    OFF
SSI[   13]    OFF
SSI[   14]    OFF
Tick:   1009
TB:     -1844731976
28-AUG-21 20:39 :30
