ERRMOT.LS      Robot Name ROBOT 28-AUG-21 20:46:32  

1" 28-AUG-21 20:46:00 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 26-AUG-21 11:04:06 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
3" 11-AUG-21 07:06:18 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
4" 10-AUG-21 14:48:36 " SRVO-233 TP OFF in T1,T2                          " " SERVO                         00110110" 
